#ifndef __CONF_OS_H__
#define __CONF_OS_H__

#define CONFIG_OS_SCHEDULER_TYPE CONFIG_OS_SCHEDULER_USE_COMPARE
#define CONFIG_OS_USE_PRIORITY false
#define CONFIG_OS_DEBUG false
#define CONFIG_OS_USE_TICK_COUNTER true
#define CONFIG_OS_USE_16BIT_TICKS false
#define CONFIG_OS_USE_SW_INTERRUPTS false
#define CONFIG_OS_USE_EVENTS false

#define CONFIG_OS_USE_STATISTICS false

#define CONFIG_OS_SPEED_OPTIMIZATION true

#endif // __CONF_OS_H__
