eeOS (Embedded Event-driven Operating System): Public API
Public API
[eeOS]
Public application interface.
Modules
Queues
This page contains technical information related to a queue.
Defines
#define OS_ALIGN(ptr)
Align a pointer. The alignement is made forward compared to the initial pointer.
#define OS_ALIGN_BACK(ptr)
Align a pointer. The alignement is made backward compared to the initial pointer.
#define OS_CONTAINER_OF(ptr, type, member) ((type *)((uint8_t *)(ptr) - offsetof(type, member)))
Retrieve the pointer of the containing structure of the ptr element.
#define OS_MALLOC_STACK(stack_symbol, stack_size) uint8_t (stack_symbol)[(stack_size)]
Allocate memory for the stack.
#define OS_MS_TO_TICKS(time_ms) (((time_ms) * CONFIG_OS_TICK_HZ) / 1000)
Convert a delay in milliseconds to a number of ticks.
#define OS_NB_ARGS(...) (sizeof((os_ptr_t []) {__VA_ARGS__}) / sizeof(os_ptr_t))
Calculate the number of argument passed in argument to this macro.
#define OS_S_TO_TICK(time_s) ((time_s) * CONFIG_OS_TICK_HZ)
Convert a delay in seconds to a number of ticks.
Kernel Control
Control the core of the operating system
void os_yield (void)
Call the scheduler to switch to a new task that is ready to run. This function is useful for cooperative task swiching.
static void os_start (uint32_t ref_hz)
Start the task scheduling process.
static char * os_get_version (void)
Get the current version of the running operating system.
Events
Set of functions to create and manage events
static void os_event_create_from_function (struct os_event *event, bool(*trigger)(os_ptr_t), os_ptr_t args)
Create a custom event from a function.
Tasks
Set of functions to manage a task
bool os_task_create (struct os_task *task, os_proc_ptr_t task_ptr, os_ptr_t args, int stack_size, enum os_task_option options)
Create a new task. By default, the new task will be automatically added to the active task list unless specified.
void os_task_delay (os_tick_t tick_nb)
Block the execution of a task until a number of ticks have passed.CONFIG_OS_TICK_HZ can be used to estimate a time delay.
static void os_task_set_priority (struct os_task *task, enum os_priority priority)
Set a priority to a task.
static enum os_priority os_task_get_priority (struct os_task *task)
Get the priority of a task.
static void os_task_delete (struct os_task *task)
Delete a task.
static void os_task_enable (struct os_task *task)
Enable the execution a task.
static void os_task_disable (struct os_task *task)
Disable the execution of a task.
static bool os_task_is_enabled (struct os_task *task)
Check wether a task is enabled or not.
static struct os_task * os_task_get_current (void)
Get the current running task.
#define os_task_sleep(...)
Send the task to sleep and wake it up uppon a specific event.
#define os_task_sleep_ex(event_triggered,...)
Send the task to sleep and wake it up uppon a specific event.
Semaphores
Set of functions to create and control sempahores
static void os_semaphore_create (struct os_semaphore *sem, os_semaphore_counter_t counter, os_semaphore_counter_t initial_count)
Creates a counting semaphore.
static void os_binary_semaphore_create (struct os_semaphore *sem)
Creates a binary semaphore.
static void os_semaphore_create_event (struct os_event *event, struct os_semaphore *sem)
Creates an event from a semaphore. The sempahore must have been previously created before using this function.
static struct os_semaphore * os_event_get_semaphore (struct os_event *event)
Get a semaphore out of a os_event structure.
void os_semaphore_take (struct os_semaphore *sem)
Take a semaphore. If no semaphore is available, wait until it gets free.
void os_semaphore_release (struct os_semaphore *sem)
Releases a semaphore.
Mutex
Set of functions to create and control mutex
static void os_mutex_create (struct os_mutex *mutex)
Creates a mutex.
static void os_mutex_create_event (struct os_event *event, struct os_mutex *mutex)
Creates an event from a mutex. The mutex must have been previously created before using this function.
static struct os_mutex * os_event_get_mutex (struct os_event *event)
Get a mutex out of a os_event structure.
void os_mutex_lock (struct os_mutex *mutex)
Lock a mutex. If the mutex is already locked, wait until it gets unlocked.
void os_mutex_unlock (struct os_mutex *mutex)
Un-lock a mutex.
Software Interrupts
A software interrupt is a task which runs from the application context and it cannot be interrupted by the scheduler. Software interrupts are scheduled with the task scheduler. They inherit from the same priority scheme than a task.
Precondition:
CONFIG_OS_USE_SW_INTERRUPTS needs to be set
void os_interrupt_create (struct os_interrupt *interrupt, os_proc_ptr_t int_ptr, os_ptr_t args)
Setup a software interrupt.
static void os_interrupt_trigger (struct os_interrupt *interrupt)
Manually trigger a software interrupt.
static void os_interrupt_set_priority (struct os_interrupt *interrupt, enum os_priority priority)
Change the priority of a software interrupt.
static enum os_priority os_interrupt_get_priority (struct os_interrupt *interrupt)
Get the priority of a software interrupt.
void os_interrupt_trigger_on_event (struct os_interrupt *interrupt, struct os_event *event)
Trigger an interrupt on a specific event.
Debug
Useful function set for debugging purpose.
Precondition:
CONFIG_OS_DEBUG must be set
static void os_debug_stop_trace (void)
Stop tracing the operating system execution.
void os_debug_start_trace (os_ptr_t buffer, int size)
Start tracing the operation system execution. The trace will be saved inside a buffer and will be wrapped if overflowed.
static struct os_trace * os_debug_trace_get_pointer (void)
Get the current trace pointer. This will point on the next trace entry to be filled. It is part of the memory previously allocated by os_debug_start_trace.
Statistics
This set of function gives real-time statistics on the current operating system setup.
os_cy_t os_statistics_get_task_switch_time (void)
Get the average time of the context task switching in number of cycles.
os_cy_t os_statistics_get_task_switch_time_jitter (void)
Get the jitter of the context task switching in number of cycles.
uint8_t os_statistics_task_cpu_allocation (struct os_task *task)
Theoretical estimation of the CPU load of a task. It is based on the number of current active tasks in the list and their priority. The ratio of the CPU ressources is calculated as follow:
Detailed Description
Public application interface.
Define Documentation
#define OS_ALIGN (ptr)
Value:
((os_ptr_t) ((((os_intptr_t) (ptr)) + OS_COMPILER_ALIGN - 1) & \
        ~(OS_COMPILER_ALIGN - 1)))
Align a pointer. The alignement is made forward compared to the initial pointer.
Parameters:
ptr The ptr to be aligned.
Returns:
The pointer aligned.
Definition at line 318 of file os_core.h.
Referenced by os_debug_start_trace().
#define OS_ALIGN_BACK (ptr)
Value:
((os_ptr_t) ((((os_intptr_t) (ptr))) & \
        ~(OS_COMPILER_ALIGN - 1)))
Align a pointer. The alignement is made backward compared to the initial pointer.
Parameters:
ptr The ptr to be aligned.
Returns:
The pointer aligned.
Definition at line 328 of file os_core.h.
Referenced by __os_process_create().
#define OS_CONTAINER_OF (ptr, type, member) ((type *)((uint8_t *)(ptr) - offsetof(type, member)))
Retrieve the pointer of the containing structure of the ptr element.
Parameters:
ptr The ptr located inside the structure from which we want to retreive the address.
type The type of the parent structure.
member The member symbol of the parent structure.
Returns:
The address of the parent structure.
Definition at line 309 of file os_core.h.
Referenced by __os_interrupt_from_process(), and __os_task_from_process().
#define OS_MALLOC_STACK (stack_symbol, stack_size) uint8_t (stack_symbol)[(stack_size)]
Allocate memory for the stack.
This macro can be used with OS_TASK_USE_CUSTOM_STACK in order to manually allocate some memory for the stack. Here is an example code to use this macro:
 void my_func(os_ptr_t args)
 {
    ...
 }
 static OS_MALLOC_STACK(my_stack, 1024);
 struct os_task my_task;
 my_task.stack = my_stack;
 os_task_create(&my_task, my_func, NULL, 0, OS_TASK_USE_CUSTOM_STACK);
Parameters:
stack_symbol The symbol name used to refer to this stack
stack_size The size of the stack in bytes
Definition at line 57 of file os_task.h.
#define OS_MS_TO_TICKS (time_ms) (((time_ms) * CONFIG_OS_TICK_HZ) / 1000)
Convert a delay in milliseconds to a number of ticks.
Parameters:
time_ms The time (in ms) to be converted
Returns:
The number of ticks
Definition at line 345 of file os_core.h.
#define OS_NB_ARGS (...) (sizeof((os_ptr_t []) {__VA_ARGS__}) / sizeof(os_ptr_t))
Calculate the number of argument passed in argument to this macro.
Parameters:
... Arguments to be monitored
Returns:
The number of arguments passed to this macro
Definition at line 337 of file os_core.h.
#define OS_S_TO_TICK (time_s) ((time_s) * CONFIG_OS_TICK_HZ)
Convert a delay in seconds to a number of ticks.
Parameters:
time_s The time (in s) to be converted
Returns:
The number of ticks
Definition at line 353 of file os_core.h.
#define os_task_sleep (...)
Value:
do { \
            struct os_queue_event __queue_elt[OS_NB_ARGS(__VA_ARGS__)]; \
            __os_process_sleep(__os_process_get_current(), \
                __queue_elt, OS_NB_ARGS(__VA_ARGS__), \
                __VA_ARGS__); \
        } while (false);
Send the task to sleep and wake it up uppon a specific event.
Parameters:
... List of events (os_event) used to wakeup the task
Precondition:
CONFIG_OS_USE_EVENTS needs to be set
Definition at line 229 of file os_task.h.
#define os_task_sleep_ex (event_triggered, ...)
Value:
do { \
            struct os_queue_event __queue_elt[OS_NB_ARGS(__VA_ARGS__)]; \
            event_triggered = __os_process_sleep( \
                    __os_process_get_current(), \
                __queue_elt, OS_NB_ARGS(__VA_ARGS__), \
                __VA_ARGS__); \
        } while (false);
Send the task to sleep and wake it up uppon a specific event.
Parameters:
event_triggered An empty os_event pointer which will point on the event which triggered the wake up of the process.
... List of events (os_event) used to wakeup the task
Precondition:
CONFIG_OS_USE_EVENTS needs to be set
Definition at line 244 of file os_task.h.
Function Documentation
static void os_binary_semaphore_create (struct os_semaphore * sem) [inline, static]
Creates a binary semaphore.
Parameters:
sem The un-initialized sempahore structure
Definition at line 95 of file os_semaphore.h.
References os_semaphore_create().
{
    os_semaphore_create(sem, 1, 1);
}
void os_debug_start_trace (os_ptr_t buffer, int size)
Start tracing the operation system execution. The trace will be saved inside a buffer and will be wrapped if overflowed.
Parameters:
buffer Memory buffer to hold the trace
size The size in bytes of the memory buffer
Precondition:
CONFIG_OS_DEBUG_USE_TRACE must be set
Definition at line 65 of file os_debug.c.
References OS_ALIGN, and os_debug_trace_flag.
{
    /* Save the first aligned byte of the buffer */
    os_debug_trace_start = OS_ALIGN(buffer);
    /* Update the size which might have changed after the alignement */
    size -= ((int) os_debug_trace_start - (int) buffer);
    /* Compute the last trace entry ending address */
    os_debug_trace_end = os_debug_trace_start
            + size / sizeof(struct os_trace);
    /* Setup the trace pointer */
    os_debug_trace_ptr = os_debug_trace_start;
    /* Activate the trace */
    os_debug_trace_flag = true;
}
static void os_debug_stop_trace (void) [inline, static]
Stop tracing the operating system execution.
Precondition:
os_debug_start_trace must be called first
CONFIG_OS_DEBUG_USE_TRACE must be set
Definition at line 197 of file os_debug.h.
References os_debug_trace_flag.
{
    extern bool os_debug_trace_flag;
    /* Disable the trace */
    os_debug_trace_flag = false;
}
static struct os_trace* os_debug_trace_get_pointer (void) [static, read]
Get the current trace pointer. This will point on the next trace entry to be filled. It is part of the memory previously allocated by os_debug_start_trace.
Returns:
A pointer on the next trace entry.
Precondition:
os_debug_start_trace must be called first
CONFIG_OS_DEBUG_USE_TRACE must be set
Definition at line 220 of file os_debug.h.
References os_debug_trace_ptr.
{
    extern struct os_trace *os_debug_trace_ptr;
    return os_debug_trace_ptr;
}
static void os_event_create_from_function (struct os_event * event, bool(*)(os_ptr_t) trigger, os_ptr_t args) [inline, static]
Create a custom event from a function.
Parameters:
event The un-initialized event structure to be filled
trigger The boolean function to trigger the event. The event will be triggered when this function returns true.
args Arguments to pass to the trigger function
Definition at line 260 of file os_event.h.
References __os_event_create(), __os_event_custom_function_handler(), os_event_descriptor::is_triggered, and __os_event_custom_function_args::trigger.
{
    /* Create the event descriptor function */
    const struct os_event_descriptor descriptor = {
        .is_triggered = __os_event_custom_function_handler
    };
    /* Create the boolean function */
    struct __os_event_custom_function_args custom_args = {
        .trigger = trigger,
        .args = args
    };
    /* Create an event out of this */
    __os_event_create(event, &descriptor, (os_ptr_t) &custom_args);
}
static struct os_mutex* os_event_get_mutex (struct os_event * event) [static, read]
Get a mutex out of a os_event structure.
Parameters:
event The mutex event
Returns:
The os_mutex structure
Precondition:
The event must have been generate from os_mutex_create_event
Definition at line 84 of file os_mutex.h.
{
    return (struct os_mutex *) event->args;
}
static struct os_semaphore* os_event_get_semaphore (struct os_event * event) [static, read]
Get a semaphore out of a os_event structure.
Parameters:
event The sempahore event
Returns:
The os_semaphore structure
Precondition:
The event must have been generate from os_semaphore_create_event
Definition at line 121 of file os_semaphore.h.
{
    return (struct os_semaphore *) event->args;
}
static char* os_get_version (void) [inline, static]
Get the current version of the running operating system.
Returns:
A string containing the version of the OS.
Definition at line 849 of file os_core.h.
{
    return OS_VERSION;
}
void os_interrupt_create (struct os_interrupt * interrupt, os_proc_ptr_t int_ptr, os_ptr_t args)
Setup a software interrupt.
Parameters:
interrupt The non-initialized structure to hold the context of the software interrupt
int_ptr A pointer on the interrupt handler (a interrupt handler is a normal function which follow the os_proc_ptr_t prototype)
args Arguments to pass to the inerrupt handler
Definition at line 32 of file os_interrupt.c.
References __HOOK_OS_DEBUG_TRACE_LOG, __os_interrupt_get_process(), __os_process_create(), os_interrupt::args, CONFIG_OS_INTERRUPT_DEFAULT_PRIORITY, os_interrupt::int_ptr, OS_DEBUG_TRACE_INTERRUPT_CREATE, os_interrupt_set_priority(), and OS_PROCESS_TYPE_INTERRUPT.
{
    __HOOK_OS_DEBUG_TRACE_LOG(OS_DEBUG_TRACE_INTERRUPT_CREATE, interrupt);
    /* Create the process */
    __os_process_create(__os_interrupt_get_process(interrupt), NULL,
            OS_PROCESS_TYPE_INTERRUPT);
    /* Fill the structure */
    interrupt->int_ptr = int_ptr;
    interrupt->args = args;
    /* Set default priority for the interrupt */
#if CONFIG_OS_USE_PRIORITY == true
    os_interrupt_set_priority(interrupt,
            CONFIG_OS_INTERRUPT_DEFAULT_PRIORITY);
#endif
}
static enum os_priority os_interrupt_get_priority (struct os_interrupt * interrupt) [inline, static]
Get the priority of a software interrupt.
Parameters:
interrupt The interrupt which priority is requested
Returns:
The interrupt priority
Precondition:
CONFIG_OS_USE_PRIORITY needs to be set first
Definition at line 169 of file os_interrupt.h.
References __HOOK_OS_DEBUG_TRACE_LOG, __os_interrupt_get_process(), __os_process_get_priority(), OS_DEBUG_TRACE_INTERRUPT_GET_PRIORITY, and os_process::priority.
{
    enum os_priority priority;
    priority = __os_process_get_priority(__os_interrupt_get_process(
            interrupt));
    __HOOK_OS_DEBUG_TRACE_LOG(OS_DEBUG_TRACE_INTERRUPT_GET_PRIORITY,
            priority);
    return (enum os_priority) priority;
}
static void os_interrupt_set_priority (struct os_interrupt * interrupt, enum os_priority priority) [inline, static]
Change the priority of a software interrupt.
Parameters:
interrupt The interrupt which needs some update
priority The new priority
Precondition:
CONFIG_OS_USE_PRIORITY needs to be set first
Definition at line 156 of file os_interrupt.h.
References __HOOK_OS_DEBUG_TRACE_LOG, __os_interrupt_get_process(), __os_process_set_priority(), and OS_DEBUG_TRACE_INTERRUPT_SET_PRIORITY.
Referenced by os_interrupt_create().
{
    __HOOK_OS_DEBUG_TRACE_LOG(OS_DEBUG_TRACE_INTERRUPT_SET_PRIORITY,
            priority);
    __os_process_set_priority(__os_interrupt_get_process(interrupt),
            priority);
}
static void os_interrupt_trigger (struct os_interrupt * interrupt) [inline, static]
Manually trigger a software interrupt.
Parameters:
interrupt The interrupt to trigger
Precondition:
The interrupt must be previously setup with os_interrupt_create
Definition at line 144 of file os_interrupt.h.
References __HOOK_OS_DEBUG_TRACE_LOG, __os_interrupt_get_process(), __os_process_enable(), and OS_DEBUG_TRACE_INTERRUPT_TRIGGER.
{
    __HOOK_OS_DEBUG_TRACE_LOG(OS_DEBUG_TRACE_INTERRUPT_TRIGGER, interrupt);
    __os_process_enable(__os_interrupt_get_process(interrupt));
}
void os_interrupt_trigger_on_event (struct os_interrupt * interrupt, struct os_event * event)
Trigger an interrupt on a specific event.
Parameters:
interrupt The interrupt to wakeup
event The event used to trigger the interrupt
Precondition:
CONFIG_OS_USE_EVENTS needs to be set
Definition at line 343 of file os_event.c.
References os_enter_critical(), os_is_critical(), and os_leave_critical().
{
    /* Save the critical region status */
    bool is_critical = os_is_critical();
    /* Enter in a critical region if not already in */
    if (!is_critical) {
        os_enter_critical();
    }
    //__os_event_start(event);
    //__os_event_register(event, __os_interrupt_get_process(interrupt));
    if (!is_critical) {
        os_leave_critical();
    }
}
static void os_mutex_create (struct os_mutex * mutex) [inline, static]
Creates a mutex.
Parameters:
mutex The un-initialized mutex structure
Definition at line 58 of file os_mutex.h.
References os_mutex::is_locked, and os_mutex::queue.
{
    mutex->is_locked = false;
    mutex->queue = NULL;
}
static void os_mutex_create_event (struct os_event * event, struct os_mutex * mutex) [inline, static]
Creates an event from a mutex. The mutex must have been previously created before using this function.
Parameters:
event The un-initialized event structure
mutex The mutex which will be linked to this event
Precondition:
CONFIG_OS_USE_EVENTS must be set
Definition at line 70 of file os_mutex.h.
References __os_event_create(), __os_event_mutex_is_triggered(), and os_event_descriptor::is_triggered.
{
    const struct os_event_descriptor mutex_event_descriptor = {
        .is_triggered = __os_event_mutex_is_triggered
    };
    __os_event_create(event, &mutex_event_descriptor, (os_ptr_t) mutex);
}
void os_mutex_lock (struct os_mutex * mutex)
Lock a mutex. If the mutex is already locked, wait until it gets unlocked.
Parameters:
mutex The mutex to be locked
Precondition:
The mutex must have previously been created
Definition at line 49 of file os_mutex.c.
References __os_process_disable_naked(), __os_process_get_current(), os_mutex::is_locked, os_enter_critical(), os_is_critical(), os_leave_critical(), os_queue_process_add(), os_switch_context, os_queue_process::proc, os_mutex::process, and os_mutex::queue.
{
    /* Save the critical region status */
    bool is_critical = os_is_critical();
    /* Enter in a critical region if not already in */
    if (!is_critical) {
        os_enter_critical();
    }
    /* If the mutex is not locked, lock it */
    if (!mutex->is_locked) {
        mutex->is_locked = true;
        mutex->process = __os_process_get_current();
    }
    /* If the mutex is already locked, suspend this task */
    else {
        /* Create a queue element, it will be stored on the stack. */
        struct os_queue_process queue_elt;
        /* Disable this process */
        __os_process_disable_naked(__os_process_get_current());
        /* Set the data associated to this queue entry */
        queue_elt.proc = __os_process_get_current();
        /* Add this process to the event list of the mutex */
        os_queue_process_add(&mutex->queue, &queue_elt);
        /* Manually switch the process context */
        os_switch_context(false);
    }
    /* Leave the critical region unless the CPU was previously in */
    if (!is_critical) {
        os_leave_critical();
    }
}
void os_mutex_unlock (struct os_mutex * mutex)
Un-lock a mutex.
Parameters:
mutex The mutex to be unlocked
Precondition:
The mutex must have previously been created
Definition at line 82 of file os_mutex.c.
References __os_process_enable_naked(), __os_process_get_current(), os_mutex::is_locked, os_enter_critical(), os_is_critical(), os_leave_critical(), os_queue_process_pop(), os_queue_process::proc, os_mutex::process, and os_mutex::queue.
{
    /* Only the process which locked the mutex can unlock it */
    if (__os_process_get_current() == mutex->process) {
        /* Save the critical region status */
        bool is_critical = os_is_critical();
        /* Enter in a critical region if not already in */
        if (!is_critical) {
            os_enter_critical();
        }
        /* Check if there is another process in the waiting list */
        if (mutex->queue) {
            struct os_process *proc;
            /* Pop the next process in the waiting list */
            proc = os_queue_process_pop(&mutex->queue)->proc;
            /* Lock the mutex for this process */
            mutex->process = proc;
            /* Enable this process */
            __os_process_enable_naked(proc);
        }
        /* Else unlock the mutex */
        else {
            mutex->is_locked = false;
        }
        /* Leave the critical region unless the CPU was previously in */
        if (!is_critical) {
            os_leave_critical();
        }
    }
}
static void os_semaphore_create (struct os_semaphore * sem, os_semaphore_counter_t counter, os_semaphore_counter_t initial_count) [inline, static]
Creates a counting semaphore.
Parameters:
sem The un-initialized sempahore structure
counter The maximum count value that can be reached
initial_count The count value assigned to the semaphore when it is created
Definition at line 83 of file os_semaphore.h.
References os_semaphore::counter, os_semaphore::max, and os_semaphore::queue.
Referenced by os_binary_semaphore_create().
{
    sem->counter = initial_count;
    sem->max = counter;
    sem->queue = NULL;
}
static void os_semaphore_create_event (struct os_event * event, struct os_semaphore * sem) [inline, static]
Creates an event from a semaphore. The sempahore must have been previously created before using this function.
Parameters:
event The un-initialized event structure
sem The semaphore which will be linked to this event
Precondition:
CONFIG_OS_USE_EVENTS must be set
Definition at line 106 of file os_semaphore.h.
References __os_event_create(), __os_event_sempahore_is_triggered(), and os_event_descriptor::is_triggered.
{
    /* Event descriptor for the semaphore */
    const struct os_event_descriptor __semaphore_event_descriptor = {
        .is_triggered = __os_event_sempahore_is_triggered
    };
    __os_event_create(event, &__semaphore_event_descriptor, (os_ptr_t) sem);
}
void os_semaphore_release (struct os_semaphore * sem)
Releases a semaphore.
Parameters:
sem The semaphore to release
Precondition:
The semaphore must have previously been created
Definition at line 88 of file os_semaphore.c.
References __os_process_enable_naked(), os_semaphore::counter, os_semaphore::max, os_enter_critical(), os_is_critical(), os_leave_critical(), os_queue_process_pop(), os_queue_process::proc, and os_semaphore::queue.
{
    /* Save the critical region status */
    bool is_critical = os_is_critical();
    /* Enter in a critical region if not already in */
    if (!is_critical) {
        os_enter_critical();
    }
    /* Check if there is another process in the waiting list */
    if (sem->queue) {
        struct os_process *proc;
        /* Pop the next process in the waiting list */
        proc = os_queue_process_pop(&sem->queue)->proc;
        /* Enable this process */
        __os_process_enable_naked(proc);
    }
    /* Else check if the sempahore counter is not above the limit */
    else if (sem->counter < sem->max) {
        /* Increase the semaphore counter, in other word, release the
         * semaphore previously taken.
         */
        sem->counter++;
    }
    /* Leave the critical region unless the CPU was previously in */
    if (!is_critical) {
        os_leave_critical();
    }
}
void os_semaphore_take (struct os_semaphore * sem)
Take a semaphore. If no semaphore is available, wait until it gets free.
Parameters:
sem The semaphore to take
Precondition:
The semaphore must have previously been created
Definition at line 55 of file os_semaphore.c.
References __os_process_disable_naked(), __os_process_get_current(), os_semaphore::counter, os_enter_critical(), os_is_critical(), os_leave_critical(), os_queue_process_add(), os_switch_context, os_queue_process::proc, and os_semaphore::queue.
{
    /* Save the critical region status */
    bool is_critical = os_is_critical();
    /* Enter in a critical region if not already in */
    if (!is_critical) {
        os_enter_critical();
    }
    /* If all the semaphores are not taken, take one */
    if (sem->counter > 0) {
        /* Decrease the semaphore counter */
        sem->counter--;
    }
    /* If the all the semaphores are taken, suspend this task */
    else {
        /* Queue element used to hold the process in the waiting list */
        struct os_queue_process queue_elt;
        /* Disable this process */
        __os_process_disable_naked(__os_process_get_current());
        /* Assign the data associated to this queue entry */
        queue_elt.proc = __os_process_get_current();
        /* Add this process to the event list of the sempahore */
        os_queue_process_add(&sem->queue, &queue_elt);
        /* Manually switch the process context */
        os_switch_context(false);
    }
    /* Leave the critical region unless the CPU was previously in */
    if (!is_critical) {
        os_leave_critical();
    }
}
static void os_start (uint32_t ref_hz) [inline, static]
Start the task scheduling process.
Parameters:
ref_hz The frequency which runs the peripheral to generate the ticks. Usually this frequency is equal to the CPU frequency.
Definition at line 819 of file os_core.h.
References __os_event_scheduler(), __os_process_get_current(), __os_process_is_event(), HOOK_OS_IDLE, os_setup_scheduler(), and os_yield().
{
    extern void os_setup_scheduler(uint32_t);
#if CONFIG_OS_SCHEDULER_TYPE != CONFIG_OS_SCHEDULER_COOPERATIVE
    /* Setup the scheduler */
    os_setup_scheduler(ref_hz);
#endif
    /* Launch the scheduler */
    os_yield();
    /* Idle loop. This loop will control the application process but also
     * the event process.
     * They both run inside an infinite loop. They cannot run at the same
     * time.
     */
    while (true) {
        /* If the event process is running, call the event scheduler */
        if (__os_process_is_event(__os_process_get_current())) {
            __os_event_scheduler();
        }
        /* Else it means the application process is running. In other
         * word, not other processes are actives or pending for events.
         */
        else {
            HOOK_OS_IDLE();
        }
    }
}
os_cy_t os_statistics_get_task_switch_time (void)
Get the average time of the context task switching in number of cycles.
Returns:
the number of cycles of the average context switching time
Precondition:
CONFIG_OS_STATISTICS_MONITOR_TASK_SWITCH must be set
Definition at line 110 of file os_statistics.c.
References task_switch_max_cy, and task_switch_min_cy.
{
    /* The switch time is the average between the maximum and minimum */
    return (task_switch_max_cy + task_switch_min_cy) / 2;
}
os_cy_t os_statistics_get_task_switch_time_jitter (void)
Get the jitter of the context task switching in number of cycles.
Returns:
the number of cycles of the switching time jitter
Precondition:
CONFIG_OS_STATISTICS_MONITOR_TASK_SWITCH must be set
Definition at line 102 of file os_statistics.c.
References task_switch_max_cy, and task_switch_min_cy.
{
    /* Switch time jitter is the difference between the maximum and
     * the minimum / 2
     */
    return (task_switch_max_cy - task_switch_min_cy) / 2;
}
uint8_t os_statistics_task_cpu_allocation (struct os_task * task)
Theoretical estimation of the CPU load of a task. It is based on the number of current active tasks in the list and their priority. The ratio of the CPU ressources is calculated as follow:
 ratio = (100 / (priority level)) / SUM(100 / (each priority level))
Parameters:
task The task to evaluate
Returns:
The allocation time in percent of the CPU assigned to this task
Definition at line 118 of file os_statistics.c.
References __os_process_get_priority(), __os_process_is_task(), __os_task_get_process(), os_process::next, and os_process::priority.
{
    struct os_process *proc = __os_task_get_process(task);
    struct os_process *last_proc = proc->next;
#if CONFIG_OS_USE_PRIORITY == true
    uint8_t priority = 100 / __os_process_get_priority(proc);
#else
    uint8_t priority = 100;
#endif
    uint16_t sum = priority;
    /* Loop into the task list */
    while (last_proc != proc) {
        if (__os_process_is_task(last_proc)) {
#if CONFIG_OS_USE_PRIORITY == true
            sum += 100 / __os_process_get_priority(last_proc);
#else
            sum += 100;
#endif
        }
        last_proc = last_proc->next;
    }
    return (uint8_t) (((uint16_t) priority * 100) / sum);
}
bool os_task_create (struct os_task * task, os_proc_ptr_t task_ptr, os_ptr_t args, int stack_size, enum os_task_option options)
Create a new task. By default, the new task will be automatically added to the active task list unless specified.
Parameters:
task A pointer on an empty structure which will contain the context of the current task.
task_ptr Entry point of the task to be run.
args Arguments to pass to the task
stack_size The size of the stack in byte
options Specific options for the task (see os_task_option)
Returns:
true if the task has been correctly registered, false otherwise.
Definition at line 42 of file os_task.c.
References __HOOK_OS_DEBUG_TASK_ADD, __HOOK_OS_DEBUG_TRACE_LOG, __os_process_create(), __os_task_get_process(), CONFIG_OS_TASK_DEFAULT_PRIORITY, os_task::core, os_task::options, OS_DEBUG_TRACE_TASK_CREATE, os_malloc(), os_process_context_load(), OS_PROCESS_TYPE_TASK, OS_TASK_DISABLE, os_task_enable(), os_task_set_priority(), OS_TASK_USE_CUSTOM_STACK, and os_task::stack.
{
    __HOOK_OS_DEBUG_TRACE_LOG(OS_DEBUG_TRACE_TASK_CREATE, task);
#if CONFIG_OS_USE_MALLOC == true
    if (!(options & OS_TASK_USE_CUSTOM_STACK)) {
        /* Allocate memory for the stack size */
        if (!(task->stack = os_malloc(stack_size))) {
            return false;
        }
    }
#endif
    /* Create the process */
    __os_process_create(__os_task_get_process(task),
            &task->stack[stack_size], OS_PROCESS_TYPE_TASK);
#if CONFIG_OS_DEBUG == true
    __HOOK_OS_DEBUG_TASK_ADD();
#endif
    /* Save the options */
    task->options = options;
    /* Set the priority of the task */
#if CONFIG_OS_USE_PRIORITY == true
    os_task_set_priority(task, CONFIG_OS_TASK_DEFAULT_PRIORITY);
#endif
    /* Load context */
    if (!os_process_context_load(&task->core, task_ptr, args)) {
        return false;
    }
    /* Enable the task */
    if (!(options & OS_TASK_DISABLE)) {
        os_task_enable(task);
    }
    return true;
}
void os_task_delay (os_tick_t tick_nb)
Block the execution of a task until a number of ticks have passed.CONFIG_OS_TICK_HZ can be used to estimate a time delay.
Parameters:
tick_nb The number of ticks to wait for
Precondition:
CONFIG_OS_USE_TICK_COUNTER needs to be set first.
Warning:
This functon needs the preemptive scheduler to run. Therefore, it cannot be used inside an interrupt or any other piece of code where the tick interrupt is disabled.
Definition at line 18 of file os_task.c.
References __HOOK_OS_DEBUG_TRACE_LOG, OS_DEBUG_TRACE_TASK_DELAY_START, OS_DEBUG_TRACE_TASK_DELAY_STOP, os_tick_counter, and os_yield().
{
    extern volatile os_tick_t os_tick_counter;
    os_tick_t start_tick, last_tick;
    __HOOK_OS_DEBUG_TRACE_LOG(OS_DEBUG_TRACE_TASK_DELAY_START, tick_nb);
    start_tick = os_tick_counter;
    last_tick = os_tick_counter + tick_nb;
    /* Check if the counter has been wrapped */
    if (last_tick < start_tick) {
        /* Monitor the 1rst half */
        while (os_tick_counter > start_tick) {
            os_yield();
        }
    }
    while (os_tick_counter < last_tick) {
        os_yield();
    }
    __HOOK_OS_DEBUG_TRACE_LOG(OS_DEBUG_TRACE_TASK_DELAY_STOP, tick_nb);
}
static void os_task_delete (struct os_task * task) [inline, static]
Delete a task.
Parameters:
task The task to be deleted
Definition at line 175 of file os_task.h.
References __HOOK_OS_DEBUG_TRACE_LOG, __os_process_disable(), __os_task_get_process(), os_task::options, OS_DEBUG_TRACE_TASK_DELETE, os_free(), OS_TASK_USE_CUSTOM_STACK, and os_task::stack.
{
    __HOOK_OS_DEBUG_TRACE_LOG(OS_DEBUG_TRACE_TASK_DELETE, task);
    __os_process_disable(__os_task_get_process(task));
    // Free the task stack if needed
    if (!(task->options & OS_TASK_USE_CUSTOM_STACK)) {
        os_free(task->stack);
    }
}
static void os_task_disable (struct os_task * task) [inline, static]
Disable the execution of a task.
Parameters:
task The task to be disabled
Definition at line 197 of file os_task.h.
References __HOOK_OS_DEBUG_TRACE_LOG, __os_process_disable(), __os_task_get_process(), and OS_DEBUG_TRACE_TASK_DISABLE.
{
    __HOOK_OS_DEBUG_TRACE_LOG(OS_DEBUG_TRACE_TASK_DISABLE, task);
    __os_process_disable(__os_task_get_process(task));
}
static void os_task_enable (struct os_task * task) [inline, static]
Enable the execution a task.
Parameters:
task The task to be enabled
Definition at line 188 of file os_task.h.
References __HOOK_OS_DEBUG_TRACE_LOG, __os_process_enable(), __os_task_get_process(), and OS_DEBUG_TRACE_TASK_ENABLE.
Referenced by os_task_create().
{
    __HOOK_OS_DEBUG_TRACE_LOG(OS_DEBUG_TRACE_TASK_ENABLE, task);
    __os_process_enable(__os_task_get_process(task));
}
static struct os_task* os_task_get_current (void) [static, read]
Get the current running task.
Returns:
the current task. NULL if none is running.
Definition at line 215 of file os_task.h.
References __os_process_get_current(), __os_process_is_task(), and __os_task_from_process().
{
    if (__os_process_is_task(__os_process_get_current())) {
        return __os_task_from_process(__os_process_get_current());
    }
    return NULL;
}
static enum os_priority os_task_get_priority (struct os_task * task) [inline, static]
Get the priority of a task.
Parameters:
task The task
Returns:
The priority of the task
Definition at line 163 of file os_task.h.
References __HOOK_OS_DEBUG_TRACE_LOG, __os_process_get_priority(), __os_task_get_process(), OS_DEBUG_TRACE_TASK_GET_PRIORITY, and os_process::priority.
{
    enum os_priority priority;
    priority = __os_process_get_priority(__os_task_get_process(task));
    __HOOK_OS_DEBUG_TRACE_LOG(OS_DEBUG_TRACE_TASK_GET_PRIORITY, priority);
    return (enum os_priority) priority;
}
static bool os_task_is_enabled (struct os_task * task) [inline, static]
Check wether a task is enabled or not.
Parameters:
task The task to be checked
Returns:
true if enabled, false otherwise
Definition at line 207 of file os_task.h.
References __os_process_is_enabled(), and __os_task_get_process().
{
    return __os_process_is_enabled(__os_task_get_process(task));
}
static void os_task_set_priority (struct os_task * task, enum os_priority priority) [inline, static]
Set a priority to a task.
Parameters:
task The task
priority The priority to set
Definition at line 153 of file os_task.h.
References __HOOK_OS_DEBUG_TRACE_LOG, __os_process_set_priority(), __os_task_get_process(), and OS_DEBUG_TRACE_TASK_SET_PRIORITY.
Referenced by os_task_create().
{
    __HOOK_OS_DEBUG_TRACE_LOG(OS_DEBUG_TRACE_TASK_SET_PRIORITY, priority);
    __os_process_set_priority(__os_task_get_process(task), priority);
}
void os_yield (void)
Call the scheduler to switch to a new task that is ready to run. This function is useful for cooperative task swiching.
Definition at line 255 of file os_core.c.
References __HOOK_OS_DEBUG_TRACE_LOG, OS_DEBUG_TRACE_YIELD, os_enter_critical(), os_is_critical(), os_leave_critical(), and os_switch_context.
Referenced by os_start(), and os_task_delay().
{
    /* Check if the current process is running inside a critical region. */
    bool is_critical = os_is_critical();
    /* The following code is critical, so enter in the critial region if
     * not already done.
     */
    if (!is_critical) {
        os_enter_critical();
    }
    /* Log the yield event to be visible in the trace. This is done only if
     * the trace is activated.
     */
    __HOOK_OS_DEBUG_TRACE_LOG(OS_DEBUG_TRACE_YIELD,
            __os_current_process);
    /* Manually switch context to execute another process. */
    os_switch_context(false);
    /* Leave the critical region if the process was not previously in. */
    if (!is_critical) {
        os_leave_critical();
    }
}