eeOS (Embedded Event-driven Operating System): Internal API
Internal API
[eeOS]
Internal API. These functions should not be used by the user.
Functions
void __os_debug_trace_log (enum os_debug_trace_event event, os_ptr_t data)
This function is called to log a trace entry.
void __os_event_create (struct os_event *event, const struct os_event_descriptor *descriptor, os_ptr_t args)
Create a new event.
enum os_event_status __os_event_custom_function_handler (struct os_process *proc, os_ptr_t args)
Internal handler for the boolean function.
static struct os_queue_event * __os_event_get_queue (struct os_event *event)
Get the os_queue_event pointer associated with an event.
static struct os_queue_event ** __os_event_get_queue_ptr (struct os_event *event)
Get the pointer on the variable that hold the os_queue_event structure associated with an event.
static bool __os_event_is_empty (struct os_event *event)
This function test a event structure and notifies if it has any remaining process in its queue.
static bool __os_event_is_enabled (struct os_event *event)
Checks if an event is enabled, in other word, test if it is in the active event list.
enum os_event_status __os_event_mutex_is_triggered (struct os_process *proc, os_ptr_t args)
Declaration of the event trigger function for a mutex.
void __os_event_register (struct os_event *event, struct os_queue_event *queue_elt, struct os_process *proc, struct os_event **event_triggered)
Associate a process with an event and enable the event.
void __os_event_scheduler (void)
Event scheduler.
static struct os_interrupt * __os_interrupt_from_process (struct os_process *proc)
Get the interrupt associated with a process.
static struct os_process * __os_interrupt_get_process (struct os_interrupt *interrupt)
Get the interrupt process.
void __os_interrupt_handler (os_ptr_t args)
Software interrupt handler.
static void __os_process_application_disable (void)
Disable the application process.
static void __os_process_application_enable (void)
Enable the application process.
static void __os_process_create (struct os_process *proc, os_ptr_t sp, enum os_process_type type)
Initializes a process.
void __os_process_disable (struct os_process *proc)
Disable the execution of a process.
void __os_process_disable_naked (struct os_process *proc)
void __os_process_enable (struct os_process *proc)
Enable the execution a process.
void __os_process_enable_naked (struct os_process *proc)
static void __os_process_event_disable (void)
Enable the event process If the event process is enabled, the application process will be disabled as they share the same process.
static void __os_process_event_enable (void)
Enable the event process If the event process is enabled, the application process will be disabled as they share the same process.
static struct os_process * __os_process_get_application (void)
Get the application process.
static struct os_process * __os_process_get_current (void)
Get the current process.
static enum os_priority __os_process_get_priority (struct os_process *proc)
Get the priority of a process.
static bool __os_process_is_application (struct os_process *proc)
Check if a process is the application process.
static bool __os_process_is_enabled (struct os_process *proc)
Check wether a process is active or not.
static bool __os_process_is_event (struct os_process *proc)
Check if a process is the event scheduler.
static bool __os_process_is_interrupt (struct os_process *proc)
Check if a process is a software interrupt.
static bool __os_process_is_pending (struct os_process *proc)
Check wether a process is enabled or not.
static bool __os_process_is_task (struct os_process *proc)
Check if a process is a task.
static void __os_process_set_priority (struct os_process *proc, enum os_priority priority)
Change the priority of a process.
struct os_event * __os_process_sleep (struct os_process *proc, struct os_queue_event *queue_elt, int nb_events,...)
Generic function to send a processus to sleep. The process can be waken up by one or more events passed in parameter.
struct os_process * __os_scheduler (void)
This function will define the rules to change the task.
static struct os_process * __os_switch_context_hook (void)
This function must be called inside theos_switch_context function in order to switch process context.
static struct os_task * __os_task_from_process (struct os_process *proc)
Get the task associated with a process.
static struct os_process * __os_task_get_process (struct os_task *task)
Get the task process.
Detailed Description
Internal API. These functions should not be used by the user.
Function Documentation
void __os_debug_trace_log (enum os_debug_trace_event event, os_ptr_t data)
This function is called to log a trace entry.
Parameters:
event The event identifier to be logged
data The data associated with the trace
Precondition:
os_debug_start_trace must have been called first.
Definition at line 30 of file os_debug.c.
References os_trace::data, os_trace::event, os_debug_trace_flag, os_enter_critical(), os_is_critical(), os_leave_critical(), os_read_cycle_counter(), and os_trace::time.
{
    /* The following code is only activated if the trace is enabled */
    if (os_debug_trace_flag) {
        /* Save the critical region status */
        bool is_critical = os_is_critical();
        /* The trace log is a shared variable so this snippet of code
         * must run as in a critical region.
         */
        if (!is_critical) {
            os_enter_critical();
        }
        /* Fill in the trace information */
        os_debug_trace_ptr->time = os_read_cycle_counter();
        os_debug_trace_ptr->event = event;
        os_debug_trace_ptr->data = data;
        /* Increase the trace pointer. The trace is saved in a circular
         * buffer, handle the wrapping if any.
         */
        os_debug_trace_ptr++;
        /* If the new trace pointer is equal to the last trace address,
         * we need to wrap.
         */
        if (os_debug_trace_ptr == os_debug_trace_end) {
            os_debug_trace_ptr = os_debug_trace_start;
        }
        /* Leave the critical region if the rest of the code does not
         * requires to run inside a critical code region.
         */
        if (!is_critical) {
            os_leave_critical();
        }
    }
}
void __os_event_create (struct os_event * event, const struct os_event_descriptor * descriptor, os_ptr_t args)
Create a new event.
Parameters:
event A non-initialized event structure to hold the context of this event
descriptor The event description structure which defines the type of event to be used.
args Argument which will be passed to the event descriptor functions.
Definition at line 25 of file os_event.c.
References os_event_descriptor::is_triggered, os_event_descriptor::sort, and os_event_descriptor::start.
Referenced by os_event_create_from_function(), os_mutex_create_event(), and os_semaphore_create_event().
{
    /* Fill the event structure */
    event->desc.sort = descriptor->sort;
    event->desc.start = descriptor->start;
    event->desc.is_triggered = descriptor->is_triggered;
    /* Associate arguments to the event */
    event->args = args;
    /* Mark this event as disabled */
    event->queue.next = NULL;
    event->queue.prev = NULL;
}
enum os_event_status __os_event_custom_function_handler (struct os_process * proc, os_ptr_t args)
Internal handler for the boolean function.
Parameters:
proc Process associated to the event
args Extra arguments to pass to this function. Arguments are a pointer of type __os_event_custom_function_args
Returns:
The status of the trigger function
Definition at line 259 of file os_event.c.
References __os_event_custom_function_args::args, and __os_event_custom_function_args::trigger.
Referenced by os_event_create_from_function().
{
    /* The pointer is cast to a structure of type
     * __os_event_custom_function_args
     */
    struct __os_event_custom_function_args *custom_args =
            (struct __os_event_custom_function_args *) args;
    /* Call the trigger function to test if the event has been triggered */
    if (custom_args->trigger(custom_args->args)) {
        /* If yes, continue looking */
        return OS_EVENT_OK_CONTINUE;
    }
    /* If not, stop */
    return OS_EVENT_NONE;
}
static struct os_queue_event* __os_event_get_queue (struct os_event * event) [static, read]
Get the os_queue_event pointer associated with an event.
Parameters:
event The event from which we want to get the structure
Returns:
The os_queue_event pointer, or NULL if no processes are associated with this event
Definition at line 229 of file os_event.h.
Referenced by __os_event_scheduler().
{
    return (struct os_queue_event *) event->queue.next;
}
static struct os_queue_event** __os_event_get_queue_ptr (struct os_event * event) [static, read]
Get the pointer on the variable that hold the os_queue_event structure associated with an event.
Parameters:
event The event we need to get data from
Returns:
A pointer on the variable which holds the os_queue_event structure associated with this event
Definition at line 240 of file os_event.h.
Referenced by __os_event_register(), and __os_event_scheduler().
{
    return (struct os_queue_event **) &event->queue.next;
}
static bool __os_event_is_empty (struct os_event * event) [inline, static]
This function test a event structure and notifies if it has any remaining process in its queue.
Parameters:
event The event to be tested
Returns:
true if there are no process in the queue, false otherwise.
Definition at line 184 of file os_event.h.
Referenced by __os_event_scheduler().
{
    return (bool) !(event->queue.next);
}
static bool __os_event_is_enabled (struct os_event * event) [inline, static]
Checks if an event is enabled, in other word, test if it is in the active event list.
Parameters:
event The event to be checked
Returns:
true if the event is enabled, false otherwise.
Definition at line 194 of file os_event.h.
Referenced by __os_event_register().
{
    return (bool) (event->queue.next);
}
enum os_event_status __os_event_mutex_is_triggered (struct os_process * proc, os_ptr_t args)
Declaration of the event trigger function for a mutex.
Parameters:
proc The process associated with this event
args Extra arguments
Returns:
Returned if the event triggered or not
Definition at line 17 of file os_mutex.c.
References os_mutex::is_locked, os_enter_critical(), os_is_critical(), os_leave_critical(), os_mutex::process, and os_process::status.
Referenced by os_mutex_create_event().
{
    /* Output status of the event */
    enum os_event_status status = OS_EVENT_NONE;
    /* Cast the arguments to a \ref os_mutex structure */
    struct os_mutex *mutex = (struct os_mutex *) args;
    /* Save the critical region status */
    bool is_critical = os_is_critical();
    /* Enter in a critical region if not already in */
    if (!is_critical) {
        os_enter_critical();
    }
    /* Test if the mutex is not locked */
    if (!mutex->is_locked) {
        /* lock it */
        mutex->is_locked = true;
        /* Associate a process with this mutex */
        mutex->process = proc;
        /* Set the status of this event to triggered */
        status = OS_EVENT_OK_STOP;
    }
    /* Leave the critical section */
    if (!is_critical) {
        os_leave_critical();
    }
    /* Return the event status */
    return status;
}
void __os_event_register (struct os_event * event, struct os_queue_event * queue_elt, struct os_process * proc, struct os_event ** event_triggered)
Associate a process with an event and enable the event.
Parameters:
event The event to receive the process
queue_elt A unitialized queue structure used to hold the process in the queue.
proc The process to add
event_triggered A pointer to update which will reflect the event that has been triggered
void __os_event_scheduler (void)
Event scheduler.
Definition at line 141 of file os_event.c.
References __os_event_get_queue(), __os_event_get_queue_ptr(), __os_event_is_empty(), __os_event_pop(), __os_process_enable_naked(), __os_process_event_disable(), __os_process_is_pending(), os_event::args, os_enter_critical(), OS_EVENT_NONE, OS_EVENT_OK_CONTINUE, os_leave_critical(), and os_switch_context.
Referenced by os_start().
{
    /* To hold the current event to process */
    struct os_event *event;
    /* Status of the current event */
    enum os_event_status status = OS_EVENT_NONE;
    /* All the following cannot be interrupted since manupulating the
     * active event list is critical.
     */
    os_enter_critical();
    /* Start with the first event to process */
    event = __os_current_event;
    /* If no events, disable the event process */
    if (!event) {
        /* Disable the event process */
        __os_process_event_disable();
    }
    /* Loop inside the active event list */
    while (event) {
        /* Loop until the status of the current event is "stop" */
        do {
            /* If the process queue of the current event is not
             * empty
             */
            if (!__os_event_is_empty(event)) {
                struct os_queue_event *queue_elt;
                /* Get the first process associated with the
                 * current event
                 */
                queue_elt = os_queue_event_head(
                        __os_event_get_queue(event));
                /* Make sure the process is in pending state */
                if (__os_process_is_pending(queue_elt->proc)) {
                    /* Check if the event has been triggered
                     */
                    status = event->desc.is_triggered(
                            queue_elt->proc,
                            event->args);
                    /* If the event has triggered */
                    if (status != OS_EVENT_NONE) {
                        struct os_queue_event *current_elt;
                        /* Update the event feedback
                         * variable
                         */
                        *queue_elt->event_triggered =
                                event;
                        /* Remove the process from the
                         * event list
                         */
                        os_queue_event_pop(
                                __os_event_get_queue_ptr(event));
                        /* Activate the process */
                        __os_process_enable_naked(queue_elt->proc);
                        /* Garbage collect, remove the other
                         * queued entries associated to this process
                         */
                        current_elt = queue_elt->relation;
                        /* Loop through the other queued entries
                         * assicoated with this process and remove
                         * them
                         */
                        while (current_elt != queue_elt) {
                            os_queue_event_remove(current_elt);
                            current_elt = current_elt->relation;
                        }
                    }
                }
                /* If a process is not pending, pop this process out
                 * of the event list. This should never happen.
                 */
                else {
                    // while (true);
                    /* Remove the not pending process from
                     * the list.
                     */
                    os_queue_event_pop(__os_event_get_queue_ptr(event));
                    /* Continue processing the next process
                     * in the list.
                     */
                    status = OS_EVENT_OK_CONTINUE;
                }
            }
        /* Loop until the status is set to "continue" */
        } while (status == OS_EVENT_OK_CONTINUE);
        /* Get the next active event */
        event = event->next;
    }
    /* Start with the first event to process */
    event = __os_current_event;
    /* Garbage collector, test if there are empty events, if so remove them
     */
    while (event) {
        /* If the process queue of the current event is empty,
         * remove this event from the active event list.
         */
        if (__os_event_is_empty(event)) {
            /* Change the status to exit the main loop */
            status = OS_EVENT_NONE;
            /* Remove this event from the active event list
             */
            __os_event_pop(event);
        }
        event = event->next;
    }
    /* Manually call the scheduler to schedule the next process */
    os_switch_context(false);
    /* Leave the critical area */
    os_leave_critical();
}
static struct os_interrupt* __os_interrupt_from_process (struct os_process * proc) [static, read]
Get the interrupt associated with a process.
Parameters:
proc the process
Returns:
The interrupt pointer
Definition at line 93 of file os_interrupt.h.
References os_interrupt::core, and OS_CONTAINER_OF.
{
    return OS_CONTAINER_OF(proc, struct os_interrupt, core);
}
static struct os_process* __os_interrupt_get_process (struct os_interrupt * interrupt) [static, read]
Get the interrupt process.
Parameters:
interrupt The interrupt
Returns:
The process of the interrupt
Definition at line 103 of file os_interrupt.h.
References os_interrupt::core.
Referenced by __os_interrupt_handler(), os_interrupt_create(), os_interrupt_get_priority(), os_interrupt_set_priority(), and os_interrupt_trigger().
{
    return &interrupt->core;
}
void __os_interrupt_handler (os_ptr_t args)
Software interrupt handler.
Parameters:
args A pointer on a os_interrupt structure
Definition at line 17 of file os_interrupt.c.
References __os_interrupt_get_process(), __os_process_disable_naked(), os_interrupt::args, os_interrupt::int_ptr, os_enter_critical(), and os_switch_context.
{
    struct os_interrupt *interrupt = (struct os_interrupt *) args;
    /* Disable scheduler interrupts */
    os_enter_critical();
    /* Remove the interrupt from the chain list to prevent another execution
     */
    __os_process_disable_naked(__os_interrupt_get_process(interrupt));
    /* Execute the interrupt handler */
    interrupt->int_ptr(interrupt->args);
    /* Manually call the scheduler */
    os_switch_context(true);
}
static void __os_process_application_disable (void) [inline, static]
Disable the application process.
Definition at line 727 of file os_core.h.
References __os_process_disable(), and __os_process_is_application().
{
    extern struct os_process os_app;
    if (__os_process_is_application(&os_app)) {
        __os_process_disable(&os_app);
    }
}
static void __os_process_application_enable (void) [inline, static]
Enable the application process.
Definition at line 719 of file os_core.h.
References __os_process_enable(), and os_process::type.
Referenced by __os_process_event_enable().
{
    extern struct os_process os_app;
    __os_process_enable(&os_app);
    os_app.type = OS_PROCESS_TYPE_APPLICATION;
}
static void __os_process_create (struct os_process * proc, os_ptr_t sp, enum os_process_type type) [inline, static]
Initializes a process.
Parameters:
proc The process to be initialized
sp The stack pointer
type The type of process
Definition at line 694 of file os_core.h.
References os_process::cycle_counter, OS_ALIGN_BACK, os_process::sp, os_process::status, and os_process::type.
Referenced by os_interrupt_create(), and os_task_create().
{
    /* Align the stack pointer within the stack. */
    proc->sp = OS_ALIGN_BACK(sp);
    /* Set the type of the process (task, interrupt, ...) */
    proc->type = type;
    /* Set the status of the process. Initially it is set to idle. */
    proc->status = OS_PROCESS_IDLE;
#if CONFIG_OS_STATISTICS_MONITOR_TASK_SWITCH == true
    /* Update the activity cycle counter of this task. */
    proc->cycle_counter = 0;
#endif
}
void __os_process_disable (struct os_process * proc)
Disable the execution of a process.
Parameters:
proc The process to be disabled
Definition at line 228 of file os_core.c.
References __os_process_disable_naked(), __os_process_is_enabled(), os_enter_critical(), os_is_critical(), os_leave_critical(), and os_switch_context.
Referenced by __os_process_application_disable(), __os_process_event_disable(), os_task_delete(), and os_task_disable().
{
    /* Check if the current process is running inside a critical region. */
    bool is_critical = os_is_critical();
    /* The following code is critical, so enter in the critial region if
     * not already done.
     */
    if (!is_critical) {
        os_enter_critical();
    }
    /* Make sure the task is not already disabled */
    if (__os_process_is_enabled(proc)) {
        /* If not, disable this process */
        __os_process_disable_naked(proc);
    }
    /* Manually switch context to stop the execution of this process if it
     * is the current process.
     */
    if (proc == __os_current_process) {
        os_switch_context(false);
    }
    /* Leave the critical region if the process was not previously in. */
    if (!is_critical) {
        os_leave_critical();
    }
}
void __os_process_disable_naked (struct os_process * proc)
Disable the execution of a process.
Parameters:
proc The process to be disabled
Warning:
This function does not check if the task is already disabled and should be used inside a critical area. It also does not stop after the execution of this function.
Definition at line 185 of file os_core.c.
References os_process::next, os_process::status, and os_process::type.
Referenced by __os_interrupt_handler(), __os_process_disable(), __os_process_sleep(), os_mutex_lock(), and os_semaphore_take().
{
    struct os_process *last_proc = proc;
    /* Look for the process before proc. A research is necessary at this
     * point since we are using a uni-directional circular chain list to
     * keep track of the active processes.
     */
    while (last_proc->next != proc) {
        /* If the process after last_proc is not equal to the proc, it
         * means we did not do a loop yet. So continue.
         */
        last_proc = last_proc->next;
    }
    /* If last_proc == proc, it means that there is only 1 process in the
     * active process list. In that case, we need to replace the current
     * process with the application process.
     */
    if (last_proc == proc) {
        /* Loop the application process over itslef. */
        os_app.next = &os_app;
        /* Set this process as the application process. This is
         * necessary since this process is shared with the event
         * process.
         */
        os_app.type = OS_PROCESS_TYPE_APPLICATION;
        /* Change the application process to active */
        os_app.status = OS_PROCESS_ACTIVE;
        /* Insert the application process in the active process list
         * after the current process.
         */
        proc->next = &os_app;
    }
    else {
        /* There is at least 2 processes in the active process list.
         * Remove the process (proc).
         */
        last_proc->next = proc->next;
    }
    /* Change the status of this process (proc) to idle. */
    proc->status = OS_PROCESS_IDLE;
}
void __os_process_enable (struct os_process * proc)
Enable the execution a process.
Parameters:
proc The process to be enabled
Definition at line 164 of file os_core.c.
References __os_process_enable_naked(), __os_process_is_enabled(), os_enter_critical(), os_is_critical(), and os_leave_critical().
Referenced by __os_process_application_enable(), os_interrupt_trigger(), and os_task_enable().
{
    /* Check if the current process is running inside a critical region. */
    bool is_critical = os_is_critical();
    /* The following code is critical, so enter in the critial region if
     * not already done.
     */
    if (!is_critical) {
        os_enter_critical();
    }
    /* Make sure the task is not already enabled */
    if (!__os_process_is_enabled(proc)) {
        /* If not, enable this process */
        __os_process_enable_naked(proc);
    }
    /* Leave the critical region if the process was not previously in. */
    if (!is_critical) {
        os_leave_critical();
    }
}
void __os_process_enable_naked (struct os_process * proc)
Enable the execution a process.
Parameters:
proc The process to be enabled
This function will push the task at the end of the chain list
Warning:
This function does not check if the task is already added to the list and should be used inside a critical area.
Definition at line 118 of file os_core.c.
References __os_process_is_application(), os_process::next, and os_process::status.
Referenced by __os_event_scheduler(), __os_process_enable(), os_mutex_unlock(), and os_semaphore_release().
{
    struct os_process *last_proc = proc;
    /* Get the next process after the current one. This because the current
     * process can never be removed from the active process list because it
     * needs to store its context on its stack before beiing disbaled.
     */
    last_proc = __os_current_process->next;
#if CONFIG_OS_PROCESS_ENABLE_FIFO == true
    /* Look for the last process in the circular chain list of active
     * processes.
     */
    while (last_proc->next != __os_current_process->next) {
        /* If this process is _not_ equal to the first process we
         * checked, it means we did not do a loop yet. So continue.
         */
        last_proc = last_proc->next;
    }
#endif
    /* If the application process is running, remove it from the active
     * process list. The application process will run only if no process
     * are running.
     */
    if (__os_process_is_application(last_proc)) {
        /* This process (proc) is then the only process that will be
         * running since we want to remove the application process. So
         * loop this process with himself (circular chain list).
         */
        proc->next = proc;
        /* Change the status of the application process to idle. */
        os_app.status = OS_PROCESS_IDLE;
    }
    else {
        /* The application process is _not_ running, this is a normal
         * case. Insert the process (proc) inside the circular chain
         * list.
         */
        proc->next = last_proc->next;
    }
    /* Finalize the insertion of this process to the circular chain list. */
    last_proc->next = proc;
    /* Change the status of the process (proc) to active */
    proc->status = OS_PROCESS_ACTIVE;
}
static void __os_process_event_disable (void) [inline, static]
Enable the event process If the event process is enabled, the application process will be disabled as they share the same process.
Definition at line 748 of file os_core.h.
References __os_process_disable(), and __os_process_is_event().
Referenced by __os_event_scheduler().
{
    extern struct os_process os_app;
    if (__os_process_is_event(&os_app)) {
        __os_process_disable(&os_app);
    }
}
static void __os_process_event_enable (void) [inline, static]
Enable the event process If the event process is enabled, the application process will be disabled as they share the same process.
Definition at line 738 of file os_core.h.
References __os_process_application_enable(), and os_process::type.
Referenced by __os_event_register().
{
    extern struct os_process os_app;
    __os_process_application_enable();
    os_app.type = OS_PROCESS_TYPE_EVENT;
}
static struct os_process* __os_process_get_application (void) [static, read]
Get the application process.
Returns:
the application process
Definition at line 712 of file os_core.h.
{
    extern struct os_process os_app;
    return &os_app;
}
static struct os_process* __os_process_get_current (void) [static, read]
Get the current process.
Returns:
A pointer on the current procress
Definition at line 561 of file os_core.h.
References __os_current_process.
Referenced by __os_process_sleep(), os_mutex_lock(), os_mutex_unlock(), os_semaphore_take(), os_start(), os_task_get_current(), and update_task_cycle_counter_start().
{
    extern struct os_process *__os_current_process;
    return __os_current_process;
}
static enum os_priority __os_process_get_priority (struct os_process * proc) [inline, static]
Get the priority of a process.
Parameters:
proc The process which priority is requested
Returns:
The process priority
Precondition:
CONFIG_OS_USE_PRIORITY needs to be set first
Definition at line 659 of file os_core.h.
References os_process::priority_counter.
Referenced by os_interrupt_get_priority(), os_statistics_task_cpu_allocation(), and os_task_get_priority().
{
    return (enum os_priority) proc->priority_counter;
}
static bool __os_process_is_application (struct os_process * proc) [inline, static]
Check if a process is the application process.
Parameters:
proc The process to be checked
Returns:
true if this is the application process, false otherwise
Definition at line 571 of file os_core.h.
References OS_PROCESS_TYPE_APPLICATION, and os_process::type.
Referenced by __os_process_application_disable(), and __os_process_enable_naked().
{
    return (proc->type == OS_PROCESS_TYPE_APPLICATION);
}
static bool __os_process_is_enabled (struct os_process * proc) [inline, static]
Check wether a process is active or not.
Parameters:
proc The process to be checked
Returns:
true if enabled, false otherwise
Definition at line 627 of file os_core.h.
References OS_PROCESS_ACTIVE, and os_process::status.
Referenced by __os_process_disable(), __os_process_enable(), __os_process_sleep(), and os_task_is_enabled().
{
    return (proc->status == OS_PROCESS_ACTIVE);
}
static bool __os_process_is_event (struct os_process * proc) [inline, static]
Check if a process is the event scheduler.
Parameters:
proc The process to be checked
Returns:
true if this is the event scheduler, false otherwise
Definition at line 602 of file os_core.h.
References OS_PROCESS_TYPE_EVENT, and os_process::type.
Referenced by __os_process_event_disable(), and os_start().
{
#if CONFIG_OS_USE_EVENTS == true
    return (proc->type == OS_PROCESS_TYPE_EVENT);
#else
    return false;
#endif
}
static bool __os_process_is_interrupt (struct os_process * proc) [inline, static]
Check if a process is a software interrupt.
Parameters:
proc The process to be checked
Returns:
true if this is a software interrupt, false otherwise
Definition at line 589 of file os_core.h.
References OS_PROCESS_TYPE_INTERRUPT, and os_process::type.
{
#if CONFIG_OS_USE_SW_INTERRUPTS == true
    return (proc->type == OS_PROCESS_TYPE_INTERRUPT);
#else
    return false;
#endif
}
static bool __os_process_is_pending (struct os_process * proc) [inline, static]
Check wether a process is enabled or not.
Parameters:
proc The process to be checked
Returns:
true if enabled, false otherwise
Definition at line 636 of file os_core.h.
References OS_PROCESS_PENDING, and os_process::status.
Referenced by __os_event_scheduler().
{
    return (proc->status == OS_PROCESS_PENDING);
}
static bool __os_process_is_task (struct os_process * proc) [inline, static]
Check if a process is a task.
Parameters:
proc The process to be checked
Returns:
true if this is a task, false otherwise
Definition at line 580 of file os_core.h.
References OS_PROCESS_TYPE_TASK, and os_process::type.
Referenced by os_statistics_task_cpu_allocation(), and os_task_get_current().
{
    return (proc->type == OS_PROCESS_TYPE_TASK);
}
static void __os_process_set_priority (struct os_process * proc, enum os_priority priority) [inline, static]
Change the priority of a process.
Parameters:
proc The process which needs some update
priority The new priority
Precondition:
CONFIG_OS_USE_PRIORITY needs to be set first
Definition at line 647 of file os_core.h.
References os_process::priority, and os_process::priority_counter.
Referenced by os_interrupt_set_priority(), and os_task_set_priority().
{
    /* Not critical so no need to use the os_enter_critical function */
    proc->priority = priority;
    proc->priority_counter = priority;
}
struct os_event* __os_process_sleep (struct os_process * proc, struct os_queue_event * queue_elt, int nb_events, ...) [read]
Generic function to send a processus to sleep. The process can be waken up by one or more events passed in parameter.
Parameters:
proc The processus to send to sleep
queue_elt The empty os_queue_event structure to hold each process instance in the events used to wake up the process.
nb_events The number of events defined to wake up this process
... A list of os_event which can wake up this process
Returns:
A pointer on the event which woke up the process
Definition at line 276 of file os_event.c.
References __os_event_register(), __os_event_start(), __os_process_disable_naked(), __os_process_get_current(), __os_process_is_enabled(), os_enter_critical(), os_is_critical(), os_leave_critical(), os_switch_context, and os_process::status.
{
    int i;
    va_list ap;
    struct os_event *event, *event_triggered = NULL;
    /* Save the critical region status */
    bool is_critical = os_is_critical();
    /* Enter in a critical region if not already in */
    if (!is_critical) {
        os_enter_critical();
    }
    /* Disable the process (send it to sleep) */
    if (__os_process_is_enabled(proc)) {
        __os_process_disable_naked(proc);
    }
    /* Set the process status to pending */
    proc->status = OS_PROCESS_PENDING;
    /* No event has been triggered so far so update the feedback variable
     * to NULL.
     */
    event_triggered = NULL;
    /* Initialize relation pointer between the queue elements */
    queue_elt[0].relation = &queue_elt[0];
    va_start(ap, nb_events);
    i = nb_events;
    while (i--) {
        /* Get the next event from the list */
        event = va_arg(ap, struct os_event *);
        /* Start the event */
        __os_event_start(event, proc);
        /* Register the process in the active event list */
        __os_event_register(event, &queue_elt[i], proc, &event_triggered);
        /* Build a relation between the processes registered */
        if (i) {
            queue_elt[i].relation = queue_elt[0].relation;
            queue_elt[0].relation = &queue_elt[i];
        }
    }
    va_end(ap);
    /* If the process to be send to sleep is thye current process, stop it
     * and use a garbage collector wipe out the extra events registered.
     */
    if (proc == __os_process_get_current()) {
        /* Call the scheduler */
        os_switch_context(false);
    }
    /* Leave the critical region */
    if (!is_critical) {
        os_leave_critical();
    }
    /* Returns a pointer on the event which has woken up the process */
    return event_triggered;
}
struct os_process* __os_scheduler (void) [read]
This function will define the rules to change the task.
Returns:
The new task context
Definition at line 60 of file os_core.c.
References __HOOK_OS_DEBUG_TRACE_LOG, os_process::next, OS_DEBUG_TRACE_CONTEXT_SWITCH, OS_SCHEDULER_PRE_INTERRUPT_HOOK, os_process::priority, and os_process::priority_counter.
Referenced by __os_switch_context_hook(), and __os_switch_context_int_handler_hook().
{
    do {
        /* Get the next process in the active process list */
        __os_current_process = __os_current_process->next;
        /* Check its priority counter and defines if it will run or not
         */
        if (__os_current_process->priority_counter == 0) {
            /* Reload the priority counter */
            __os_current_process->priority_counter =
                    __os_current_process->priority;
            /* Interrupt hook, will be used only if interrupt are
             * enabled.
             */
            OS_SCHEDULER_PRE_INTERRUPT_HOOK();
            /* Log the context switch event. Active only if the
             * trace functionality is enabled.
             */
            __HOOK_OS_DEBUG_TRACE_LOG(OS_DEBUG_TRACE_CONTEXT_SWITCH,
                    __os_current_process);
            /* Return the new process to be executed. The context
             * will be switch to enable this process.
             */
            return __os_current_process;
        }
        /* If the scheduler did not decide to run this process due to
         * its priority level, then decrease its priority counter.
         */
        __os_current_process->priority_counter--;
    /* This is a infinite loop why exists only if a process has the right
     * priority to be execute. It also means that at least 1 process should
     * be on the active process list all the time.
     */
    } while (true);
}
static struct os_process* __os_switch_context_hook (void) [static, read]
This function must be called inside theos_switch_context function in order to switch process context.
Returns:
The context of the new process
Definition at line 675 of file os_core.h.
References __os_scheduler(), and OS_SCHEDULER_POST_INTERRUPT_HOOK.
{
#ifdef OS_SCHEDULER_POST_INTERRUPT_HOOK
    /* Clear the software interrupt if needed */
    OS_SCHEDULER_POST_INTERRUPT_HOOK();
#endif
#ifdef OS_SCHEDULER_POST_EVENT_HOOK
    /* Use the alternate task if any */
    OS_SCHEDULER_POST_EVENT_HOOK();
#endif
    /* Task switch context */
    return __os_scheduler();
}
static struct os_task* __os_task_from_process (struct os_process * proc) [static, read]
Get the task associated with a process.
Parameters:
proc the process
Returns:
The task pointer
Definition at line 98 of file os_task.h.
References os_task::core, and OS_CONTAINER_OF.
Referenced by os_task_get_current().
{
    return OS_CONTAINER_OF(proc, struct os_task, core);
}
static struct os_process* __os_task_get_process (struct os_task * task) [static, read]
Get the task process.
Parameters:
task The task
Returns:
The process of the task
Definition at line 107 of file os_task.h.
References os_task::core.
Referenced by os_statistics_task_cpu_allocation(), os_task_create(), os_task_delete(), os_task_disable(), os_task_enable(), os_task_get_priority(), os_task_is_enabled(), and os_task_set_priority().
{
    return &task->core;
}