OS: Porting functions
Porting functions
eeOS
Functions which should be implemented to port this operating system onto another platform.
Defines
#define os_switch_context(bypass_context_saving)
Context switch for a process.
Function used to schedule and switch between the processes.
This function will handle the return from a softwre interrupt. Therefore it can be optimized to bypass the saving context part IF an interrupt is running.
Functions
static void os_enter_critical (void)
Start of a critical code region. Preemptive context switches cannot occur when in a critical region.
.
static void os_free (os_ptr_t ptr)
Free memory previously allocated by os_malloc.
static void os_leave_critical (void)
Exit a critical code region.
.
static os_ptr_t os_malloc (int stack_size)
Allocate some memory for the stack of a task.
bool os_process_context_load (struct os_process *proc, os_proc_ptr_t proc_ptr, os_ptr_t args)
Load the context of a task into the stack. this is the inital process which will setup the stack before entering in the task function.
void os_setup_scheduler (uint32_t ref_hz)
Setup the task scheduler interrupt.
static struct os_process * os_switch_context_hook (void)
This function must be called inside the os_switch_context function in order to switch process context.
static void os_switch_context_int_handler (void)
Context switch for a process.
Interrupt handler which is used to schedule and switch between the processes.
static struct os_process * os_switch_context_int_handler_hook (void)
This function must be called inside the os_switch_context_int_handler function in order to switch task context.
Detailed Description
Functions which should be implemented to port this operating system onto another platform.
Define Documentation
os_switch_context (bypass_context_saving)
Value:
do { \
        __asm__ __volatile__ ( \
            "mov r8, "ASTRINGZ(bypass_context_saving)"\n\t" \
            "scall\n\t" \
        ); \
    } while (false)
Context switch for a process.
Function used to schedule and switch between the processes.
This function will handle the return from a softwre interrupt. Therefore it can be optimized to bypass the saving context part IF an interrupt is running.
Parameters:
bypass_context_saving If true, this function needs to bypass the context saving.
Definition at line 73 of file os_port.h.
Referenced by __os_interrupt_handler(), os_process_disable(), os_task_sleep(), and os_yield().
Function Documentation
os_enter_critical (void) [inline, static]
Start of a critical code region. Preemptive context switches cannot occur when in a critical region.
.
Definition at line 65 of file os_port.h.
References cpu_irq_disable.
Referenced by __os_event_mutex_is_triggered(), __os_interrupt_handler(), os_event_scheduler(), os_event_sempahore_is_triggered(), os_interrupt_trigger_on_event(), os_mutex_lock(), os_mutex_unlock(), os_process_disable(), os_process_enable(), os_semaphore_release(), os_semaphore_take(), os_task_sleep(), and os_yield().
{
    cpu_irq_disable();
};
void os_free (os_ptr_t ptr) [inline, static]
Free memory previously allocated by os_malloc.
Parameters:
ptr The memory to free
Definition at line 572 of file os_core.h.
Referenced by os_task_delete().
{
    free((void *) ptr);
}
os_leave_critical (void) [inline, static]
Exit a critical code region.
.
Definition at line 69 of file os_port.h.
References cpu_irq_enable.
Referenced by __os_event_mutex_is_triggered(), os_event_scheduler(), os_event_sempahore_is_triggered(), os_interrupt_trigger_on_event(), os_mutex_lock(), os_mutex_unlock(), os_process_disable(), os_process_enable(), os_semaphore_release(), os_semaphore_take(), os_task_sleep(), and os_yield().
{
    cpu_irq_enable();
};
os_ptr_t os_malloc (int stack_size) [inline, static]
Allocate some memory for the stack of a task.
Parameters:
stack_size The size in byte of the stack
Returns:
The pointer of the memory allocated, NULL in case of an error.
Definition at line 561 of file os_core.h.
Referenced by os_task_create().
{
    return (os_ptr_t) malloc(stack_size);
}
bool os_process_context_load (struct os_process * proc, os_proc_ptr_t proc_ptr, os_ptr_t args)
Load the context of a task into the stack. this is the inital process which will setup the stack before entering in the task function.
Parameters:
proc The task
proc_ptr Pointer of the entry point of the process
args Parameters to pass to the task
Returns:
true in case of success, false otherwise
Definition at line 258 of file uc3_port.c.
References CONFIG_OS_DEFAULT_SR_VALUE, and PUSH.
Referenced by os_task_create().
{
    PUSH(proc, 0); // R8
    PUSH(proc, 0); // R9
    PUSH(proc, 0); // R10
    PUSH(proc, 0); // R11
    PUSH(proc, args); // R12
    PUSH(proc, 0); // LR
    PUSH(proc, (void *) proc_ptr); // PC
    PUSH(proc, CONFIG_OS_DEFAULT_SR_VALUE);
    PUSH(proc, 0); // R0
    PUSH(proc, 0); // R1
    PUSH(proc, 0); // R2
    PUSH(proc, 0); // R3
    PUSH(proc, 0); // R4
    PUSH(proc, 0); // R5
    PUSH(proc, 0); // R6
    PUSH(proc, 0); // R7
    return true;
}
void os_setup_scheduler (uint32_t ref_hz)
Setup the task scheduler interrupt.
Parameters:
ref_hz The reference frequency used to clock the peripheral which will generate the tick interrupt. Usually this frequency is equal to the CPU frequency.
Definition at line 37 of file uc3_port.c.
References CONFIG_OS_SCHEDULER_IRQ_PRIORITY, CONFIG_OS_TICK_HZ, cpu_irq_disable, cpu_irq_enable, irq_initialize_vectors, irq_register_handler, os_switch_context_int_handler(), and Set_system_register.
Referenced by os_start().
    {
        cpu_irq_disable();
        irq_initialize_vectors();
        irq_register_handler((__int_handler) os_switch_context_int_handler,
                AVR32_CORE_COMPARE_IRQ, CONFIG_OS_SCHEDULER_IRQ_PRIORITY);
        Set_system_register(AVR32_COMPARE, cpu_freq_hz / CONFIG_OS_TICK_HZ);
        Set_system_register(AVR32_COUNT, 0);
        cpu_irq_enable();
    }
static struct os_process* os_switch_context_hook (void) [static, read]
This function must be called inside the os_switch_context function in order to switch process context.
Returns:
The context of the new process
Definition at line 613 of file os_core.h.
References os_scheduler(), OS_SCHEDULER_POST_EVENT_HOOK, and OS_SCHEDULER_POST_INTERRUPT_HOOK.
Referenced by _os_switch_context().
{
#ifdef OS_SCHEDULER_POST_INTERRUPT_HOOK
    // Clear the software interrupt if needed
    OS_SCHEDULER_POST_INTERRUPT_HOOK();
#endif
#ifdef OS_SCHEDULER_POST_EVENT_HOOK
    // Use the alternate task if any
    OS_SCHEDULER_POST_EVENT_HOOK();
#endif
    // Task switch context
    return os_scheduler();
}
os_switch_context_int_handler (void) [static]
Context switch for a process.
Interrupt handler which is used to schedule and switch between the processes.
Referenced by os_setup_scheduler().
static struct os_process* os_switch_context_int_handler_hook (void) [static, read]
This function must be called inside the os_switch_context_int_handler function in order to switch task context.
Returns:
The context of the new process
Definition at line 594 of file os_core.h.
References HOOK_OS_DEBUG_TICK, HOOK_OS_TICK, os_scheduler(), and tick_counter.
Referenced by ISR().
{
#if CONFIG_OS_USE_TICK_COUNTER == true
    extern volatile os_tick_t tick_counter;
    // Update the tick counter
    tick_counter++;
#endif
#if CONFIG_OS_DEBUG == true
    HOOK_OS_DEBUG_TICK();
#endif
    HOOK_OS_TICK();
    // Task switch context
    return os_scheduler();
}