OS: CPU - Cycle Counter
CPU - Cycle Counter
CPU Cycle Counter provides an interface to the COUNT and COMPARE registers.
Data Structures
struct t_cpu_time
Structure holding private information, automatically initialized by the cpu_set_timeout() function.
Defines
#define Get_sys_compare() (Get_system_register(AVR32_COMPARE))
#define Get_sys_count() (Get_system_register(AVR32_COUNT))
#define Set_sys_compare(x) (Set_system_register(AVR32_COMPARE, (x)))
#define Set_sys_count(x) (Set_system_register(AVR32_COUNT, (x)))
Functions
static uint32_t cpu_cy_2_ms (unsigned long cy, unsigned long fcpu_hz)
Convert CPU cycles into milli-seconds.
static uint32_t cpu_cy_2_us (unsigned long cy, unsigned long fcpu_hz)
Convert CPU cycles into micro-seconds.
static void cpu_delay_cy (unsigned long delay)
Waits during at least the specified delay (in CPU cycles) before returning.
static void cpu_delay_ms (unsigned long delay, unsigned long fcpu_hz)
Waits during at least the specified delay (in millisecond) before returning.
static void cpu_delay_us (unsigned long delay, unsigned long fcpu_hz)
Waits during at least the specified delay (in microsecond) before returning.
static unsigned long cpu_is_timeout (t_cpu_time *cpu_time)
Test if a timer variable reached its timeout.
static unsigned long cpu_is_timer_stopped (t_cpu_time *cpu_time)
Test if a timer is stopped.
static uint32_t cpu_ms_2_cy (unsigned long ms, unsigned long fcpu_hz)
Convert milli-seconds into CPU cycles.
static void cpu_set_timeout (unsigned long delay, t_cpu_time *cpu_time)
Set a timer variable.
static void cpu_stop_timeout (t_cpu_time *cpu_time)
Stop a timeout detection.
static uint32_t cpu_us_2_cy (unsigned long us, unsigned long fcpu_hz)
Convert micro-seconds into CPU cycles.
Detailed Description
CPU Cycle Counter provides an interface to the COUNT and COMPARE registers.
Define Documentation
#define Get_sys_compare () (Get_system_register(AVR32_COMPARE))
Definition at line 311 of file cycle_counter.h.
#define Get_sys_count () (Get_system_register(AVR32_COUNT))
Definition at line 309 of file cycle_counter.h.
#define Set_sys_compare (x) (Set_system_register(AVR32_COMPARE, (x)))
Definition at line 312 of file cycle_counter.h.
#define Set_sys_count (x) (Set_system_register(AVR32_COUNT, (x)))
Definition at line 310 of file cycle_counter.h.
Function Documentation
static uint32_t cpu_cy_2_ms (unsigned long cy, unsigned long fcpu_hz) [inline, static]
Convert CPU cycles into milli-seconds.
Parameters:
cy,: Number of CPU cycles.
fcpu_hz,: CPU frequency in Hz.
Returns:
the converted number of milli-second.
Definition at line 123 of file cycle_counter.h.
{
  return ((unsigned long long)cy * 1000 + fcpu_hz-1) / fcpu_hz;
}
static uint32_t cpu_cy_2_us (unsigned long cy, unsigned long fcpu_hz) [inline, static]
Convert CPU cycles into micro-seconds.
Parameters:
cy,: Number of CPU cycles.
fcpu_hz,: CPU frequency in Hz.
Returns:
the converted number of micro-second.
Definition at line 140 of file cycle_counter.h.
{
  return ((unsigned long long)cy * 1000000 + fcpu_hz-1) / fcpu_hz;
}
static void cpu_delay_cy (unsigned long delay) [inline, static]
Waits during at least the specified delay (in CPU cycles) before returning.
Parameters:
delay,: Number of CPU cycles to wait.
Definition at line 301 of file cycle_counter.h.
References cpu_is_timeout(), and cpu_set_timeout().
{
  t_cpu_time timer;
  cpu_set_timeout( delay, &timer);
  while( !cpu_is_timeout(&timer) );
}
static void cpu_delay_ms (unsigned long delay, unsigned long fcpu_hz) [inline, static]
Waits during at least the specified delay (in millisecond) before returning.
Parameters:
delay,: Number of millisecond to wait.
fcpu_hz,: CPU frequency in Hz.
Definition at line 270 of file cycle_counter.h.
References cpu_is_timeout(), cpu_ms_2_cy(), and cpu_set_timeout().
{
  t_cpu_time timer;
  cpu_set_timeout( cpu_ms_2_cy(delay, fcpu_hz), &timer);
  while( !cpu_is_timeout(&timer) );
}
static void cpu_delay_us (unsigned long delay, unsigned long fcpu_hz) [inline, static]
Waits during at least the specified delay (in microsecond) before returning.
Parameters:
delay,: Number of microsecond to wait.
fcpu_hz,: CPU frequency in Hz.
Definition at line 286 of file cycle_counter.h.
References cpu_is_timeout(), cpu_set_timeout(), and cpu_us_2_cy().
{
  t_cpu_time timer;
  cpu_set_timeout( cpu_us_2_cy(delay, fcpu_hz), &timer);
  while( !cpu_is_timeout(&timer) );
}
static unsigned long cpu_is_timeout (t_cpu_time * cpu_time) [inline, static]
Test if a timer variable reached its timeout.
Once the timeout is reached, the function will always return true, until the cpu_stop_timeout() function is called.
Ex: t_cpu_time timer; cpu_set_timeout(10, FOSC0, &timer); // timeout in 10 ms if(cpu_is_timeout(&timer)) cpu_stop_timeout(&timer); ../..
Parameters:
cpu_time,: (input) internal information used by the timer API.
Returns:
true if timeout occured, otherwise false.
Definition at line 188 of file cycle_counter.h.
References CPU_TIMER_STATE_REACHED, CPU_TIMER_STATE_STOPPED, t_cpu_time::delay_end_cycle, t_cpu_time::delay_start_cycle, Get_system_register, and t_cpu_time::timer_state.
Referenced by cpu_delay_cy(), cpu_delay_ms(), and cpu_delay_us().
{
  unsigned long current_cycle_count = Get_system_register(AVR32_COUNT);
  if( cpu_time->timer_state==CPU_TIMER_STATE_STOPPED )
    return false;
  // Test if the timeout as already occured.
  else if (cpu_time->timer_state == CPU_TIMER_STATE_REACHED)
    return true;
  // If the ending cycle count of this timeout is wrapped, ...
  else if (cpu_time->delay_start_cycle > cpu_time->delay_end_cycle)
  {
    if (current_cycle_count < cpu_time->delay_start_cycle && current_cycle_count > cpu_time->delay_end_cycle)
    {
      cpu_time->timer_state = CPU_TIMER_STATE_REACHED;
      return true;
    }
    return false;
  }
  else
  {
    if (current_cycle_count < cpu_time->delay_start_cycle || current_cycle_count > cpu_time->delay_end_cycle)
    {
      cpu_time->timer_state = CPU_TIMER_STATE_REACHED;
      return true;
    }
    return false;
  }
}
static unsigned long cpu_is_timer_stopped (t_cpu_time * cpu_time) [inline, static]
Test if a timer is stopped.
Parameters:
cpu_time,: (input) internal information used by the timer API.
Returns:
true if timer is stopped, otherwise false.
Definition at line 251 of file cycle_counter.h.
References CPU_TIMER_STATE_STOPPED, and t_cpu_time::timer_state.
{
  if( cpu_time->timer_state==CPU_TIMER_STATE_STOPPED )
    return true;
  else
    return false;
}
static uint32_t cpu_ms_2_cy (unsigned long ms, unsigned long fcpu_hz) [inline, static]
Convert milli-seconds into CPU cycles.
Parameters:
ms,: Number of millisecond.
fcpu_hz,: CPU frequency in Hz.
Returns:
the converted number of CPU cycles.
Definition at line 89 of file cycle_counter.h.
Referenced by cpu_delay_ms().
{
  return ((unsigned long long)ms * fcpu_hz + 999) / 1000;
}
static void cpu_set_timeout (unsigned long delay, t_cpu_time * cpu_time) [inline, static]
Set a timer variable.
Ex: t_cpu_time timer; cpu_set_timeout(cpu_ms_2_cy(10, FOSC0), &timer); // timeout in 10 ms if(cpu_is_timeout(&timer)) cpu_stop_timeout(&timer); ../..
Parameters:
delay,: (input) delay in CPU cycles before timeout.
cpu_time,: (output) internal information used by the timer API.
Definition at line 161 of file cycle_counter.h.
References CPU_TIMER_STATE_STARTED, t_cpu_time::delay_end_cycle, t_cpu_time::delay_start_cycle, Get_system_register, and t_cpu_time::timer_state.
Referenced by cpu_delay_cy(), cpu_delay_ms(), and cpu_delay_us().
{
  cpu_time->delay_start_cycle = Get_system_register(AVR32_COUNT);
  cpu_time->delay_end_cycle   = cpu_time->delay_start_cycle + delay;
  cpu_time->timer_state       = CPU_TIMER_STATE_STARTED;
}
static void cpu_stop_timeout (t_cpu_time * cpu_time) [inline, static]
Stop a timeout detection.
Ex: t_cpu_time timer; cpu_set_timeout(10, FOSC0, &timer); // timeout in 10 ms if(cpu_is_timeout(&timer)) cpu_stop_timeout(&timer); ../..
Parameters:
cpu_time,: (input) internal information used by the timer API.
Definition at line 235 of file cycle_counter.h.
References CPU_TIMER_STATE_STOPPED, and t_cpu_time::timer_state.
{
  cpu_time->timer_state = CPU_TIMER_STATE_STOPPED;
}
static uint32_t cpu_us_2_cy (unsigned long us, unsigned long fcpu_hz) [inline, static]
Convert micro-seconds into CPU cycles.
Parameters:
us,: Number of microsecond.
fcpu_hz,: CPU frequency in Hz.
Returns:
the converted number of CPU cycles.
Definition at line 106 of file cycle_counter.h.
Referenced by cpu_delay_us().
{
  return ((unsigned long long)us * fcpu_hz + 999999) / 1000000;
}