OS: TIMING - RTC - Real Time Counter
TIMING - RTC - Real Time Counter
Driver for the RTC (32-bit Real Time Counter).
Functions
void rtc_clear_interrupt (volatile avr32_rtc_t *rtc)
Clear the interrupt flag. Call this function once you handled the interrupt.
void rtc_disable (volatile avr32_rtc_t *rtc)
Disable the RTC.
void rtc_disable_interrupt (volatile avr32_rtc_t *rtc)
Disable the interrupt feature of the RTC.
void rtc_disable_wake_up (volatile avr32_rtc_t *rtc)
Disable the wake up feature of the RTC.
void rtc_enable (volatile avr32_rtc_t *rtc)
Enable the RTC.
void rtc_enable_interrupt (volatile avr32_rtc_t *rtc)
Enable the interrupt feature of the RTC. An interrupt is raised when the value of the RTC is equal to its top value.
void rtc_enable_wake_up (volatile avr32_rtc_t *rtc)
Enable the wake up feature of the RTC.
unsigned long rtc_get_top_value (volatile avr32_rtc_t *rtc)
This function returns the RTC current top value.
unsigned long rtc_get_value (volatile avr32_rtc_t *rtc)
This function returns the RTC current value.
int rtc_init (volatile avr32_rtc_t *rtc, unsigned char osc_type, unsigned char psel)
This function will initialise the RTC module. If you use the 32 KHz oscillator, it will enable this module. This function also set the top value of the RTC to 0xFFFFFFFF and the value to 0.
int rtc_interrupt_enabled (volatile avr32_rtc_t *rtc)
Get the status of interrupts.
int rtc_is_busy (volatile avr32_rtc_t *rtc)
This function checks if the RTC is busy or not.
int rtc_is_interrupt (volatile avr32_rtc_t *rtc)
Check if an interrupt is raised.
void rtc_set_top_value (volatile avr32_rtc_t *rtc, unsigned long top)
This function sets the RTC current top value.
void rtc_set_value (volatile avr32_rtc_t *rtc, unsigned long val)
This function sets the RTC current value.
Oscillator Types
#define RTC_OSC_32KHZ 1
#define RTC_OSC_RC 0
Predefined PSEL Values
#define RTC_PSEL_32KHZ_1HZ 14
The PSEL value to set the RTC source clock (after the prescaler) to 1 Hz, when using an external 32-kHz crystal.
#define RTC_PSEL_RC_1_76HZ 15
The PSEL value to set the RTC source clock (after the prescaler) to 1.76 Hz, when using the internal RC oscillator (~ 115 kHz).
Detailed Description
Driver for the RTC (32-bit Real Time Counter).
The RTC enables periodic interrupts at long intervals, or accurate measurement of real-time sequences. Can be clocked from internal RC oscillator or external 32 kHz crystal.
Define Documentation
#define RTC_OSC_32KHZ 1
Definition at line 69 of file rtc.h.
Referenced by rtc_init().
#define RTC_OSC_RC 0
Definition at line 70 of file rtc.h.
#define RTC_PSEL_32KHZ_1HZ 14
The PSEL value to set the RTC source clock (after the prescaler) to 1 Hz, when using an external 32-kHz crystal.
Definition at line 79 of file rtc.h.
#define RTC_PSEL_RC_1_76HZ 15
The PSEL value to set the RTC source clock (after the prescaler) to 1.76 Hz, when using the internal RC oscillator (~ 115 kHz).
Definition at line 83 of file rtc.h.
Function Documentation
void rtc_clear_interrupt (volatile avr32_rtc_t * rtc)
Clear the interrupt flag. Call this function once you handled the interrupt.
Parameters:
rtc Base address of the RTC (i.e. &AVR32_RTC).
Definition at line 174 of file rtc.c.
References cpu_irq_disable, cpu_irq_enable, and cpu_irq_is_enabled.
{
  bool global_interrupt_enabled = cpu_irq_is_enabled();
  if (global_interrupt_enabled) cpu_irq_disable();
  rtc->icr = AVR32_RTC_ICR_TOPI_MASK;
  rtc->isr;
  if (global_interrupt_enabled) cpu_irq_enable();
}
void rtc_disable (volatile avr32_rtc_t * rtc)
Disable the RTC.
Parameters:
rtc Base address of the RTC (i.e. &AVR32_RTC).
Definition at line 146 of file rtc.c.
References rtc_is_busy().
{
  // Wait until the rtc CTRL register is up-to-date
  while (rtc_is_busy(rtc));
  // Disable the RTC
  rtc->ctrl &= ~AVR32_RTC_CTRL_EN_MASK;
  // Wait until write is done
  while (rtc_is_busy(rtc));
}
void rtc_disable_interrupt (volatile avr32_rtc_t * rtc)
Disable the interrupt feature of the RTC.
Parameters:
rtc Base address of the RTC (i.e. &AVR32_RTC).
Definition at line 163 of file rtc.c.
References cpu_irq_disable, cpu_irq_enable, and cpu_irq_is_enabled.
{
  bool global_interrupt_enabled = cpu_irq_is_enabled();
  if (global_interrupt_enabled) cpu_irq_disable();
  rtc->idr = AVR32_RTC_IDR_TOPI_MASK;
  rtc->imr;
  if (global_interrupt_enabled) cpu_irq_enable();
}
void rtc_disable_wake_up (volatile avr32_rtc_t * rtc)
Disable the wake up feature of the RTC.
Parameters:
rtc Base address of the RTC (i.e. &AVR32_RTC).
Definition at line 124 of file rtc.c.
References rtc_is_busy().
{
  // Wait until the rtc CTRL register is up-to-date
  while (rtc_is_busy(rtc));
  // Disable the wake up of the RTC
  rtc->ctrl &= ~AVR32_RTC_CTRL_WAKE_EN_MASK;
  // Wait until write is done
  while (rtc_is_busy(rtc));
}
void rtc_enable (volatile avr32_rtc_t * rtc)
Enable the RTC.
Parameters:
rtc Base address of the RTC (i.e. &AVR32_RTC).
Definition at line 135 of file rtc.c.
References rtc_is_busy().
{
  // Wait until the rtc CTRL register is up-to-date
  while (rtc_is_busy(rtc));
  // Enable the RTC
  rtc->ctrl |= AVR32_RTC_CTRL_EN_MASK;
  // Wait until write is done
  while (rtc_is_busy(rtc));
}
void rtc_enable_interrupt (volatile avr32_rtc_t * rtc)
Enable the interrupt feature of the RTC. An interrupt is raised when the value of the RTC is equal to its top value.
Parameters:
rtc Base address of the RTC (i.e. &AVR32_RTC).
Definition at line 157 of file rtc.c.
{
  rtc->ier = AVR32_RTC_IER_TOPI_MASK;
}
void rtc_enable_wake_up (volatile avr32_rtc_t * rtc)
Enable the wake up feature of the RTC.
Parameters:
rtc Base address of the RTC (i.e. &AVR32_RTC).
Definition at line 113 of file rtc.c.
References rtc_is_busy().
{
  // Wait until the rtc CTRL register is up-to-date
  while (rtc_is_busy(rtc));
  // Enable the wake up of the RTC
  rtc->ctrl |= AVR32_RTC_CTRL_WAKE_EN_MASK;
  // Wait until write is done
  while (rtc_is_busy(rtc));
}
unsigned long rtc_get_top_value (volatile avr32_rtc_t * rtc)
This function returns the RTC current top value.
Parameters:
rtc Base address of the RTC (i.e. &AVR32_RTC).
Returns:
The RTC current top value.
Definition at line 196 of file rtc.c.
{
  return rtc->top;
}
unsigned long rtc_get_value (volatile avr32_rtc_t * rtc)
This function returns the RTC current value.
Parameters:
rtc Base address of the RTC (i.e. &AVR32_RTC).
Returns:
The RTC current value.
Definition at line 107 of file rtc.c.
{
  return rtc->val;
}
int rtc_init (volatile avr32_rtc_t * rtc, unsigned char osc_type, unsigned char psel)
This function will initialise the RTC module. If you use the 32 KHz oscillator, it will enable this module. This function also set the top value of the RTC to 0xFFFFFFFF and the value to 0.
Parameters:
rtc Base address of the RTC (i.e. &AVR32_RTC).
osc_type The oscillator you want to use. If you need a better accuracy, use the 32 KHz oscillator (i.e. RTC_OSC_32KHZ).
psel The preselector value for the corresponding oscillator (4-bits). To obtain this value, you can use this formula: psel = log(Fosc/Frtc)/log(2)-1, where Fosc is the frequency of the oscillator you are using (32 KHz or 115 KHz) and Frtc the frequency desired.
Returns:
1 if the initialisation succeds otherwize it will return 0.
Definition at line 60 of file rtc.c.
References pm_enable_clk32(), pm_enable_osc32_crystal(), rtc_is_busy(), RTC_OSC_32KHZ, rtc_set_top_value(), and rtc_set_value().
{
  // If exit, it means that the configuration has not been set correctly
  if (osc_type > (1 << AVR32_RTC_CTRL_CLK32_SIZE) - 1 ||
      psel > (1 << AVR32_RTC_CTRL_PSEL_SIZE) - 1)
    return 0;
  // If we use the 32-kHz oscillator, we have to enable it first
  if (osc_type == RTC_OSC_32KHZ)
  {
    // Select the 32-kHz oscillator crystal
    pm_enable_osc32_crystal(&AVR32_PM);
    // Enable the 32-kHz clock and wait until the osc32 clock is ready.
    pm_enable_clk32(&AVR32_PM, AVR32_PM_OSCCTRL32_STARTUP_0_RCOSC);
  }
  // Wait until the rtc accepts writes to the CTRL register
  while (rtc_is_busy(rtc));
  // Set the new RTC configuration
  rtc->ctrl = osc_type << AVR32_RTC_CTRL_CLK32_OFFSET |
              psel << AVR32_RTC_CTRL_PSEL_OFFSET |
              AVR32_RTC_CTRL_CLKEN_MASK;
  // Wait until write is done
  while (rtc_is_busy(rtc));
  // Set the counter value to 0
  rtc_set_value(rtc, 0x00000000);
  // Set the top value to 0xFFFFFFFF
  rtc_set_top_value(rtc, 0xFFFFFFFF);
  return 1;
}
int rtc_interrupt_enabled (volatile avr32_rtc_t * rtc)
Get the status of interrupts.
Parameters:
rtc Base address of the RTC (i.e. &AVR32_RTC).
Returns:
1 if the interrupts are enabled otherwize it returns 0.
Definition at line 202 of file rtc.c.
{
  return (rtc->imr & AVR32_RTC_IMR_TOPI_MASK) != 0;
}
int rtc_is_busy (volatile avr32_rtc_t * rtc)
This function checks if the RTC is busy or not.
Parameters:
rtc Base address of the RTC (i.e. &AVR32_RTC).
Returns:
1 if the RTC is busy otherwize it will return 0.
Definition at line 54 of file rtc.c.
Referenced by rtc_disable(), rtc_disable_wake_up(), rtc_enable(), rtc_enable_wake_up(), rtc_init(), rtc_set_top_value(), and rtc_set_value().
{
  return (rtc->ctrl & AVR32_RTC_CTRL_BUSY_MASK) != 0;
}
int rtc_is_interrupt (volatile avr32_rtc_t * rtc)
Check if an interrupt is raised.
Parameters:
rtc Base address of the RTC (i.e. &AVR32_RTC).
Returns:
1 if an interrupt is currently raised otherwize it returns 0.
Definition at line 208 of file rtc.c.
{
  return (rtc->isr & AVR32_RTC_ISR_TOPI_MASK) != 0;
}
void rtc_set_top_value (volatile avr32_rtc_t * rtc, unsigned long top)
This function sets the RTC current top value.
Parameters:
rtc Base address of the RTC (i.e. &AVR32_RTC).
top The top value you want to store.
Definition at line 185 of file rtc.c.
References rtc_is_busy().
Referenced by rtc_init().
{
  // Wait until we can write into the VAL register
  while (rtc_is_busy(rtc));
  // Set the new val value
  rtc->top = top;
  // Wait until write is done
  while (rtc_is_busy(rtc));
}
void rtc_set_value (volatile avr32_rtc_t * rtc, unsigned long val)
This function sets the RTC current value.
Parameters:
rtc Base address of the RTC (i.e. &AVR32_RTC).
val The value you want to store.
Definition at line 96 of file rtc.c.
References rtc_is_busy().
Referenced by rtc_init().
{
  // Wait until we can write into the VAL register
  while (rtc_is_busy(rtc));
  // Set the new val value
  rtc->val = val;
  // Wait until write is done
  while (rtc_is_busy(rtc));
}