OS: CPU - PM - Power Manager
CPU - PM - Power Manager
The Power Manager (PM) controls the oscillators and PLLs, and generates the clocks and resets in the device.
Data Structures
struct pm_freq_param_t
Input and output parameters when initializing PM clocks using pm_configure_clocks().
Modules
Power Clocks Library
Defines
#define PM_FREQ_STATUS_FAIL (-1)
#define PM_FREQ_STATUS_OK (0)
Functions
void pm_bod_clear_irq (volatile avr32_pm_t *pm)
Clears the Brown-Out Detector interrupt flag.
void pm_bod_disable_irq (volatile avr32_pm_t *pm)
Disables the Brown-Out Detector interrupt.
void pm_bod_enable_irq (volatile avr32_pm_t *pm)
Enables the Brown-Out Detector interrupt.
unsigned long pm_bod_get_irq_enable_bit (volatile avr32_pm_t *pm)
Gets the Brown-Out Detector interrupt enable status.
unsigned long pm_bod_get_irq_status (volatile avr32_pm_t *pm)
Gets the Brown-Out Detector interrupt flag.
unsigned long pm_bod_get_level (volatile avr32_pm_t *pm)
Gets the triggering threshold of the Brown-Out Detector.
void pm_cksel (volatile avr32_pm_t *pm, unsigned int pbadiv, unsigned int pbasel, unsigned int pbbdiv, unsigned int pbbsel, unsigned int hsbdiv, unsigned int hsbsel)
This function will select all the power manager clocks.
void pm_cksel_get (volatile avr32_pm_t *pm, unsigned long *p_cksel)
This function returns the cksel (Clock Select).
void pm_cksel_set (volatile avr32_pm_t *pm, unsigned long cksel)
This function set the cksel (Clock Select).
int pm_configure_clocks (pm_freq_param_t *param)
Automatically configure the CPU, PBA, PBB, and HSB clocks according to the user wishes.
void pm_configure_usb_clock (void)
Automatically configure the USB clock.
void pm_disable_clk0 (volatile avr32_pm_t *pm)
This function will disable the oscillator 0.
void pm_disable_clk1 (volatile avr32_pm_t *pm)
This function will disable the oscillator 1.
void pm_disable_clk32 (volatile avr32_pm_t *pm)
This function will disable the oscillator 32.
long pm_disable_module (volatile avr32_pm_t *pm, unsigned long module)
Disable the clock of a module.
void pm_enable_clk0 (volatile avr32_pm_t *pm, unsigned int startup)
This function will enable the oscillator 0 to be used with a startup time.
void pm_enable_clk0_no_wait (volatile avr32_pm_t *pm, unsigned int startup)
This function will enable the oscillator 0 to be used with no startup time.
void pm_enable_clk1 (volatile avr32_pm_t *pm, unsigned int startup)
This function will enable the oscillator 1 to be used with a startup time.
void pm_enable_clk1_no_wait (volatile avr32_pm_t *pm, unsigned int startup)
This function will enable the oscillator 1 to be used with no startup time.
void pm_enable_clk32 (volatile avr32_pm_t *pm, unsigned int startup)
This function will enable the oscillator 32 to be used with a startup time.
void pm_enable_clk32_no_wait (volatile avr32_pm_t *pm, unsigned int startup)
This function will enable the oscillator 32 to be used with no startup time.
long pm_enable_module (volatile avr32_pm_t *pm, unsigned long module)
Enable the clock of a module.
void pm_enable_osc0_crystal (volatile avr32_pm_t *pm, unsigned int fosc0)
This function will enable the crystal mode of the oscillator 0.
void pm_enable_osc0_ext_clock (volatile avr32_pm_t *pm)
This function will enable the external clock mode of the oscillator 0.
void pm_enable_osc1_crystal (volatile avr32_pm_t *pm, unsigned int fosc1)
This function will enable the crystal mode of the oscillator 1.
void pm_enable_osc1_ext_clock (volatile avr32_pm_t *pm)
This function will enable the external clock mode of the oscillator 1.
void pm_enable_osc32_crystal (volatile avr32_pm_t *pm)
This function will enable the crystal mode of the 32-kHz oscillator.
void pm_enable_osc32_ext_clock (volatile avr32_pm_t *pm)
This function will enable the external clock mode of the 32-kHz oscillator.
void pm_gc_disable (volatile avr32_pm_t *pm, unsigned int gc)
This function will disable a generic clock.
void pm_gc_enable (volatile avr32_pm_t *pm, unsigned int gc)
This function will enable a generic clock.
void pm_gc_setup (volatile avr32_pm_t *pm, unsigned int gc, unsigned int osc_or_pll, unsigned int pll_osc, unsigned int diven, unsigned int div)
This function will setup a generic clock.
unsigned long pm_get_clock (volatile avr32_pm_t *pm)
This function returns the power manager main clock.
static unsigned int pm_get_reset_cause (volatile avr32_pm_t *pm)
Gets the MCU reset cause.
void pm_pll_disable (volatile avr32_pm_t *pm, unsigned int pll)
This function will disable a PLL.
void pm_pll_enable (volatile avr32_pm_t *pm, unsigned int pll)
This function will enable a PLL.
unsigned int pm_pll_get_option (volatile avr32_pm_t *pm, unsigned int pll)
This function will get a PLL option.
void pm_pll_set_option (volatile avr32_pm_t *pm, unsigned int pll, unsigned int pll_freq, unsigned int pll_div2, unsigned int pll_wbwdisable)
This function will set a PLL option.
void pm_pll_setup (volatile avr32_pm_t *pm, unsigned int pll, unsigned int mul, unsigned int div, unsigned int osc, unsigned int lockcount)
This function will setup a PLL.
unsigned long pm_read_gplp (volatile avr32_pm_t *pm, unsigned long gplp)
Read the content of the PM GPLP registers.
void pm_switch_to_clock (volatile avr32_pm_t *pm, unsigned long clock)
This function will switch the power manager main clock.
void pm_switch_to_osc0 (volatile avr32_pm_t *pm, unsigned int fosc0, unsigned int startup)
Switch main clock to clock Osc0 (crystal mode)
void pm_wait_for_clk0_ready (volatile avr32_pm_t *pm)
This function will wait until the Osc0 clock is ready.
void pm_wait_for_clk1_ready (volatile avr32_pm_t *pm)
This function will wait until the Osc1 clock is ready.
void pm_wait_for_clk32_ready (volatile avr32_pm_t *pm)
This function will wait until the osc32 clock is ready.
void pm_wait_for_pll0_locked (volatile avr32_pm_t *pm)
This function will wait for PLL0 locked.
void pm_wait_for_pll1_locked (volatile avr32_pm_t *pm)
This function will wait for PLL1 locked.
void pm_write_gplp (volatile avr32_pm_t *pm, unsigned long gplp, unsigned long value)
Write into the PM GPLP registers.
Sleep Functions
static void pm_asyn_wake_up_enable (unsigned long awen_mask)
Enable one or several asynchronous wake-up source.
static void pm_asyn_wake_up_disable (unsigned long awen_mask)
Disable one or several asynchronous wake-up sources.
#define SLEEP(mode) {__asm__ __volatile__ ("sleep "STRINGZ(mode));}
Sets the MCU in the specified sleep mode.
Detailed Description
The Power Manager (PM) controls the oscillators and PLLs, and generates the clocks and resets in the device.
Define Documentation
#define PM_FREQ_STATUS_FAIL (-1)
Definition at line 126 of file pm.h.
Referenced by pm_configure_clocks().
#define PM_FREQ_STATUS_OK (0)
Definition at line 127 of file pm.h.
Referenced by pm_configure_clocks().
#define SLEEP (mode) {__asm__ __volatile__ ("sleep "STRINGZ(mode));}
Sets the MCU in the specified sleep mode.
Parameters:
mode Sleep mode:
AVR32_PM_SMODE_IDLE: Idle;
AVR32_PM_SMODE_FROZEN: Frozen;
AVR32_PM_SMODE_STANDBY: Standby;
AVR32_PM_SMODE_STOP: Stop;
AVR32_PM_SMODE_DEEP_STOP: DeepStop;
AVR32_PM_SMODE_STATIC: Static.
Definition at line 77 of file pm.h.
Referenced by pm_sleep().
Function Documentation
static void pm_asyn_wake_up_disable (unsigned long awen_mask) [inline, static]
Disable one or several asynchronous wake-up sources.
Parameters:
awen_mask Mask of asynchronous wake-up sources (use one of the defines AVR32_PM_AWEN_xxxxWEN_MASK in the part-specific header file under "toolchain folder"/avr32/inc(lude)/avr32/)
Definition at line 102 of file pm.h.
{
  AVR32_PM.awen &= ~awen_mask;
}
static void pm_asyn_wake_up_enable (unsigned long awen_mask) [inline, static]
Enable one or several asynchronous wake-up source.
Parameters:
awen_mask Mask of asynchronous wake-up sources (use one of the defines AVR32_PM_AWEN_xxxxWEN_MASK in the part-specific header file under "toolchain folder"/avr32/inc(lude)/avr32/)
Definition at line 88 of file pm.h.
{
  AVR32_PM.awen |= awen_mask;
}
void pm_bod_clear_irq (volatile avr32_pm_t * pm)
Clears the Brown-Out Detector interrupt flag.
Parameters:
pm Base address of the Power Manager (i.e. &AVR32_PM).
Definition at line 506 of file pm.c.
{
  pm->icr = AVR32_PM_ICR_BODDET_MASK;
}
void pm_bod_disable_irq (volatile avr32_pm_t * pm)
Disables the Brown-Out Detector interrupt.
Parameters:
pm Base address of the Power Manager (i.e. &AVR32_PM).
Definition at line 495 of file pm.c.
References cpu_irq_disable, cpu_irq_enable, and cpu_irq_is_enabled.
{
  bool global_interrupt_enabled = cpu_irq_is_enabled();
  if (global_interrupt_enabled) cpu_irq_disable();
  pm->idr = AVR32_PM_IDR_BODDET_MASK;
  pm->isr;
  if (global_interrupt_enabled) cpu_irq_enable();
}
void pm_bod_enable_irq (volatile avr32_pm_t * pm)
Enables the Brown-Out Detector interrupt.
Parameters:
pm Base address of the Power Manager (i.e. &AVR32_PM).
Definition at line 489 of file pm.c.
{
  pm->ier = AVR32_PM_IER_BODDET_MASK;
}
unsigned long pm_bod_get_irq_enable_bit (volatile avr32_pm_t * pm)
Gets the Brown-Out Detector interrupt enable status.
Parameters:
pm Base address of the Power Manager (i.e. &AVR32_PM).
Return values:
0 BOD interrupt disabled.
1 BOD interrupt enabled.
Definition at line 518 of file pm.c.
{
  return ((pm->imr & AVR32_PM_IMR_BODDET_MASK) != 0);
}
unsigned long pm_bod_get_irq_status (volatile avr32_pm_t * pm)
Gets the Brown-Out Detector interrupt flag.
Parameters:
pm Base address of the Power Manager (i.e. &AVR32_PM).
Return values:
0 No BOD interrupt.
1 BOD interrupt pending.
Definition at line 512 of file pm.c.
{
  return ((pm->isr & AVR32_PM_ISR_BODDET_MASK) != 0);
}
unsigned long pm_bod_get_level (volatile avr32_pm_t * pm)
Gets the triggering threshold of the Brown-Out Detector.
Parameters:
pm Base address of the Power Manager (i.e. &AVR32_PM).
Returns:
Triggering threshold of the BOD. See the electrical characteristics in the part datasheet for actual voltage levels.
Definition at line 524 of file pm.c.
{
  return (pm->bod & AVR32_PM_BOD_LEVEL_MASK) >> AVR32_PM_BOD_LEVEL_OFFSET;
}
void pm_cksel (volatile avr32_pm_t * pm, unsigned int pbadiv, unsigned int pbasel, unsigned int pbbdiv, unsigned int pbbsel, unsigned int hsbdiv, unsigned int hsbsel)
This function will select all the power manager clocks.
Parameters:
pm Base address of the Power Manager (i.e. &AVR32_PM)
pbadiv Peripheral Bus A clock divisor enable
pbasel Peripheral Bus A select
pbbdiv Peripheral Bus B clock divisor enable
pbbsel Peripheral Bus B select
hsbdiv High Speed Bus clock divisor enable (CPU clock = HSB clock)
hsbsel High Speed Bus select (CPU clock = HSB clock)
Definition at line 342 of file pm.c.
References u_avr32_pm_cksel_t::cksel, and u_avr32_pm_cksel_t::CKSEL.
Referenced by pm_configure_clocks().
{
  u_avr32_pm_cksel_t u_avr32_pm_cksel = {0};
  u_avr32_pm_cksel.CKSEL.cpusel = hsbsel;
  u_avr32_pm_cksel.CKSEL.cpudiv = hsbdiv;
  u_avr32_pm_cksel.CKSEL.hsbsel = hsbsel;
  u_avr32_pm_cksel.CKSEL.hsbdiv = hsbdiv;
  u_avr32_pm_cksel.CKSEL.pbasel = pbasel;
  u_avr32_pm_cksel.CKSEL.pbadiv = pbadiv;
  u_avr32_pm_cksel.CKSEL.pbbsel = pbbsel;
  u_avr32_pm_cksel.CKSEL.pbbdiv = pbbdiv;
  pm->cksel = u_avr32_pm_cksel.cksel;
  // Wait for ckrdy bit and then clear it
  while (!(pm->poscsr & AVR32_PM_POSCSR_CKRDY_MASK));
}
void pm_cksel_get (volatile avr32_pm_t * pm, unsigned long * p_cksel)
This function returns the cksel (Clock Select).
Parameters:
pm Base address of the Power Manager (i.e. &AVR32_PM)
p_cksel output cksel value
Definition at line 327 of file pm.c.
{
  *p_cksel = pm->cksel;
}
void pm_cksel_set (volatile avr32_pm_t * pm, unsigned long cksel)
This function set the cksel (Clock Select).
Parameters:
pm Base address of the Power Manager (i.e. &AVR32_PM)
cksel The cksel value.
Definition at line 333 of file pm.c.
{
  pm->cksel = cksel;
  // Wait for ckrdy bit and then clear it
  while (!(pm->poscsr & AVR32_PM_POSCSR_CKRDY_MASK));
}
int pm_configure_clocks (pm_freq_param_t * param)
Automatically configure the CPU, PBA, PBB, and HSB clocks according to the user wishes.
This function needs some parameters stored in a pm_freq_param_t structure:
cpu_f and pba_f are the wanted frequencies,
osc0_f is the oscillator 0 on-board frequency (e.g. FOSC0),
osc0_startup is the oscillator 0 startup time (e.g. OSC0_STARTUP).
The function will then configure the clocks using the following rules:
It first try to find a valid PLL frequency (the highest possible value to avoid jitter) in order to satisfy the CPU frequency,
It optimizes the configuration depending the various divide stages,
Then, the PBA frequency is configured from the CPU freq.
Note that HSB and PBB are configured with the same frequency as CPU.
Note also that the number of wait states of the flash read accesses is automatically set-up depending the CPU frequency. As a consequence, the application needs the FLASHC driver to compile.
The CPU, HSB and PBA frequencies programmed after configuration are stored back into cpu_f and pba_f.
Parameters:
param pointer on the configuration structure.
Return values:
PM_FREQ_STATUS_OK Mode successfully initialized.
PM_FREQ_STATUS_FAIL The configuration can not be done.
Definition at line 60 of file pm_conf_clocks.c.
References pm_freq_param_t::cpu_f, flashc_issue_command(), flashc_set_wait_state(), pm_freq_param_t::osc0_f, pm_freq_param_t::osc0_startup, pm_freq_param_t::pba_f, pm_cksel(), PM_FREQ_STATUS_FAIL, PM_FREQ_STATUS_OK, PM_MAX_MUL, pm_pll_enable(), pm_pll_set_option(), pm_pll_setup(), pm_switch_to_clock(), pm_switch_to_osc0(), and pm_wait_for_pll0_locked().
Referenced by pcl_configure_clocks().
{
  // Supported frequencies:
  // Fosc0 mul div PLL div2_en cpu_f pba_f   Comment
  //  12   15   1  192     1     12    12
  //  12    9   3   40     1     20    20    PLL out of spec
  //  12   15   1  192     1     24    12
  //  12    9   1  120     1     30    15
  //  12    9   3   40     0     40    20    PLL out of spec
  //  12   15   1  192     1     48    12
  //  12   15   1  192     1     48    24
  //  12    8   1  108     1     54    27
  //  12    9   1  120     1     60    15
  //  12    9   1  120     1     60    30
  //  12   10   1  132     1     66    16.5
  //
  unsigned long in_cpu_f  = param->cpu_f;
  unsigned long in_osc0_f = param->osc0_f;
  unsigned long mul, div, div2_en = 0, div2_cpu = 0, div2_pba = 0;
  unsigned long pll_freq, rest;
  bool b_div2_pba, b_div2_cpu;
  // Switch to external Oscillator 0
  pm_switch_to_osc0(&AVR32_PM, in_osc0_f, param->osc0_startup);
  // Start with CPU freq config
  if (in_cpu_f == in_osc0_f)
  {
    param->cpu_f = in_osc0_f;
    param->pba_f = in_osc0_f;
    return PM_FREQ_STATUS_OK;
  }
  else if (in_cpu_f < in_osc0_f)
  {
    // TBD
  }
  rest = in_cpu_f % in_osc0_f;
  for (div = 1; div < 32; div++)
  {
    if ((div * rest) % in_osc0_f == 0)
      break;
  }
  if (div == 32)
    return PM_FREQ_STATUS_FAIL;
  mul = (in_cpu_f * div) / in_osc0_f;
  if (mul > PM_MAX_MUL)
    return PM_FREQ_STATUS_FAIL;
  // export 2power from PLL div to div2_cpu
  while (!(div % 2))
  {
    div /= 2;
    div2_cpu++;
  }
  // Here we know the mul and div parameter of the PLL config.
  // . Check out if the PLL has a valid in_cpu_f.
  // . Try to have for the PLL frequency (VCO output) the highest possible value
  //   to reduce jitter.
  while (in_osc0_f * 2 * mul / div < AVR32_PM_PLL_VCO_RANGE0_MAX_FREQ)
  {
    if (2 * mul > PM_MAX_MUL)
      break;
    mul *= 2;
    div2_cpu++;
  }
  if (div2_cpu != 0)
  {
    div2_cpu--;
    div2_en = 1;
  }
  pll_freq = in_osc0_f * mul / (div * (1 << div2_en));
  // Update real CPU Frequency
  param->cpu_f = pll_freq / (1 << div2_cpu);
  mul--;
  pm_pll_setup(&AVR32_PM
  , 0   // pll
  , mul // mul
  , div // div
  , 0   // osc
  , 16  // lockcount
  );
  pm_pll_set_option(&AVR32_PM
  , 0 // pll
  // PLL clock is lower than 160MHz: need to set pllopt.
  , (pll_freq < AVR32_PM_PLL_VCO_RANGE0_MIN_FREQ) ? 1 : 0 // pll_freq
  , div2_en // pll_div2
  , 0 // pll_wbwdisable
  );
  rest = pll_freq;
  while (rest > AVR32_PM_PBA_MAX_FREQ ||
         rest != param->pba_f)
  {
    div2_pba++;
    rest = pll_freq / (1 << div2_pba);
    if (rest < param->pba_f)
      break;
  }
  // Update real PBA Frequency
  param->pba_f = pll_freq / (1 << div2_pba);
  // Enable PLL0
  pm_pll_enable(&AVR32_PM, 0);
  // Wait for PLL0 locked
  pm_wait_for_pll0_locked(&AVR32_PM);
  if (div2_cpu)
  {
    b_div2_cpu = true;
    div2_cpu--;
  }
  else
    b_div2_cpu = false;
  if (div2_pba)
  {
    b_div2_pba = true;
    div2_pba--;
  }
  else
    b_div2_pba = false;
  pm_cksel(&AVR32_PM
  , b_div2_pba, div2_pba // PBA
  , b_div2_cpu, div2_cpu // PBB
  , b_div2_cpu, div2_cpu // HSB
  );
  if (param->cpu_f > AVR32_FLASHC_FWS_0_MAX_FREQ)
  {
    flashc_set_wait_state(1);
#if (defined AVR32_FLASHC_210_H_INCLUDED)
    if (param->cpu_f > AVR32_FLASHC_HSEN_FWS_1_MAX_FREQ)
      flashc_issue_command(AVR32_FLASHC_FCMD_CMD_HSEN, -1);
    else
      flashc_issue_command(AVR32_FLASHC_FCMD_CMD_HSDIS, -1);
#endif
  }
  else
  {
    flashc_set_wait_state(0);
#if (defined AVR32_FLASHC_210_H_INCLUDED)
    if (param->cpu_f > AVR32_FLASHC_HSEN_FWS_0_MAX_FREQ)
      flashc_issue_command(AVR32_FLASHC_FCMD_CMD_HSEN, -1);
    else
      flashc_issue_command(AVR32_FLASHC_FCMD_CMD_HSDIS, -1);
#endif
  }
  pm_switch_to_clock(&AVR32_PM, AVR32_PM_MCCTRL_MCSEL_PLL0);
  return PM_FREQ_STATUS_OK;
}
void pm_configure_usb_clock (void)
Automatically configure the USB clock.
USB clock is configured to 48MHz, using the PLL1 from the Oscillator0, assuming a 12 MHz crystal is connected to it.
Definition at line 227 of file pm_conf_clocks.c.
References pm_gc_enable(), pm_gc_setup(), pm_pll_enable(), pm_pll_set_option(), pm_pll_setup(), and pm_wait_for_pll1_locked().
Referenced by pcl_configure_usb_clock().
{
#if UC3A3
  // Setup USB GCLK.
  pm_gc_setup(&AVR32_PM, AVR32_PM_GCLK_USBB, // gc
                  0,                  // osc_or_pll: use Osc (if 0) or PLL (if 1)
                  0,                  // pll_osc: select Osc0/PLL0 or Osc1/PLL1
                  0,                  // diven
                  0);                 // div
  // Enable USB GCLK.
  pm_gc_enable(&AVR32_PM, AVR32_PM_GCLK_USBB);
#else
  // Use 12MHz from OSC0 and generate 96 MHz
  pm_pll_setup(&AVR32_PM, 1,  // pll.
      7,   // mul.
      1,   // div.
      0,   // osc.
      16); // lockcount.
  pm_pll_set_option(&AVR32_PM, 1, // pll.
      1,  // pll_freq: choose the range 80-180MHz.
      1,  // pll_div2.
      0); // pll_wbwdisable.
  // start PLL1 and wait forl lock
  pm_pll_enable(&AVR32_PM, 1);
  // Wait for PLL1 locked.
  pm_wait_for_pll1_locked(&AVR32_PM);
  pm_gc_setup(&AVR32_PM, AVR32_PM_GCLK_USBB,  // gc.
            1,  // osc_or_pll: use Osc (if 0) or PLL (if 1).
            1,  // pll_osc: select Osc0/PLL0 or Osc1/PLL1.
            0,  // diven.
            0); // div.
  pm_gc_enable(&AVR32_PM, AVR32_PM_GCLK_USBB);
#endif
}
void pm_disable_clk0 (volatile avr32_pm_t * pm)
This function will disable the oscillator 0.
Parameters:
pm Base address of the Power Manager (i.e. &AVR32_PM)
Definition at line 180 of file pm.c.
{
  pm->mcctrl &= ~AVR32_PM_MCCTRL_OSC0EN_MASK;
}
void pm_disable_clk1 (volatile avr32_pm_t * pm)
This function will disable the oscillator 1.
Parameters:
pm Base address of the Power Manager (i.e. &AVR32_PM)
Definition at line 243 of file pm.c.
{
  pm->mcctrl &= ~AVR32_PM_MCCTRL_OSC1EN_MASK;
}
void pm_disable_clk32 (volatile avr32_pm_t * pm)
This function will disable the oscillator 32.
Parameters:
pm Base address of the Power Manager (i.e. &AVR32_PM)
Definition at line 303 of file pm.c.
{
  pm->oscctrl32 &= ~AVR32_PM_OSCCTRL32_OSC32EN_MASK;
}
long pm_disable_module (volatile avr32_pm_t * pm, unsigned long module)
Disable the clock of a module.
Parameters:
pm Base address of the Power Manager (i.e. &AVR32_PM)
module The module to shut down (use one of the defines in the part-specific header file under "toolchain folder"/avr32/inc(lude)/avr32/; depending on the clock domain, look for the sections "CPU clocks", "HSB clocks", "PBx clocks")
Returns:
Status.
Return values:
0 Success.
<0 An error occured.
Definition at line 555 of file pm.c.
References PASS.
{
  unsigned long domain = module>>5;
  unsigned long *regptr = (unsigned long*)(&(pm->cpumask) + domain);
  // Implementation-specific shortcut: the ckMASK registers are contiguous and
  // memory-mapped in that order: CPUMASK, HSBMASK, PBAMASK, PBBMASK.
  *regptr &= ~(1<<(module%32));
  return PASS;
}
void pm_enable_clk0 (volatile avr32_pm_t * pm, unsigned int startup)
This function will enable the oscillator 0 to be used with a startup time.
Parameters:
pm Base address of the Power Manager (i.e. &AVR32_PM)
startup Clock 0 startup time. AVR32_PM_OSCCTRL0_STARTUP_x_RCOSC.
Definition at line 173 of file pm.c.
References pm_enable_clk0_no_wait(), and pm_wait_for_clk0_ready().
Referenced by pm_switch_to_osc0().
{
  pm_enable_clk0_no_wait(pm, startup);
  pm_wait_for_clk0_ready(pm);
}
void pm_enable_clk0_no_wait (volatile avr32_pm_t * pm, unsigned int startup)
This function will enable the oscillator 0 to be used with no startup time.
Parameters:
pm Base address of the Power Manager (i.e. &AVR32_PM)
startup Clock 0 startup time, for which the function does not wait. AVR32_PM_OSCCTRL0_STARTUP_x_RCOSC.
Definition at line 186 of file pm.c.
References u_avr32_pm_oscctrl0_t::OSCCTRL0, and u_avr32_pm_oscctrl0_t::oscctrl0.
Referenced by pm_enable_clk0().
{
  // Read register
  u_avr32_pm_oscctrl0_t u_avr32_pm_oscctrl0 = {pm->oscctrl0};
  // Modify
  u_avr32_pm_oscctrl0.OSCCTRL0.startup = startup;
  // Write back
  pm->oscctrl0 = u_avr32_pm_oscctrl0.oscctrl0;
  pm->mcctrl |= AVR32_PM_MCCTRL_OSC0EN_MASK;
}
void pm_enable_clk1 (volatile avr32_pm_t * pm, unsigned int startup)
This function will enable the oscillator 1 to be used with a startup time.
Parameters:
pm Base address of the Power Manager (i.e. &AVR32_PM)
startup Clock 1 startup time. AVR32_PM_OSCCTRL1_STARTUP_x_RCOSC.
Definition at line 236 of file pm.c.
References pm_enable_clk1_no_wait(), and pm_wait_for_clk1_ready().
{
  pm_enable_clk1_no_wait(pm, startup);
  pm_wait_for_clk1_ready(pm);
}
void pm_enable_clk1_no_wait (volatile avr32_pm_t * pm, unsigned int startup)
This function will enable the oscillator 1 to be used with no startup time.
Parameters:
pm Base address of the Power Manager (i.e. &AVR32_PM)
startup Clock 1 startup time, for which the function does not wait. AVR32_PM_OSCCTRL1_STARTUP_x_RCOSC.
Definition at line 249 of file pm.c.
References u_avr32_pm_oscctrl1_t::OSCCTRL1, and u_avr32_pm_oscctrl1_t::oscctrl1.
Referenced by pm_enable_clk1().
{
  // Read register
  u_avr32_pm_oscctrl1_t u_avr32_pm_oscctrl1 = {pm->oscctrl1};
  // Modify
  u_avr32_pm_oscctrl1.OSCCTRL1.startup = startup;
  // Write back
  pm->oscctrl1 = u_avr32_pm_oscctrl1.oscctrl1;
  pm->mcctrl |= AVR32_PM_MCCTRL_OSC1EN_MASK;
}
void pm_enable_clk32 (volatile avr32_pm_t * pm, unsigned int startup)
This function will enable the oscillator 32 to be used with a startup time.
Parameters:
pm Base address of the Power Manager (i.e. &AVR32_PM)
startup Clock 32 kHz startup time. AVR32_PM_OSCCTRL32_STARTUP_x_RCOSC.
Definition at line 296 of file pm.c.
References pm_enable_clk32_no_wait(), and pm_wait_for_clk32_ready().
Referenced by rtc_init().
{
  pm_enable_clk32_no_wait(pm, startup);
  pm_wait_for_clk32_ready(pm);
}
void pm_enable_clk32_no_wait (volatile avr32_pm_t * pm, unsigned int startup)
This function will enable the oscillator 32 to be used with no startup time.
Parameters:
pm Base address of the Power Manager (i.e. &AVR32_PM)
startup Clock 32 kHz startup time, for which the function does not wait. AVR32_PM_OSCCTRL32_STARTUP_x_RCOSC.
Definition at line 309 of file pm.c.
References u_avr32_pm_oscctrl32_t::OSCCTRL32, and u_avr32_pm_oscctrl32_t::oscctrl32.
Referenced by pm_enable_clk32().
{
  // Read register
  u_avr32_pm_oscctrl32_t u_avr32_pm_oscctrl32 = {pm->oscctrl32};
  // Modify
  u_avr32_pm_oscctrl32.OSCCTRL32.osc32en = 1;
  u_avr32_pm_oscctrl32.OSCCTRL32.startup = startup;
  // Write back
  pm->oscctrl32 = u_avr32_pm_oscctrl32.oscctrl32;
}
long pm_enable_module (volatile avr32_pm_t * pm, unsigned long module)
Enable the clock of a module.
Parameters:
pm Base address of the Power Manager (i.e. &AVR32_PM)
module The module to clock (use one of the defines in the part-specific header file under "toolchain folder"/avr32/inc(lude)/avr32/; depending on the clock domain, look for the sections "CPU clocks", "HSB clocks", "PBx clocks")
Returns:
Status.
Return values:
0 Success.
<0 An error occured.
Definition at line 542 of file pm.c.
References PASS.
{
  unsigned long domain = module>>5;
  unsigned long *regptr = (unsigned long*)(&(pm->cpumask) + domain);
  // Implementation-specific shortcut: the ckMASK registers are contiguous and
  // memory-mapped in that order: CPUMASK, HSBMASK, PBAMASK, PBBMASK.
  *regptr |= (1<<(module%32));
  return PASS;
}
void pm_enable_osc0_crystal (volatile avr32_pm_t * pm, unsigned int fosc0)
This function will enable the crystal mode of the oscillator 0.
Parameters:
pm Base address of the Power Manager (i.e. &AVR32_PM)
fosc0 Oscillator 0 crystal frequency (Hz)
Definition at line 164 of file pm.c.
References pm_set_osc0_mode().
Referenced by pm_switch_to_osc0().
{
  pm_set_osc0_mode(pm, (fosc0 <  900000) ? AVR32_PM_OSCCTRL0_MODE_CRYSTAL_G0 :
                       (fosc0 < 3000000) ? AVR32_PM_OSCCTRL0_MODE_CRYSTAL_G1 :
                       (fosc0 < 8000000) ? AVR32_PM_OSCCTRL0_MODE_CRYSTAL_G2 :
                                           AVR32_PM_OSCCTRL0_MODE_CRYSTAL_G3);
}
void pm_enable_osc0_ext_clock (volatile avr32_pm_t * pm)
This function will enable the external clock mode of the oscillator 0.
Parameters:
pm Base address of the Power Manager (i.e. &AVR32_PM)
Definition at line 158 of file pm.c.
References pm_set_osc0_mode().
{
  pm_set_osc0_mode(pm, AVR32_PM_OSCCTRL0_MODE_EXT_CLOCK);
}
void pm_enable_osc1_crystal (volatile avr32_pm_t * pm, unsigned int fosc1)
This function will enable the crystal mode of the oscillator 1.
Parameters:
pm Base address of the Power Manager (i.e. &AVR32_PM)
fosc1 Oscillator 1 crystal frequency (Hz)
Definition at line 227 of file pm.c.
References pm_set_osc1_mode().
{
  pm_set_osc1_mode(pm, (fosc1 <  900000) ? AVR32_PM_OSCCTRL1_MODE_CRYSTAL_G0 :
                       (fosc1 < 3000000) ? AVR32_PM_OSCCTRL1_MODE_CRYSTAL_G1 :
                       (fosc1 < 8000000) ? AVR32_PM_OSCCTRL1_MODE_CRYSTAL_G2 :
                                           AVR32_PM_OSCCTRL1_MODE_CRYSTAL_G3);
}
void pm_enable_osc1_ext_clock (volatile avr32_pm_t * pm)
This function will enable the external clock mode of the oscillator 1.
Parameters:
pm Base address of the Power Manager (i.e. &AVR32_PM)
Definition at line 221 of file pm.c.
References pm_set_osc1_mode().
{
  pm_set_osc1_mode(pm, AVR32_PM_OSCCTRL1_MODE_EXT_CLOCK);
}
void pm_enable_osc32_crystal (volatile avr32_pm_t * pm)
This function will enable the crystal mode of the 32-kHz oscillator.
Parameters:
pm Base address of the Power Manager (i.e. &AVR32_PM)
Definition at line 290 of file pm.c.
References pm_set_osc32_mode().
Referenced by rtc_init().
{
  pm_set_osc32_mode(pm, AVR32_PM_OSCCTRL32_MODE_CRYSTAL);
}
void pm_enable_osc32_ext_clock (volatile avr32_pm_t * pm)
This function will enable the external clock mode of the 32-kHz oscillator.
Parameters:
pm Base address of the Power Manager (i.e. &AVR32_PM)
Definition at line 284 of file pm.c.
References pm_set_osc32_mode().
{
  pm_set_osc32_mode(pm, AVR32_PM_OSCCTRL32_MODE_EXT_CLOCK);
}
void pm_gc_disable (volatile avr32_pm_t * pm, unsigned int gc)
This function will disable a generic clock.
Parameters:
pm Base address of the Power Manager (i.e. &AVR32_PM)
gc generic clock number (0 for gc0...)
Definition at line 393 of file pm.c.
{
  pm->gcctrl[gc] &= ~AVR32_PM_GCCTRL_CEN_MASK;
}
void pm_gc_enable (volatile avr32_pm_t * pm, unsigned int gc)
This function will enable a generic clock.
Parameters:
pm Base address of the Power Manager (i.e. &AVR32_PM)
gc generic clock number (0 for gc0...)
Definition at line 386 of file pm.c.
Referenced by pm_configure_usb_clock().
{
  pm->gcctrl[gc] |= AVR32_PM_GCCTRL_CEN_MASK;
}
void pm_gc_setup (volatile avr32_pm_t * pm, unsigned int gc, unsigned int osc_or_pll, unsigned int pll_osc, unsigned int diven, unsigned int div)
This function will setup a generic clock.
Parameters:
pm Base address of the Power Manager (i.e. &AVR32_PM)
gc generic clock number (0 for gc0...)
osc_or_pll Use OSC (=0) or PLL (=1)
pll_osc Select Osc0/PLL0 or Osc1/PLL1
diven Generic clock divisor enable
div Generic clock divisor
Definition at line 368 of file pm.c.
References u_avr32_pm_gcctrl_t::gcctrl, and u_avr32_pm_gcctrl_t::GCCTRL.
Referenced by pm_configure_usb_clock().
{
  u_avr32_pm_gcctrl_t u_avr32_pm_gcctrl = {0};
  u_avr32_pm_gcctrl.GCCTRL.oscsel = pll_osc;
  u_avr32_pm_gcctrl.GCCTRL.pllsel = osc_or_pll;
  u_avr32_pm_gcctrl.GCCTRL.diven  = diven;
  u_avr32_pm_gcctrl.GCCTRL.div    = div;
  pm->gcctrl[gc] = u_avr32_pm_gcctrl.gcctrl;
}
unsigned long pm_get_clock (volatile avr32_pm_t * pm)
This function returns the power manager main clock.
Parameters:
pm Base address of the Power Manager (i.e. &AVR32_PM)
Return values:
The main clock value.
Definition at line 463 of file pm.c.
References u_avr32_pm_mcctrl_t::MCCTRL, and u_avr32_pm_mcctrl_t::mcctrl.
{
  u_avr32_pm_mcctrl_t u_avr32_pm_mcctrl = {pm->mcctrl};
  return u_avr32_pm_mcctrl.MCCTRL.mcsel;
}
static unsigned int pm_get_reset_cause (volatile avr32_pm_t * pm) [inline, static]
Gets the MCU reset cause.
Parameters:
pm Base address of the Power Manager instance (i.e. &AVR32_PM).
Returns:
The MCU reset cause which can be masked with the AVR32_PM_RCAUSE_x_MASK bit-masks to isolate specific causes.
Definition at line 140 of file pm.h.
{
  return pm->rcause;
}
void pm_pll_disable (volatile avr32_pm_t * pm, unsigned int pll)
This function will disable a PLL.
Parameters:
pm Base address of the Power Manager (i.e. &AVR32_PM)
pll PLL number(0 for PLL0, 1 for PLL1)
Definition at line 444 of file pm.c.
{
  pm->pll[pll] &= ~AVR32_PM_PLLEN_MASK;
}
void pm_pll_enable (volatile avr32_pm_t * pm, unsigned int pll)
This function will enable a PLL.
Parameters:
pm Base address of the Power Manager (i.e. &AVR32_PM)
pll PLL number(0 for PLL0, 1 for PLL1)
Definition at line 437 of file pm.c.
Referenced by pm_configure_clocks(), and pm_configure_usb_clock().
{
  pm->pll[pll] |= AVR32_PM_PLLEN_MASK;
}
unsigned int pm_pll_get_option (volatile avr32_pm_t * pm, unsigned int pll)
This function will get a PLL option.
Parameters:
pm Base address of the Power Manager (i.e. &AVR32_PM)
pll PLL number(0 for PLL0, 1 for PLL1)
Returns:
Option
Definition at line 430 of file pm.c.
{
  return (pm->pll[pll] & AVR32_PM_PLLOPT_MASK) >> AVR32_PM_PLLOPT_OFFSET;
}
void pm_pll_set_option (volatile avr32_pm_t * pm, unsigned int pll, unsigned int pll_freq, unsigned int pll_div2, unsigned int pll_wbwdisable)
This function will set a PLL option.
Parameters:
pm Base address of the Power Manager (i.e. &AVR32_PM)
pll PLL number(0 for PLL0, 1 for PLL1)
pll_freq Set to 1 for VCO frequency range 80-180MHz, set to 0 for VCO frequency range 160-240Mhz.
pll_div2 Divide the PLL output frequency by 2 (this settings does not change the FVCO value)
pll_wbwdisable 1 Disable the Wide-Bandith Mode (Wide-Bandwith mode allow a faster startup time and out-of-lock time). 0 to enable the Wide-Bandith Mode.
Definition at line 418 of file pm.c.
References u_avr32_pm_pll_t::PLL, and u_avr32_pm_pll_t::pll.
Referenced by pm_configure_clocks(), and pm_configure_usb_clock().
{
  u_avr32_pm_pll_t u_avr32_pm_pll = {pm->pll[pll]};
  u_avr32_pm_pll.PLL.pllopt = pll_freq | (pll_div2 << 1) | (pll_wbwdisable << 2);
  pm->pll[pll] = u_avr32_pm_pll.pll;
}
void pm_pll_setup (volatile avr32_pm_t * pm, unsigned int pll, unsigned int mul, unsigned int div, unsigned int osc, unsigned int lockcount)
This function will setup a PLL.
Parameters:
pm Base address of the Power Manager (i.e. &AVR32_PM)
pll PLL number(0 for PLL0, 1 for PLL1)
mul PLL MUL in the PLL formula
div PLL DIV in the PLL formula
osc OSC number (0 for osc0, 1 for osc1)
lockcount PLL lockount
Definition at line 400 of file pm.c.
References u_avr32_pm_pll_t::pll, and u_avr32_pm_pll_t::PLL.
Referenced by pm_configure_clocks(), and pm_configure_usb_clock().
{
  u_avr32_pm_pll_t u_avr32_pm_pll = {0};
  u_avr32_pm_pll.PLL.pllosc   = osc;
  u_avr32_pm_pll.PLL.plldiv   = div;
  u_avr32_pm_pll.PLL.pllmul   = mul;
  u_avr32_pm_pll.PLL.pllcount = lockcount;
  pm->pll[pll] = u_avr32_pm_pll.pll;
}
unsigned long pm_read_gplp (volatile avr32_pm_t * pm, unsigned long gplp)
Read the content of the PM GPLP registers.
Parameters:
pm Base address of the Power Manager (i.e. &AVR32_PM)
gplp GPLP register index (0,1,... depending on the number of GPLP registers for a given part)
Returns:
The content of the chosen GPLP register.
Definition at line 530 of file pm.c.
{
  return pm->gplp[gplp];
}
void pm_switch_to_clock (volatile avr32_pm_t * pm, unsigned long clock)
This function will switch the power manager main clock.
Parameters:
pm Base address of the Power Manager (i.e. &AVR32_PM)
clock Clock to be switched on. AVR32_PM_MCSEL_SLOW for RCOsc, AVR32_PM_MCSEL_OSC0 for Osc0, AVR32_PM_MCSEL_PLL0 for PLL0.
Definition at line 470 of file pm.c.
References u_avr32_pm_mcctrl_t::MCCTRL, and u_avr32_pm_mcctrl_t::mcctrl.
Referenced by pm_configure_clocks(), and pm_switch_to_osc0().
{
  // Read
  u_avr32_pm_mcctrl_t u_avr32_pm_mcctrl = {pm->mcctrl};
  // Modify
  u_avr32_pm_mcctrl.MCCTRL.mcsel = clock;
  // Write back
  pm->mcctrl = u_avr32_pm_mcctrl.mcctrl;
}
void pm_switch_to_osc0 (volatile avr32_pm_t * pm, unsigned int fosc0, unsigned int startup)
Switch main clock to clock Osc0 (crystal mode)
Parameters:
pm Base address of the Power Manager (i.e. &AVR32_PM)
fosc0 Oscillator 0 crystal frequency (Hz)
startup Crystal 0 startup time. AVR32_PM_OSCCTRL0_STARTUP_x_RCOSC.
Definition at line 481 of file pm.c.
References pm_enable_clk0(), pm_enable_osc0_crystal(), and pm_switch_to_clock().
Referenced by main(), pcl_switch_to_osc(), and pm_configure_clocks().
{
  pm_enable_osc0_crystal(pm, fosc0);            // Enable the Osc0 in crystal mode
  pm_enable_clk0(pm, startup);                  // Crystal startup time - This parameter is critical and depends on the characteristics of the crystal
  pm_switch_to_clock(pm, AVR32_PM_MCSEL_OSC0);  // Then switch main clock to Osc0
}
void pm_wait_for_clk0_ready (volatile avr32_pm_t * pm)
This function will wait until the Osc0 clock is ready.
Parameters:
pm Base address of the Power Manager (i.e. &AVR32_PM)
Definition at line 199 of file pm.c.
Referenced by pm_enable_clk0().
{
  while (!(pm->poscsr & AVR32_PM_POSCSR_OSC0RDY_MASK));
}
void pm_wait_for_clk1_ready (volatile avr32_pm_t * pm)
This function will wait until the Osc1 clock is ready.
Parameters:
pm Base address of the Power Manager (i.e. &AVR32_PM)
Definition at line 262 of file pm.c.
Referenced by pm_enable_clk1().
{
  while (!(pm->poscsr & AVR32_PM_POSCSR_OSC1RDY_MASK));
}
void pm_wait_for_clk32_ready (volatile avr32_pm_t * pm)
This function will wait until the osc32 clock is ready.
Parameters:
pm Base address of the Power Manager (i.e. &AVR32_PM)
Definition at line 321 of file pm.c.
Referenced by pm_enable_clk32().
{
  while (!(pm->poscsr & AVR32_PM_POSCSR_OSC32RDY_MASK));
}
void pm_wait_for_pll0_locked (volatile avr32_pm_t * pm)
This function will wait for PLL0 locked.
Parameters:
pm Base address of the Power Manager (i.e. &AVR32_PM)
Definition at line 451 of file pm.c.
Referenced by pm_configure_clocks().
{
  while (!(pm->poscsr & AVR32_PM_POSCSR_LOCK0_MASK));
}
void pm_wait_for_pll1_locked (volatile avr32_pm_t * pm)
This function will wait for PLL1 locked.
Parameters:
pm Base address of the Power Manager (i.e. &AVR32_PM)
Definition at line 457 of file pm.c.
Referenced by pm_configure_usb_clock().
{
  while (!(pm->poscsr & AVR32_PM_POSCSR_LOCK1_MASK));
}
void pm_write_gplp (volatile avr32_pm_t * pm, unsigned long gplp, unsigned long value)
Write into the PM GPLP registers.
Parameters:
pm Base address of the Power Manager (i.e. &AVR32_PM)
gplp GPLP register index (0,1,... depending on the number of GPLP registers for a given part)
value Value to write
Definition at line 536 of file pm.c.
{
  pm->gplp[gplp] = value;
}