OS: Power Clocks Library
Power Clocks Library
CPU - PM - Power Manager
Clocks Management
enum pcl_osc_t {
PCL_OSC0 = 0,
PCL_OSC1 = 1
}
The different oscillators.
enum pcl_dfll_t {
PCL_DFLL0 = 0,
PCL_DFLL1 = 1
}
The different DFLLs.
enum pcl_mainclk_t {
PCL_MC_RCSYS,
PCL_MC_OSC0,
PCL_MC_OSC1,
PCL_MC_OSC0_PLL0,
PCL_MC_OSC1_PLL0,
PCL_MC_OSC0_PLL1,
PCL_MC_OSC1_PLL1,
PCL_MC_DFLL0,
PCL_MC_DFLL1,
PCL_MC_RC120M,
PCL_MC_RC8M,
PCL_MC_CRIPOSC
}
Possible Main Clock Sources.
long int pcl_configure_clocks (pcl_freq_param_t *param)
Automatically configure the CPU, PBA, PBB, and HSB clocks.
long int pcl_configure_clocks_rcsys (pcl_freq_param_t *param)
Automatically configure the CPU, PBA, PBB, and HSB clocks using the RCSYS osc as main source clock.
long int pcl_configure_clocks_rc120m (pcl_freq_param_t *param)
Automatically configure the CPU, PBA, PBB, and HSB clocks using the RC120M osc as main source clock.
long int pcl_configure_clocks_osc0 (pcl_freq_param_t *param)
Automatically configure the CPU, PBA, PBB, and HSB clocks using the OSC0 osc as main source clock.
long int pcl_configure_clocks_dfll0 (pcl_freq_param_t *param)
Automatically configure the CPU, PBA, PBB, and HSB clocks using the DFLL0 as main source clock.
long int pcl_switch_to_osc (pcl_osc_t osc, unsigned int fcrystal, unsigned int startup)
Switch the main clock source to Osc0 configured in crystal mode.
long int pcl_configure_usb_clock (void)
Configure the USB Clock.
#define pcl_freq_param_t pm_freq_param_t
Input and output parameters to configure clocks with pcl_configure_clocks().
#define PCL_NOT_SUPPORTED (-10000)
Define "not supported" for the lib.
#define pcl_enable_module(module) pm_enable_module(&AVR32_PM, module)
Enable the clock of a module.
#define pcl_disable_module(module) pm_disable_module(&AVR32_PM, module)
Disable the clock of a module.
Power Management
unsigned long pcl_read_gplp (unsigned long gplp)
Read the content of the GPLP registers.
void pcl_write_gplp (unsigned long gplp, unsigned long value)
Write into the GPLP registers.
Define Documentation
#define pcl_disable_module (module) pm_disable_module(&AVR32_PM, module)
Disable the clock of a module.
Parameters:
module The module to shut down (use one of the defines in the part-specific header file under "toolchain folder"/avr32/inc(lude)/avr32/; depending on the clock domain, look for the sections "CPU clocks", "HSB clocks", "PBx clocks" or look in the module section).
Returns:
Status.
Return values:
0 Success.
<0 An error occured.
Definition at line 346 of file power_clocks_lib.h.
#define pcl_enable_module (module) pm_enable_module(&AVR32_PM, module)
Enable the clock of a module.
Parameters:
module The module to clock (use one of the defines in the part-specific header file under "toolchain folder"/avr32/inc(lude)/avr32/; depending on the clock domain, look for the sections "CPU clocks", "HSB clocks", "PBx clocks" or look in the module section).
Returns:
Status.
Return values:
0 Success.
<0 An error occured.
Definition at line 327 of file power_clocks_lib.h.
#define pcl_freq_param_t pm_freq_param_t
Input and output parameters to configure clocks with pcl_configure_clocks().
Definition at line 125 of file power_clocks_lib.h.
#define PCL_NOT_SUPPORTED (-10000)
Define "not supported" for the lib.
Definition at line 162 of file power_clocks_lib.h.
Referenced by pcl_configure_usb_clock(), and pcl_switch_to_osc().
Enumeration Type Documentation
enum pcl_dfll_t
The different DFLLs.
Enumerator:
PCL_DFLL0
PCL_DFLL1
Definition at line 98 of file power_clocks_lib.h.
{
  PCL_DFLL0  = 0,
  PCL_DFLL1  = 1
} pcl_dfll_t;
enum pcl_mainclk_t
Possible Main Clock Sources.
Enumerator:
PCL_MC_RCSYS
PCL_MC_OSC0
PCL_MC_OSC1
PCL_MC_OSC0_PLL0
PCL_MC_OSC1_PLL0
PCL_MC_OSC0_PLL1
PCL_MC_OSC1_PLL1
PCL_MC_DFLL0
PCL_MC_DFLL1
PCL_MC_RC120M
PCL_MC_RC8M
PCL_MC_CRIPOSC
Definition at line 105 of file power_clocks_lib.h.
{
  PCL_MC_RCSYS,      // Default main clock source, supported by all (aka Slow Clock)
  PCL_MC_OSC0,       // Supported by all
  PCL_MC_OSC1,       // Supported by UC3C only
  PCL_MC_OSC0_PLL0,  // Supported by UC3A, UC3B, UC3A3, UC3C (the main clock source is PLL0 with OSC0 as reference)
  PCL_MC_OSC1_PLL0,  // Supported by UC3A, UC3B, UC3A3, UC3C (the main clock source is PLL0 with OSC1 as reference)
  PCL_MC_OSC0_PLL1,  // Supported by UC3C  (the main clock source is PLL1 with OSC0 as reference)
  PCL_MC_OSC1_PLL1,  // Supported by UC3C  (the main clock source is PLL1 with OSC1 as reference)
  PCL_MC_DFLL0,      // Supported by UC3L
  PCL_MC_DFLL1,      // Not supported yet
  PCL_MC_RC120M,     // Supported by UC3L, UC3C
  PCL_MC_RC8M,       // Supported by UC3C
  PCL_MC_CRIPOSC     // Supported by UC3C
} pcl_mainclk_t;
enum pcl_osc_t
The different oscillators.
Enumerator:
PCL_OSC0
PCL_OSC1
Definition at line 91 of file power_clocks_lib.h.
{
  PCL_OSC0  = 0,
  PCL_OSC1  = 1
} pcl_osc_t;
Function Documentation
long int pcl_configure_clocks (pcl_freq_param_t * param)
Automatically configure the CPU, PBA, PBB, and HSB clocks.
This function needs some parameters stored in a pcl_freq_param_t structure:
main_clk_src is the id of the main clock source to use,
cpu_f and pba_f and pbb_f are the wanted frequencies,
osc0_f is the oscillator 0's external crystal (or external clock) on-board frequency (e.g. FOSC0),
osc0_startup is the oscillator 0's external crystal (or external clock) startup time (e.g. OSC0_STARTUP).
dfll_f is the target DFLL frequency to set-up if main_clk_src is the dfll.
The CPU, HSB and PBA frequencies programmed after configuration are stored back into cpu_f and pba_f.
Note:
: since it is dynamically computing the appropriate field values of the configuration registers from the parameters structure, this function is not optimal in terms of code size. For a code size optimal solution, it is better to create a new function from pcl_configure_clocks() and modify it to use preprocessor computation from pre-defined target frequencies.
Parameters:
param pointer on the configuration structure.
Return values:
0 Success.
<0 The configuration cannot be performed.
Definition at line 60 of file power_clocks_lib.c.
References pcl_configure_clocks_uc3l(), and pm_configure_clocks().
{
#ifndef AVR32_PM_VERSION_RESETVALUE
  // Implementation for UC3A, UC3A3, UC3B parts.
  return(pm_configure_clocks(param));
#else
  #if (defined AVR32_PM_410_H_INCLUDED ) || (defined AVR32_PM_412_H_INCLUDED )
    // Implementation for UC3C parts.
    return(pcl_configure_clocks_uc3c(param));
  #else
    // Implementation for UC3L parts.
    return(pcl_configure_clocks_uc3l(param));
  #endif
#endif
}
long int pcl_configure_clocks_dfll0 (pcl_freq_param_t * param)
Automatically configure the CPU, PBA, PBB, and HSB clocks using the DFLL0 as main source clock.
This function needs some parameters stored in a pcl_freq_param_t structure:
cpu_f and pba_f and pbb_f are the wanted frequencies,
dfll_f is the target DFLL frequency to set-up
Note:
: when the DFLL0 is to be used as main source clock for the synchronous clocks, the target frequency of the DFLL should be chosen to be as high as possible within the specification range (for stability reasons); the target cpu and pbx frequencies will then be reached by appropriate division ratio.
Supported main clock sources: PCL_MC_DFLL0
Supported synchronous clocks frequencies: (these obviously depend on the DFLL target frequency; we'll take 100MHz as an example) 50MHz, 25MHz, 12.5MHz, 6.25MHz, 3.125MHz, 1562.5kHz, 781.25kHz, 390.625kHz.
Note:
: by default, this implementation doesn't perform thorough checks on the input parameters. To enable the checks, define AVR32SFW_INPUT_CHECK.
: since it is dynamically computing the appropriate field values of the configuration registers from the parameters structure, this function is not optimal in terms of code size. For a code size optimal solution, it is better to create a new function from pcl_configure_clocks_dfll0() and modify it to use preprocessor computation from pre-defined target frequencies.
Parameters:
param pointer on the configuration structure.
Return values:
0 Success.
<0 The configuration cannot be performed.
Definition at line 177 of file power_clocks_lib.c.
References pcl_configure_synchronous_clocks().
Referenced by pcl_configure_clocks_uc3l().
{
  // Supported main clock sources: PCL_MC_DFLL
  // Supported synchronous clocks frequencies if DFLL is the main clock source:
  // (these obviously depend on the DFLL target frequency; we'll take 100MHz as an example)
  // 50MHz, 25MHz, 12.5MHz, 6.25MHz, 3.125MHz, 1562.5kHz, 781.25kHz, 390.625kHz.
  // NOTE: by default, this implementation doesn't perform thorough checks on the
  // input parameters. To enable the checks, define AVR32SFW_INPUT_CHECK.
  unsigned long   main_clock_freq;
  scif_gclk_opt_t *pgc_dfllif_ref_opt;
#ifdef AVR32SFW_INPUT_CHECK
  // Verify that fCPU >= fPBx
  if((param->cpu_f < param->pba_f) || (param->cpu_f < param->pbb_f))
    return(-1);
#endif
  main_clock_freq = param->dfll_f;
#ifdef AVR32SFW_INPUT_CHECK
  // Verify that the target DFLL output frequency is in the correct range.
  if((main_clock_freq > SCIF_DFLL_MAXFREQ_HZ) || (main_clock_freq < SCIF_DFLL_MINFREQ_HZ))
    return(-1);
  // Verify that the target frequencies are reachable.
  if((param->cpu_f > main_clock_freq) || (param->pba_f > main_clock_freq)
    || (param->pbb_f > main_clock_freq))
    return(-1);
#endif
  pgc_dfllif_ref_opt = (scif_gclk_opt_t *)param->pextra_params;
  // Implementation note: this implementation configures the DFLL in closed-loop
  // mode (because it gives the best accuracy) which enables the generic clock CLK_DFLLIF_REF
  // as a reference (RCSYS being used as the generic clock source, undivided).
  scif_dfll0_closedloop_configure_and_start(pgc_dfllif_ref_opt, main_clock_freq, true);
  return(pcl_configure_synchronous_clocks(PM_CLK_SRC_DFLL0, main_clock_freq, param));
}
long int pcl_configure_clocks_osc0 (pcl_freq_param_t * param)
Automatically configure the CPU, PBA, PBB, and HSB clocks using the OSC0 osc as main source clock.
This function needs some parameters stored in a pcl_freq_param_t structure:
cpu_f and pba_f and pbb_f are the wanted frequencies,
osc0_f is the oscillator 0's external crystal (or external clock) on-board frequency (e.g. FOSC0),
osc0_startup is the oscillator 0's external crystal (or external clock) startup time (e.g. OSC0_STARTUP).
Supported main clock sources: PCL_MC_OSC0
Supported synchronous clocks frequencies: (these obviously depend on the OSC0 frequency; we'll take 16MHz as an example) 16MHz, 8MHz, 4MHz, 2MHz, 1MHz, 500kHz, 250kHz, 125kHz, 62.5kHz.
Note:
: by default, this implementation doesn't perform thorough checks on the input parameters. To enable the checks, define AVR32SFW_INPUT_CHECK.
: since it is dynamically computing the appropriate field values of the configuration registers from the parameters structure, this function is not optimal in terms of code size. For a code size optimal solution, it is better to create a new function from pcl_configure_clocks_osc0() and modify it to use preprocessor computation from pre-defined target frequencies.
Parameters:
param pointer on the configuration structure.
Return values:
0 Success.
<0 The configuration cannot be performed.
Definition at line 141 of file power_clocks_lib.c.
References pcl_configure_synchronous_clocks().
Referenced by pcl_configure_clocks_uc3l().
{
  // Supported main clock sources: PCL_MC_OSC0
  // Supported synchronous clocks frequencies if OSC0 is the main clock source:
  // (these obviously depend on the OSC0 frequency; we'll take 16MHz as an example)
  // 16MHz, 8MHz, 4MHz, 2MHz, 1MHz, 500kHz, 250kHz, 125kHz, 62.5kHz.
  // NOTE: by default, this implementation doesn't perform thorough checks on the
  // input parameters. To enable the checks, define AVR32SFW_INPUT_CHECK.
  unsigned long               main_clock_freq;
#ifdef AVR32SFW_INPUT_CHECK
  // Verify that fCPU >= fPBx
  if((param->cpu_f < param->pba_f) || (param->cpu_f < param->pbb_f))
    return(-1);
#endif
  main_clock_freq = param->osc0_f;
#ifdef AVR32SFW_INPUT_CHECK
  // Verify that the target frequencies are reachable.
  if((param->cpu_f > main_clock_freq) || (param->pba_f > main_clock_freq)
    || (param->pbb_f > main_clock_freq))
    return(-1);
#endif
  // Configure OSC0 in crystal mode, external crystal with a fcrystal Hz frequency.
  scif_configure_osc_crystalmode(SCIF_OSC0, main_clock_freq);
  // Enable the OSC0
  scif_enable_osc(SCIF_OSC0, param->osc0_startup, true);
  return(pcl_configure_synchronous_clocks(PM_CLK_SRC_OSC0, main_clock_freq, param));
}
long int pcl_configure_clocks_rc120m (pcl_freq_param_t * param)
Automatically configure the CPU, PBA, PBB, and HSB clocks using the RC120M osc as main source clock.
This function needs some parameters stored in a pcl_freq_param_t structure:
cpu_f and pba_f and pbb_f are the wanted frequencies
Supported main clock sources: PCL_MC_RC120M
Supported synchronous clocks frequencies: 30MHz, 15MHz, 7.5MHz, 3.75MHz, 1.875MHz, 937.5kHz, 468.75kHz.
Note:
: by default, this implementation doesn't perform thorough checks on the input parameters. To enable the checks, define AVR32SFW_INPUT_CHECK.
: since it is dynamically computing the appropriate field values of the configuration registers from the parameters structure, this function is not optimal in terms of code size. For a code size optimal solution, it is better to create a new function from pcl_configure_clocks_rc120m() and modify it to use preprocessor computation from pre-defined target frequencies.
Parameters:
param pointer on the configuration structure.
Return values:
0 Success.
<0 The configuration cannot be performed.
Definition at line 111 of file power_clocks_lib.c.
References pcl_configure_synchronous_clocks().
Referenced by pcl_configure_clocks_uc3l().
{
  // Supported main clock sources: PCL_MC_RC120M
  // Supported synchronous clocks frequencies if RC120M is the main clock source:
  // 30MHz, 15MHz, 7.5MHz, 3.75MHz, 1.875MHz, 937.5kHz, 468.75kHz.
  // NOTE: by default, this implementation doesn't perform thorough checks on the
  // input parameters. To enable the checks, define AVR32SFW_INPUT_CHECK.
#ifdef AVR32SFW_INPUT_CHECK
  // Verify that fCPU >= fPBx
  if((param->cpu_f < param->pba_f) || (param->cpu_f < param->pbb_f))
    return(-1);
#endif
#ifdef AVR32SFW_INPUT_CHECK
  // Verify that the target frequencies are reachable.
  if((param->cpu_f > SCIF_RC120M_FREQ_HZ) || (param->pba_f > SCIF_RC120M_FREQ_HZ)
    || (param->pbb_f > SCIF_RC120M_FREQ_HZ))
    return(-1);
#endif
  // Start the 120MHz internal RCosc (RC120M) clock
  scif_start_rc120M();
  return(pcl_configure_synchronous_clocks(PM_CLK_SRC_RC120M, SCIF_RC120M_FREQ_HZ, param));
}
long int pcl_configure_clocks_rcsys (pcl_freq_param_t * param)
Automatically configure the CPU, PBA, PBB, and HSB clocks using the RCSYS osc as main source clock.
This function needs some parameters stored in a pcl_freq_param_t structure:
cpu_f and pba_f and pbb_f are the wanted frequencies
Supported main clock sources: PCL_MC_RCSYS
Supported synchronous clocks frequencies: 115200Hz, 57600Hz, 28800Hz, 14400Hz, 7200Hz, 3600Hz, 1800Hz, 900Hz, 450Hz.
Note:
: by default, this implementation doesn't perform thorough checks on the input parameters. To enable the checks, define AVR32SFW_INPUT_CHECK.
: since it is dynamically computing the appropriate field values of the configuration registers from the parameters structure, this function is not optimal in terms of code size. For a code size optimal solution, it is better to create a new function from pcl_configure_clocks_rcsys() and modify it to use preprocessor computation from pre-defined target frequencies.
Parameters:
param pointer on the configuration structure.
Return values:
0 Success.
<0 The configuration cannot be performed.
Definition at line 84 of file power_clocks_lib.c.
References pcl_configure_synchronous_clocks().
Referenced by pcl_configure_clocks_uc3l().
{
  // Supported main clock sources: PCL_MC_RCSYS
  // Supported synchronous clocks frequencies if RCSYS is the main clock source:
  // 115200Hz, 57600Hz, 28800Hz, 14400Hz, 7200Hz, 3600Hz, 1800Hz, 900Hz, 450Hz.
  // NOTE: by default, this implementation doesn't perform thorough checks on the
  // input parameters. To enable the checks, define AVR32SFW_INPUT_CHECK.
#ifdef AVR32SFW_INPUT_CHECK
  // Verify that fCPU >= fPBx
  if((param->cpu_f < param->pba_f) || (param->cpu_f < param->pbb_f))
    return(-1);
#endif
#ifdef AVR32SFW_INPUT_CHECK
    // Verify that the target frequencies are reachable.
    if((param->cpu_f > SCIF_SLOWCLOCK_FREQ_HZ) || (param->pba_f > SCIF_SLOWCLOCK_FREQ_HZ)
      || (param->pbb_f > SCIF_SLOWCLOCK_FREQ_HZ))
      return(-1);
#endif
  return(pcl_configure_synchronous_clocks(PM_CLK_SRC_SLOW, SCIF_SLOWCLOCK_FREQ_HZ, param));
}
long int pcl_configure_usb_clock (void)
Configure the USB Clock.
Returns:
Status.
Return values:
0 Success.
<0 An error occured.
Definition at line 500 of file power_clocks_lib.c.
References PASS, PCL_NOT_SUPPORTED, and pm_configure_usb_clock().
{
#ifndef AVR32_PM_VERSION_RESETVALUE
// Implementation for UC3A, UC3A3, UC3B parts.
  pm_configure_usb_clock();
  return PASS;
#else
 #if UC3C
    const scif_pll_opt_t opt = {
              .osc = SCIF_OSC0,     // Sel Osc0 or Osc1
              .lockcount = 16,      // lockcount in main clock for the PLL wait lock
              .div = 1,             // DIV=1 in the formula
              .mul = 5,             // MUL=7 in the formula
              .pll_div2 = 1,        // pll_div2 Divide the PLL output frequency by 2 (this settings does not change the FVCO value)
              .pll_wbwdisable = 0,  //pll_wbwdisable 1 Disable the Wide-Bandith Mode (Wide-Bandwith mode allow a faster startup time and out-of-lock time). 0 to enable the Wide-Bandith Mode.
              .pll_freq = 1,        // Set to 1 for VCO frequency range 80-180MHz, set to 0 for VCO frequency range 160-240Mhz.
    };
    /* Setup PLL1 on Osc0, mul=7 ,no divisor, lockcount=16, ie. 16Mhzx6 = 96MHz output */
    scif_pll_setup(SCIF_PLL1, opt); // lockcount in main clock for the PLL wait lock
    /* Enable PLL1 */
    scif_pll_enable(SCIF_PLL1);
    /* Wait for PLL1 locked */
    scif_wait_for_pll_locked(SCIF_PLL1) ;
  // Implementation for UC3C parts.
    // Setup the generic clock for USB
    scif_gc_setup(
#if (defined AVR32_USBB)
                                AVR32_SCIF_GCLK_USB,
#else
                                AVR32_SCIF_GCLK_USBC,
#endif
                  SCIF_GCCTRL_PLL1,
                  AVR32_SCIF_GC_NO_DIV_CLOCK,
                  0);
    // Now enable the generic clock
    scif_gc_enable(
#if (defined AVR32_USBB)
                                AVR32_SCIF_GCLK_USB
#else
                                AVR32_SCIF_GCLK_USBC
#endif
                                );
    return PASS;
 #else
      return PCL_NOT_SUPPORTED;
 #endif
#endif
}
unsigned long pcl_read_gplp (unsigned long gplp)
Read the content of the GPLP registers.
Parameters:
gplp GPLP register index (0,1,... depending on the number of GPLP registers for a given part)
Returns:
The content of the chosen GPLP register.
long int pcl_switch_to_osc (pcl_osc_t osc, unsigned int fcrystal, unsigned int startup)
Switch the main clock source to Osc0 configured in crystal mode.
Parameters:
osc The oscillator to enable and switch to.
fcrystal Oscillator external crystal frequency (Hz)
startup Oscillator startup time.
Returns:
Status.
Return values:
0 Success.
<0 An error occured.
Definition at line 457 of file power_clocks_lib.c.
References flashc_set_flash_waitstate_and_readmode(), PASS, PCL_NOT_SUPPORTED, PCL_OSC0, and pm_switch_to_osc0().
{
#ifndef AVR32_PM_VERSION_RESETVALUE
// Implementation for UC3A, UC3A3, UC3B parts.
  if(PCL_OSC0 == osc)
  {
    // Configure OSC0 in crystal mode, external crystal with a FOSC0 Hz frequency,
    // enable the OSC0, set the main clock source as being OSC0.
    pm_switch_to_osc0(&AVR32_PM, fcrystal, startup);
  }
  else
  {
    return PCL_NOT_SUPPORTED;
  }
#else
// Implementation for UC3C, UC3L parts.
  #if AVR32_PM_VERSION_RESETVALUE < 0x400
    return PCL_NOT_SUPPORTED;
  #else
  if(PCL_OSC0 == osc)
  {
    // Configure OSC0 in crystal mode, external crystal with a fcrystal Hz frequency.
    scif_configure_osc_crystalmode(SCIF_OSC0, fcrystal);
    // Enable the OSC0
    scif_enable_osc(SCIF_OSC0, startup, true);
    // Set the Flash wait state and the speed read mode (depending on the target CPU frequency).
#if UC3L
    flashcdw_set_flash_waitstate_and_readmode(fcrystal);
#elif UC3C
    flashc_set_flash_waitstate_and_readmode(fcrystal);
#endif
    // Set the main clock source as being OSC0.
    pm_set_mclk_source(PM_CLK_SRC_OSC0);
  }
  else
  {
    return PCL_NOT_SUPPORTED;
  }
  #endif
#endif
  return PASS;
}
void pcl_write_gplp (unsigned long gplp, unsigned long value)
Write into the GPLP registers.
Parameters:
gplp GPLP register index (0,1,... depending on the number of GPLP registers for a given part)
value Value to write