OS: MEMORY - FLASHC - Flash Controller
MEMORY - FLASHC - Flash Controller
FLASHC interfaces a flash block with the 32-bit internal HSB bus.
Defines
#define AVR32_FLASHC_REGIONS
Number of flash regions defined by the FLASHC.
FLASHC Status
static unsigned int flashc_error_status = 0
Sticky error status of the FLASHC.
static unsigned int flashc_get_error_status (void)
Gets the error status of the FLASHC.
Flash Properties
unsigned int flashc_get_flash_size (void)
Gets the size of the whole flash array.
unsigned int flashc_get_page_count (void)
Gets the total number of pages in the flash array.
unsigned int flashc_get_page_count_per_region (void)
Gets the number of pages in each flash region.
unsigned int flashc_get_page_region (int page_number)
Gets the region number of a page.
unsigned int flashc_get_region_first_page_number (unsigned int region)
Gets the number of the first page of a region.
FLASHC Control
unsigned int flashc_get_wait_state (void)
Gets the number of wait states of flash read accesses.
void flashc_set_wait_state (unsigned int wait_state)
Sets the number of wait states of flash read accesses.
void flashc_set_bus_freq (unsigned int cpu_f_hz)
Depending on the CPU frequency, set the wait states of flash read accesses.
bool flashc_is_ready_int_enabled (void)
Tells whether the Flash Ready interrupt is enabled.
void flashc_enable_ready_int (bool enable)
Enables or disables the Flash Ready interrupt.
bool flashc_is_lock_error_int_enabled (void)
Tells whether the Lock Error interrupt is enabled.
void flashc_enable_lock_error_int (bool enable)
Enables or disables the Lock Error interrupt.
bool flashc_is_prog_error_int_enabled (void)
Tells whether the Programming Error interrupt is enabled.
void flashc_enable_prog_error_int (bool enable)
Enables or disables the Programming Error interrupt.
#define flash_set_bus_freq(cpu_f_hz) flashc_set_bus_freq(cpu_f_hz)
Alias on the flashc_set_bus_freq() function.
FLASHC Status
void(*volatile flashc_wait_until_ready)(void)
Pointer to the function used by the driver when it needs to wait until the FLASHC is ready to run a new command.
bool flashc_is_ready (void)
Tells whether the FLASHC is ready to run a new command.
void flashc_default_wait_until_ready (void)
Waits actively until the FLASHC is ready to run a new command.
bool flashc_is_lock_error (void)
Tells whether a Lock Error has occurred during the last function called that issued one or more FLASHC commands.
bool flashc_is_programming_error (void)
Tells whether a Programming Error has occurred during the last function called that issued one or more FLASHC commands.
FLASHC Command Control
unsigned int flashc_get_command (void)
Gets the last issued FLASHC command.
unsigned int flashc_get_page_number (void)
Gets the current FLASHC page number.
void flashc_issue_command (unsigned int command, int page_number)
Issues a FLASHC command.
FLASHC Global Commands
void flashc_no_operation (void)
Issues a No Operation command to the FLASHC.
void flashc_erase_all (void)
Issues an Erase All command to the FLASHC.
FLASHC Protection Mechanisms
bool flashc_is_security_bit_active (void)
Tells whether the Security bit is active.
void flashc_activate_security_bit (void)
Activates the Security bit.
unsigned int flashc_get_bootloader_protected_size (void)
Gets the bootloader protected size.
unsigned int flashc_set_bootloader_protected_size (unsigned int bootprot_size)
Sets the bootloader protected size.
bool flashc_is_external_privileged_fetch_locked (void)
Tells whether external privileged fetch is locked.
void flashc_lock_external_privileged_fetch (bool lock)
Locks or unlocks external privileged fetch.
bool flashc_is_page_region_locked (int page_number)
Tells whether the region of a page is locked.
bool flashc_is_region_locked (unsigned int region)
Tells whether a region is locked.
void flashc_lock_page_region (int page_number, bool lock)
Locks or unlocks the region of a page.
void flashc_lock_region (unsigned int region, bool lock)
Locks or unlocks a region.
void flashc_lock_all_regions (bool lock)
Locks or unlocks all regions.
Access to General-Purpose Fuses
bool flashc_read_gp_fuse_bit (unsigned int gp_fuse_bit)
Reads a general-purpose fuse bit.
uint64_t flashc_read_gp_fuse_bitfield (unsigned int pos, unsigned int width)
Reads a general-purpose fuse bit-field.
uint8_t flashc_read_gp_fuse_byte (unsigned int gp_fuse_byte)
Reads a general-purpose fuse byte.
uint64_t flashc_read_all_gp_fuses (void)
Reads all general-purpose fuses.
bool flashc_erase_gp_fuse_bit (unsigned int gp_fuse_bit, bool check)
Erases a general-purpose fuse bit.
bool flashc_erase_gp_fuse_bitfield (unsigned int pos, unsigned int width, bool check)
Erases a general-purpose fuse bit-field.
bool flashc_erase_gp_fuse_byte (unsigned int gp_fuse_byte, bool check)
Erases a general-purpose fuse byte.
bool flashc_erase_all_gp_fuses (bool check)
Erases all general-purpose fuses.
void flashc_write_gp_fuse_bit (unsigned int gp_fuse_bit, bool value)
Writes a general-purpose fuse bit.
void flashc_write_gp_fuse_bitfield (unsigned int pos, unsigned int width, uint64_t value)
Writes a general-purpose fuse bit-field.
void flashc_write_gp_fuse_byte (unsigned int gp_fuse_byte, uint8_t value)
Writes a general-purpose fuse byte.
void flashc_write_all_gp_fuses (uint64_t value)
Writes all general-purpose fuses.
void flashc_set_gp_fuse_bit (unsigned int gp_fuse_bit, bool value)
Sets a general-purpose fuse bit with the appropriate erase and write operations.
void flashc_set_gp_fuse_bitfield (unsigned int pos, unsigned int width, uint64_t value)
Sets a general-purpose fuse bit-field with the appropriate erase and write operations.
void flashc_set_gp_fuse_byte (unsigned int gp_fuse_byte, uint8_t value)
Sets a general-purpose fuse byte with the appropriate erase and write operations.
void flashc_set_all_gp_fuses (uint64_t value)
Sets all general-purpose fuses with the appropriate erase and write operations.
Access to Flash Pages
void flashc_clear_page_buffer (void)
Clears the page buffer.
bool flashc_is_page_erased (void)
Tells whether the page to which the last Quick Page Read or Quick Page Read User Page command was applied was erased.
bool flashc_quick_page_read (int page_number)
Applies the Quick Page Read command to a page.
bool flashc_erase_page (int page_number, bool check)
Erases a page.
bool flashc_erase_all_pages (bool check)
Erases all pages within the flash array.
void flashc_write_page (int page_number)
Writes a page from the page buffer.
bool flashc_quick_user_page_read (void)
Issues a Quick Page Read User Page command to the FLASHC.
bool flashc_erase_user_page (bool check)
Erases the User page.
void flashc_write_user_page (void)
Writes the User page from the page buffer.
volatile void * flashc_memset8 (volatile void *dst, uint8_t src, size_t nbytes, bool erase)
Copies nbytes bytes to the flash destination pointed to by dst from the repeated src source byte.
volatile void * flashc_memset16 (volatile void *dst, uint16_t src, size_t nbytes, bool erase)
Copies nbytes bytes to the flash destination pointed to by dst from the repeated src big-endian source half-word.
volatile void * flashc_memset32 (volatile void *dst, uint32_t src, size_t nbytes, bool erase)
Copies nbytes bytes to the flash destination pointed to by dst from the repeated src big-endian source word.
volatile void * flashc_memset64 (volatile void *dst, uint64_t src, size_t nbytes, bool erase)
Copies nbytes bytes to the flash destination pointed to by dst from the repeated src big-endian source double-word.
volatile void * flashc_memcpy (volatile void *dst, const void *src, size_t nbytes, bool erase)
Copies nbytes bytes to the flash destination pointed to by dst from the source pointed to by src.
void flashc_set_flash_waitstate_and_readmode (unsigned long cpu_f_hz)
Depednding to the CPU frequency, set the wait states of flash read accesses and enable or disable the High speed read mode.
#define flashc_memset(dst, src, src_width, nbytes, erase) TPASTE2(flashc_memset, src_width)((dst), (src), (nbytes), (erase))
Copies nbytes bytes to the flash destination pointed to by dst from the repeated src big-endian source pattern.
Detailed Description
FLASHC interfaces a flash block with the 32-bit internal HSB bus.
Define Documentation
#define AVR32_FLASHC_REGIONS
Value:
(AVR32_FLASHC_FLASH_SIZE /\
            (AVR32_FLASHC_PAGES_PR_REGION * AVR32_FLASHC_PAGE_SIZE))
Number of flash regions defined by the FLASHC.
Definition at line 56 of file flashc.h.
Referenced by flashc_get_page_count_per_region(), flashc_is_region_locked(), and flashc_lock_all_regions().
#define flash_set_bus_freq (cpu_f_hz) flashc_set_bus_freq(cpu_f_hz)
Alias on the flashc_set_bus_freq() function.
Parameters:
cpu_f_hz The CPU frequency
Definition at line 131 of file flashc.h.
#define flashc_memset (dst, src, src_width, nbytes, erase) TPASTE2(flashc_memset, src_width)((dst), (src), (nbytes), (erase))
Copies nbytes bytes to the flash destination pointed to by dst from the repeated src big-endian source pattern.
All pointer and size alignments are supported.
Parameters:
dst Pointer to flash destination.
src Source double-word.
src_width src width in bits: 8, 16, 32 or 64.
nbytes Number of bytes to set.
erase Whether to erase before writing: true or false.
Returns:
The value of dst.
Warning:
This function may be called with erase set to false only if the destination consists only of erased words, i.e. this function can not be used to write only one bit of a previously written word. E.g., if 0x00000001 then 0xFFFFFFFE are written to a word, the resulting value in flash may be different from 0x00000000.
A Lock Error is issued if the command is applied to pages belonging to a locked region or to the bootloader protected area.
Note:
The FLASHC error status returned by flashc_is_lock_error and flashc_is_programming_error is updated.
Definition at line 956 of file flashc.h.
Function Documentation
void flashc_activate_security_bit (void)
Activates the Security bit.
Note:
The FLASHC error status returned by flashc_is_lock_error and flashc_is_programming_error is updated.
Definition at line 338 of file flashc.c.
References flashc_issue_command().
{
    flashc_issue_command(AVR32_FLASHC_FCMD_CMD_SSB, -1);
}
void flashc_clear_page_buffer (void)
Clears the page buffer.
This command resets all bits in the page buffer to one. Write accesses to the page buffer can only change page buffer bits from one to zero.
Warning:
The page buffer is not automatically reset after a page write.
Note:
The FLASHC error status returned by flashc_is_lock_error and flashc_is_programming_error is updated.
Definition at line 626 of file flashc.c.
References flashc_issue_command().
Referenced by flashc_memcpy(), and flashc_memset64().
{
    flashc_issue_command(AVR32_FLASHC_FCMD_CMD_CPB, -1);
}
void flashc_default_wait_until_ready (void)
Waits actively until the FLASHC is ready to run a new command.
This is the default function assigned to flashc_wait_until_ready.
Definition at line 222 of file flashc.c.
References flashc_is_ready().
{
    while (!flashc_is_ready());
}
void flashc_enable_lock_error_int (bool enable)
Enables or disables the Lock Error interrupt.
Parameters:
enable Whether to enable the Lock Error interrupt: true or false.
Definition at line 186 of file flashc.c.
References u_avr32_flashc_fcr_t::FCR, and u_avr32_flashc_fcr_t::fcr.
{
    u_avr32_flashc_fcr_t u_avr32_flashc_fcr = {AVR32_FLASHC.fcr};
    u_avr32_flashc_fcr.FCR.locke = (enable != false);
    AVR32_FLASHC.fcr = u_avr32_flashc_fcr.fcr;
}
void flashc_enable_prog_error_int (bool enable)
Enables or disables the Programming Error interrupt.
Parameters:
enable Whether to enable the Programming Error interrupt: true or false.
Definition at line 200 of file flashc.c.
References u_avr32_flashc_fcr_t::FCR, and u_avr32_flashc_fcr_t::fcr.
{
    u_avr32_flashc_fcr_t u_avr32_flashc_fcr = {AVR32_FLASHC.fcr};
    u_avr32_flashc_fcr.FCR.proge = (enable != false);
    AVR32_FLASHC.fcr = u_avr32_flashc_fcr.fcr;
}
void flashc_enable_ready_int (bool enable)
Enables or disables the Flash Ready interrupt.
Parameters:
enable Whether to enable the Flash Ready interrupt: true or false.
Definition at line 172 of file flashc.c.
References u_avr32_flashc_fcr_t::FCR, and u_avr32_flashc_fcr_t::fcr.
{
    u_avr32_flashc_fcr_t u_avr32_flashc_fcr = {AVR32_FLASHC.fcr};
    u_avr32_flashc_fcr.FCR.frdy = (enable != false);
    AVR32_FLASHC.fcr = u_avr32_flashc_fcr.fcr;
}
void flashc_erase_all (void)
Issues an Erase All command to the FLASHC.
This command erases all bits in the flash array, the general-purpose fuse bits and the Security bit. The User page is not erased.
This command also ensures that all volatile memories, such as register file and RAMs, are erased before the Security bit is erased, i.e. deactivated.
Warning:
A Lock Error is issued if at least one region is locked or the bootloader protection is active.
Note:
The FLASHC error status returned by flashc_is_lock_error and flashc_is_programming_error is updated.
An erase operation can only set bits.
Definition at line 318 of file flashc.c.
References flashc_issue_command().
{
    flashc_issue_command(AVR32_FLASHC_FCMD_CMD_EA, -1);
}
bool flashc_erase_all_gp_fuses (bool check)
Erases all general-purpose fuses.
Parameters:
check Whether to check erase: true or false.
Returns:
Whether the erase succeeded or always true if erase check was not requested.
Warning:
A Lock Error is issued if the Security bit is active.
Note:
The FLASHC error status returned by flashc_is_lock_error and flashc_is_programming_error is updated.
An erase operation can only set bits.
The actual number of general-purpose fuse bits implemented by hardware is given by AVR32_FLASHC_GPF_NUM. The other bits among the 64 are fixed at 1 by hardware.
Definition at line 493 of file flashc.c.
References flashc_issue_command(), and flashc_read_all_gp_fuses().
Referenced by flashc_erase_gp_fuse_byte(), and flashc_set_all_gp_fuses().
{
    flashc_issue_command(AVR32_FLASHC_FCMD_CMD_EAGPF, -1);
    return (check) ? (flashc_read_all_gp_fuses() == 0xFFFFFFFFFFFFFFFFULL) : true;
}
bool flashc_erase_all_pages (bool check)
Erases all pages within the flash array.
Parameters:
check Whether to check erase: true or false.
Returns:
Whether the erase succeeded or always true if erase check was not requested.
Warning:
A Lock Error is issued if at least one region is locked or the bootloader protection is active.
Note:
The FLASHC error status returned by flashc_is_lock_error and flashc_is_programming_error is updated.
An erase operation can only set bits.
Definition at line 659 of file flashc.c.
References flashc_erase_page(), flashc_error_status, and flashc_get_page_count().
{
    bool all_pages_erased = true;
    unsigned int error_status = 0;
    unsigned int page_number = flashc_get_page_count();
    while (page_number) {
        all_pages_erased &= flashc_erase_page(--page_number, check);
        error_status |= flashc_error_status;
    }
    flashc_error_status = error_status;
    return all_pages_erased;
}
bool flashc_erase_gp_fuse_bit (unsigned int gp_fuse_bit, bool check)
Erases a general-purpose fuse bit.
Parameters:
gp_fuse_bit The general-purpose fuse bit: 0 to 63.
check Whether to check erase: true or false.
Returns:
Whether the erase succeeded or always true if erase check was not requested.
Warning:
A Lock Error is issued if the Security bit is active and the command is applied to BOOTPROT or EPFL fuses.
Note:
The FLASHC error status returned by flashc_is_lock_error and flashc_is_programming_error is updated.
An erase operation can only set bits.
The actual number of general-purpose fuse bits implemented by hardware is given by AVR32_FLASHC_GPF_NUM. The other bits among the 64 are fixed at 1 by hardware.
Definition at line 450 of file flashc.c.
References flashc_issue_command(), and flashc_read_gp_fuse_bit().
Referenced by flashc_erase_gp_fuse_bitfield(), and flashc_set_gp_fuse_bit().
{
    flashc_issue_command(AVR32_FLASHC_FCMD_CMD_EGPB, gp_fuse_bit & 0x3F);
    return (check) ? flashc_read_gp_fuse_bit(gp_fuse_bit) : true;
}
bool flashc_erase_gp_fuse_bitfield (unsigned int pos, unsigned int width, bool check)
Erases a general-purpose fuse bit-field.
Parameters:
pos The bit-position of the general-purpose fuse bit-field: 0 to 63.
width The bit-width of the general-purpose fuse bit-field: 0 to 64.
check Whether to check erase: true or false.
Returns:
Whether the erase succeeded or always true if erase check was not requested.
Warning:
A Lock Error is issued if the Security bit is active and the command is applied to BOOTPROT or EPFL fuses.
Note:
The FLASHC error status returned by flashc_is_lock_error and flashc_is_programming_error is updated.
An erase operation can only set bits.
The actual number of general-purpose fuse bits implemented by hardware is given by AVR32_FLASHC_GPF_NUM. The other bits among the 64 are fixed at 1 by hardware.
Definition at line 457 of file flashc.c.
References flashc_erase_gp_fuse_bit(), flashc_error_status, flashc_read_gp_fuse_bitfield(), and min.
{
    unsigned int error_status = 0;
    unsigned int gp_fuse_bit;
    pos &= 0x3F;
    width = min(width, 64);
    for (gp_fuse_bit = pos; gp_fuse_bit < pos + width; gp_fuse_bit++) {
        flashc_erase_gp_fuse_bit(gp_fuse_bit, false);
        error_status |= flashc_error_status;
    }
    flashc_error_status = error_status;
    return (check) ? (flashc_read_gp_fuse_bitfield(pos, width) == (1ULL << width) - 1) : true;
}
bool flashc_erase_gp_fuse_byte (unsigned int gp_fuse_byte, bool check)
Erases a general-purpose fuse byte.
Parameters:
gp_fuse_byte The general-purpose fuse byte: 0 to 7.
check Whether to check erase: true or false.
Returns:
Whether the erase succeeded or always true if erase check was not requested.
Warning:
A Lock Error is issued if the Security bit is active.
Note:
The FLASHC error status returned by flashc_is_lock_error and flashc_is_programming_error is updated.
An erase operation can only set bits.
The actual number of general-purpose fuse bits implemented by hardware is given by AVR32_FLASHC_GPF_NUM. The other bits among the 64 are fixed at 1 by hardware.
Definition at line 473 of file flashc.c.
References flashc_erase_all_gp_fuses(), flashc_error_status, flashc_read_all_gp_fuses(), flashc_read_gp_fuse_byte(), and flashc_write_gp_fuse_byte().
Referenced by flashc_set_gp_fuse_byte().
{
    unsigned int error_status;
    unsigned int current_gp_fuse_byte;
    uint64_t value = flashc_read_all_gp_fuses();
    flashc_erase_all_gp_fuses(false);
    error_status = flashc_error_status;
    for (current_gp_fuse_byte = 0; current_gp_fuse_byte < 8; current_gp_fuse_byte++, value >>= 8) {
        if (current_gp_fuse_byte != gp_fuse_byte) {
            flashc_write_gp_fuse_byte(current_gp_fuse_byte, value);
            error_status |= flashc_error_status;
        }
    }
    flashc_error_status = error_status;
    return (check) ? (flashc_read_gp_fuse_byte(gp_fuse_byte) == 0xFF) : true;
}
bool flashc_erase_page (int page_number, bool check)
Erases a page.
Parameters:
page_number The page number:
0 to (flashc_get_page_count() - 1): a page number within the flash array;
< 0: the current page number.
check Whether to check erase: true or false.
Returns:
Whether the erase succeeded or always true if erase check was not requested.
Warning:
A Lock Error is issued if the command is applied to a page belonging to a locked region or to the bootloader protected area.
Note:
The FLASHC error status returned by flashc_is_lock_error and flashc_is_programming_error is updated.
An erase operation can only set bits.
Definition at line 645 of file flashc.c.
References flashc_error_status, flashc_issue_command(), and flashc_quick_page_read().
Referenced by flashc_erase_all_pages(), flashc_memcpy(), and flashc_memset64().
{
    bool page_erased = true;
    flashc_issue_command(AVR32_FLASHC_FCMD_CMD_EP, page_number);
    if (check) {
        unsigned int error_status = flashc_error_status;
        page_erased = flashc_quick_page_read(-1);
        flashc_error_status |= error_status;
    }
    return page_erased;
}
bool flashc_erase_user_page (bool check)
Erases the User page.
Parameters:
check Whether to check erase: true or false.
Returns:
Whether the erase succeeded or always true if erase check was not requested.
Note:
The FLASHC error status returned by flashc_is_lock_error and flashc_is_programming_error is updated.
An erase operation can only set bits.
Definition at line 687 of file flashc.c.
References flashc_issue_command(), and flashc_quick_user_page_read().
Referenced by flashc_memcpy(), and flashc_memset64().
{
    flashc_issue_command(AVR32_FLASHC_FCMD_CMD_EUP, -1);
    return (check) ? flashc_quick_user_page_read() : true;
}
unsigned int flashc_get_bootloader_protected_size (void)
Gets the bootloader protected size.
Returns:
The bootloader protected size in bytes.
Definition at line 344 of file flashc.c.
References flashc_read_gp_fuse_bitfield().
Referenced by flashc_set_bootloader_protected_size().
{
    unsigned int bootprot = (1 << AVR32_FLASHC_FGPFRLO_BOOTPROT_SIZE) - 1 -
            flashc_read_gp_fuse_bitfield(AVR32_FLASHC_FGPFRLO_BOOTPROT_OFFSET,
            AVR32_FLASHC_FGPFRLO_BOOTPROT_SIZE);
    return (bootprot) ? AVR32_FLASHC_PAGE_SIZE << bootprot : 0;
}
unsigned int flashc_get_command (void)
Gets the last issued FLASHC command.
Returns:
The last issued FLASHC command.
Definition at line 275 of file flashc.c.
{
    return (AVR32_FLASHC.fcmd & AVR32_FLASHC_FCMD_CMD_MASK) >> AVR32_FLASHC_FCMD_CMD_OFFSET;
}
static unsigned int flashc_get_error_status (void) [static]
Gets the error status of the FLASHC.
Returns:
The error status of the FLASHC built up from AVR32_FLASHC_FSR_LOCKE_MASK and AVR32_FLASHC_FSR_PROGE_MASK.
Warning:
This hardware error status is cleared by all functions reading the Flash Status Register (FSR). This function is therefore not part of the driver's API which instead presents flashc_is_lock_error and flashc_is_programming_error.
Definition at line 241 of file flashc.c.
Referenced by flashc_issue_command().
{
    return AVR32_FLASHC.fsr & (AVR32_FLASHC_FSR_LOCKE_MASK |
            AVR32_FLASHC_FSR_PROGE_MASK);
}
unsigned int flashc_get_flash_size (void)
Gets the size of the whole flash array.
Returns:
The size of the whole flash array in bytes.
Definition at line 68 of file flashc.c.
Referenced by flashc_get_page_count(), flashc_memcpy(), and flashc_memset64().
{
#if (AVR32_FLASHC_H_VERSION >= 300)
    const uint16_t FLASH_SIZE[] = {
        4,
        8,
        16,
        32,
        48,
        64,
        96,
        128,
        192,
        256,
        384,
        512,
        768,
        1024,
        2048,
    };
    return ((unsigned int)FLASH_SIZE[(AVR32_FLASHC.pr & AVR32_FLASHC_PR_FSZ_MASK)
            >> AVR32_FLASHC_PR_FSZ_OFFSET])<<10;
#else // in older flashc version, FSZ is located in FSR register
    const uint16_t FLASH_SIZE[] = {
        32,
        64,
        128,
        256,
        384,
        512,
        768,
        1024,
    };
    return ((unsigned int)FLASH_SIZE[(AVR32_FLASHC.fsr & AVR32_FLASHC_FSR_FSZ_MASK)
            >> AVR32_FLASHC_FSR_FSZ_OFFSET]) << 10;
#endif
}
unsigned int flashc_get_page_count (void)
Gets the total number of pages in the flash array.
Returns:
The total number of pages in the flash array.
Definition at line 108 of file flashc.c.
References flashc_get_flash_size().
Referenced by flashc_erase_all_pages(), and flashc_get_page_count_per_region().
{
    return flashc_get_flash_size() / AVR32_FLASHC_PAGE_SIZE;
}
unsigned int flashc_get_page_count_per_region (void)
Gets the number of pages in each flash region.
Returns:
The number of pages in each flash region.
Definition at line 114 of file flashc.c.
References AVR32_FLASHC_REGIONS, and flashc_get_page_count().
Referenced by flashc_get_page_region(), and flashc_get_region_first_page_number().
{
    return flashc_get_page_count() / AVR32_FLASHC_REGIONS;
}
unsigned int flashc_get_page_number (void)
Gets the current FLASHC page number.
Returns:
The current FLASHC page number.
Definition at line 281 of file flashc.c.
Referenced by flashc_get_page_region().
{
    return (AVR32_FLASHC.fcmd & AVR32_FLASHC_FCMD_PAGEN_MASK) >> AVR32_FLASHC_FCMD_PAGEN_OFFSET;
}
unsigned int flashc_get_page_region (int page_number)
Gets the region number of a page.
Parameters:
page_number The page number:
0 to (flashc_get_page_count() - 1): a page number within the flash array;
< 0: the current page number.
Returns:
The region number of the specified page.
Definition at line 120 of file flashc.c.
References flashc_get_page_count_per_region(), and flashc_get_page_number().
Referenced by flashc_is_page_region_locked().
{
    return ((page_number >= 0) ? page_number
            : flashc_get_page_number()) / flashc_get_page_count_per_region();
}
unsigned int flashc_get_region_first_page_number (unsigned int region)
Gets the number of the first page of a region.
Parameters:
region The region number: 0 to (AVR32_FLASHC_REGIONS - 1).
Returns:
The number of the first page of the specified region.
Definition at line 127 of file flashc.c.
References flashc_get_page_count_per_region().
Referenced by flashc_lock_region().
{
    return region * flashc_get_page_count_per_region();
}
unsigned int flashc_get_wait_state (void)
Gets the number of wait states of flash read accesses.
Returns:
The number of wait states of flash read accesses.
Definition at line 141 of file flashc.c.
{
    return (AVR32_FLASHC.fcr & AVR32_FLASHC_FCR_FWS_MASK) >> AVR32_FLASHC_FCR_FWS_OFFSET;
}
bool flashc_is_external_privileged_fetch_locked (void)
Tells whether external privileged fetch is locked.
Returns:
Whether external privileged fetch is locked.
Definition at line 369 of file flashc.c.
References flashc_read_gp_fuse_bit().
{
    return (!flashc_read_gp_fuse_bit(AVR32_FLASHC_FGPFRLO_EPFL_OFFSET));
}
bool flashc_is_lock_error (void)
Tells whether a Lock Error has occurred during the last function called that issued one or more FLASHC commands.
Returns:
Whether a Lock Error has occurred during the last function called that issued one or more FLASHC commands.
Definition at line 255 of file flashc.c.
References flashc_error_status.
{
    return ((flashc_error_status & AVR32_FLASHC_FSR_LOCKE_MASK) != 0);
}
bool flashc_is_lock_error_int_enabled (void)
Tells whether the Lock Error interrupt is enabled.
Returns:
Whether the Lock Error interrupt is enabled.
Definition at line 180 of file flashc.c.
{
    return ((AVR32_FLASHC.fcr & AVR32_FLASHC_FCR_LOCKE_MASK) != 0);
}
bool flashc_is_page_erased (void)
Tells whether the page to which the last Quick Page Read or Quick Page Read User Page command was applied was erased.
Returns:
Whether the page to which the last Quick Page Read or Quick Page Read User Page command was applied was erased.
Definition at line 632 of file flashc.c.
Referenced by flashc_quick_page_read(), and flashc_quick_user_page_read().
{
    return ((AVR32_FLASHC.fsr & AVR32_FLASHC_FSR_QPRR_MASK) != 0);
}
bool flashc_is_page_region_locked (int page_number)
Tells whether the region of a page is locked.
Parameters:
page_number The page number:
0 to (flashc_get_page_count() - 1): a page number within the flash array;
< 0: the current page number.
Returns:
Whether the region of the specified page is locked.
Definition at line 381 of file flashc.c.
References flashc_get_page_region(), and flashc_is_region_locked().
{
    return flashc_is_region_locked(flashc_get_page_region(page_number));
}
bool flashc_is_prog_error_int_enabled (void)
Tells whether the Programming Error interrupt is enabled.
Returns:
Whether the Programming Error interrupt is enabled.
Definition at line 194 of file flashc.c.
{
    return ((AVR32_FLASHC.fcr & AVR32_FLASHC_FCR_PROGE_MASK) != 0);
}
bool flashc_is_programming_error (void)
Tells whether a Programming Error has occurred during the last function called that issued one or more FLASHC commands.
Returns:
Whether a Programming Error has occurred during the last function called that issued one or more FLASHC commands.
Definition at line 261 of file flashc.c.
References flashc_error_status.
{
    return ((flashc_error_status & AVR32_FLASHC_FSR_PROGE_MASK) != 0);
}
bool flashc_is_ready (void)
Tells whether the FLASHC is ready to run a new command.
Returns:
Whether the FLASHC is ready to run a new command.
Definition at line 216 of file flashc.c.
Referenced by flashc_default_wait_until_ready().
{
    return ((AVR32_FLASHC.fsr & AVR32_FLASHC_FSR_FRDY_MASK) != 0);
}
bool flashc_is_ready_int_enabled (void)
Tells whether the Flash Ready interrupt is enabled.
Returns:
Whether the Flash Ready interrupt is enabled.
Definition at line 166 of file flashc.c.
{
    return ((AVR32_FLASHC.fcr & AVR32_FLASHC_FCR_FRDY_MASK) != 0);
}
bool flashc_is_region_locked (unsigned int region)
Tells whether a region is locked.
Parameters:
region The region number: 0 to (AVR32_FLASHC_REGIONS - 1).
Returns:
Whether the specified region is locked.
Definition at line 387 of file flashc.c.
References AVR32_FLASHC_REGIONS.
Referenced by flashc_is_page_region_locked().
{
    return ((AVR32_FLASHC.fsr & AVR32_FLASHC_FSR_LOCK0_MASK << (region & (AVR32_FLASHC_REGIONS - 1))) != 0);
}
bool flashc_is_security_bit_active (void)
Tells whether the Security bit is active.
Returns:
Whether the Security bit is active.
Definition at line 332 of file flashc.c.
{
    return ((AVR32_FLASHC.fsr & AVR32_FLASHC_FSR_SECURITY_MASK) != 0);
}
void flashc_issue_command (unsigned int command, int page_number)
Issues a FLASHC command.
Parameters:
command The command: AVR32_FLASHC_FCMD_CMD_x.
page_number The page number to apply the command to:
0 to (flashc_get_page_count() - 1): a page number within the flash array;
< 0: use this to apply the command to the current page number or if the command does not apply to any page number;
this argument may have other meanings according to the command. See the FLASHC chapter of the MCU datasheet.
Warning:
A Lock Error is issued if the command violates the protection mechanism.
A Programming Error is issued if the command is invalid.
Note:
The FLASHC error status returned by flashc_is_lock_error and flashc_is_programming_error is updated.
Definition at line 287 of file flashc.c.
References u_avr32_flashc_fcmd_t::FCMD, u_avr32_flashc_fcmd_t::fcmd, flashc_error_status, flashc_get_error_status(), and flashc_wait_until_ready.
Referenced by flashc_activate_security_bit(), flashc_clear_page_buffer(), flashc_erase_all(), flashc_erase_all_gp_fuses(), flashc_erase_gp_fuse_bit(), flashc_erase_page(), flashc_erase_user_page(), flashc_lock_page_region(), flashc_no_operation(), flashc_quick_page_read(), flashc_quick_user_page_read(), flashc_write_gp_fuse_bit(), flashc_write_gp_fuse_byte(), flashc_write_page(), flashc_write_user_page(), and pm_configure_clocks().
{
    u_avr32_flashc_fcmd_t u_avr32_flashc_fcmd;
    flashc_wait_until_ready();
    u_avr32_flashc_fcmd.fcmd = AVR32_FLASHC.fcmd;
    u_avr32_flashc_fcmd.FCMD.cmd = command;
    if (page_number >= 0) {
        u_avr32_flashc_fcmd.FCMD.pagen = page_number;
    }
    u_avr32_flashc_fcmd.FCMD.key = AVR32_FLASHC_FCMD_KEY_KEY;
    AVR32_FLASHC.fcmd = u_avr32_flashc_fcmd.fcmd;
    flashc_error_status = flashc_get_error_status();
    flashc_wait_until_ready();
}
void flashc_lock_all_regions (bool lock)
Locks or unlocks all regions.
Parameters:
lock Whether to lock the regions: true or false.
Note:
The FLASHC error status returned by flashc_is_lock_error and flashc_is_programming_error is updated.
Definition at line 405 of file flashc.c.
References AVR32_FLASHC_REGIONS, flashc_error_status, and flashc_lock_region().
{
    unsigned int error_status = 0;
    unsigned int region = AVR32_FLASHC_REGIONS;
    while (region) {
        flashc_lock_region(--region, lock);
        error_status |= flashc_error_status;
    }
    flashc_error_status = error_status;
}
void flashc_lock_external_privileged_fetch (bool lock)
Locks or unlocks external privileged fetch.
Parameters:
lock Whether to lock external privileged fetch: true or false.
Warning:
A Lock Error is issued if the Security bit is active.
Note:
The FLASHC error status returned by flashc_is_lock_error and flashc_is_programming_error is updated.
Definition at line 375 of file flashc.c.
References flashc_set_gp_fuse_bit().
{
    flashc_set_gp_fuse_bit(AVR32_FLASHC_FGPFRLO_EPFL_OFFSET, !lock);
}
void flashc_lock_page_region (int page_number, bool lock)
Locks or unlocks the region of a page.
Parameters:
page_number The page number:
0 to (flashc_get_page_count() - 1): a page number within the flash array;
< 0: the current page number.
lock Whether to lock the region of the specified page: true or false.
Note:
The FLASHC error status returned by flashc_is_lock_error and flashc_is_programming_error is updated.
Definition at line 393 of file flashc.c.
References flashc_issue_command().
Referenced by flashc_lock_region().
{
    flashc_issue_command((lock) ? AVR32_FLASHC_FCMD_CMD_LP : AVR32_FLASHC_FCMD_CMD_UP, page_number);
}
void flashc_lock_region (unsigned int region, bool lock)
Locks or unlocks a region.
Parameters:
region The region number: 0 to (AVR32_FLASHC_REGIONS - 1).
lock Whether to lock the specified region: true or false.
Note:
The FLASHC error status returned by flashc_is_lock_error and flashc_is_programming_error is updated.
Definition at line 399 of file flashc.c.
References flashc_get_region_first_page_number(), and flashc_lock_page_region().
Referenced by flashc_lock_all_regions().
{
    flashc_lock_page_region(flashc_get_region_first_page_number(region), lock);
}
volatile void* flashc_memcpy (volatile void * dst, const void * src, size_t nbytes, bool erase)
Copies nbytes bytes to the flash destination pointed to by dst from the source pointed to by src.
The destination areas that are not within the flash array or the User page are caught by an assert() operation.
All pointer and size alignments are supported.
Parameters:
dst Pointer to flash destination.
src Pointer to source data.
nbytes Number of bytes to copy.
erase Whether to erase before writing: true or false.
Returns:
The value of dst.
Warning:
If copying takes place between areas that overlap, the behavior is undefined.
This function may be called with erase set to false only if the destination consists only of erased words, i.e. this function can not be used to write only one bit of a previously written word. E.g., if 0x00000001 then 0xFFFFFFFE are written to a word, the resulting value in flash may be different from 0x00000000.
A Lock Error is issued if the command is applied to pages belonging to a locked region or to the bootloader protected area.
Note:
The FLASHC error status returned by flashc_is_lock_error and flashc_is_programming_error is updated.
Definition at line 877 of file flashc.c.
References Assert, flashc_clear_page_buffer(), flashc_erase_page(), flashc_erase_user_page(), flashc_error_status, flashc_get_flash_size(), flashc_write_page(), flashc_write_user_page(), Union64::u64, and Union64::u8.
{
    uint16_t page_pos;
    Union64 flash_dword;
    uint8_t i;
    bool b_user_page;
    unsigned int error_status = 0;
    uint8_t* flash_add;
    uint8_t* dest_add=(uint8_t*)dst;
    const uint8_t* src_buf=(const uint8_t*)src;
    // Copy area must be in flash array or flash user page
    Assert( (((uint8_t *)dst >= AVR32_FLASH)
            && (((uint8_t *)dst + nbytes) <= (AVR32_FLASH + flashc_get_flash_size())))
            || (((uint8_t *)dst >= AVR32_FLASHC_USER_PAGE)
            && (((uint8_t *)dst + nbytes) <= (AVR32_FLASHC_USER_PAGE + AVR32_FLASHC_USER_PAGE_SIZE))) );
    b_user_page = (volatile uint8_t *)dst >= AVR32_FLASHC_USER_PAGE;
    flash_add = (uint8_t*)((uint32_t)dest_add - ((uint32_t)dest_add % AVR32_FLASHC_PAGE_SIZE));
    while (nbytes) {
        // Clear the page buffer in order to prepare data for a flash page write.
        flashc_clear_page_buffer();
        error_status |= flashc_error_status;
        // Loop in the page
        for (page_pos=0; page_pos<AVR32_FLASHC_PAGE_SIZE; page_pos+=sizeof(uint64_t) ) {
            // Read the flash double-word buffer
            flash_dword.u64 = *(volatile uint64_t*)flash_add;
            // Update double-word if necessary
            for (i = 0; i < sizeof(uint64_t); i++) {
                if (nbytes && (flash_add == dest_add)) {
                    // Update page with data source
                    flash_dword.u8[i] = *src_buf++;
                    dest_add++;
                    nbytes--;
                }
                flash_add++;
            }
            // Write the flash double-word buffer to the page buffer.
            *(volatile uint64_t*)((uint32_t)flash_add - sizeof(uint64_t))= flash_dword.u64;
        }
        // Erase the current page if requested and write it from the page buffer.
        if (erase) {
            (b_user_page)? flashc_erase_user_page(false) : flashc_erase_page(-1, false);
            error_status |= flashc_error_status;
        }
        // Write the page
        (b_user_page)? flashc_write_user_page() : flashc_write_page(-1);
        error_status |= flashc_error_status;
    }
    // Update the FLASHC error status.
    flashc_error_status = error_status;
    // Return the initial destination pointer as the standard memcpy function does.
    return dst;
}
volatile void* flashc_memset16 (volatile void * dst, uint16_t src, size_t nbytes, bool erase)
Copies nbytes bytes to the flash destination pointed to by dst from the repeated src big-endian source half-word.
All pointer and size alignments are supported.
Parameters:
dst Pointer to flash destination.
src Source half-word.
nbytes Number of bytes to set.
erase Whether to erase before writing: true or false.
Returns:
The value of dst.
Warning:
This function may be called with erase set to false only if the destination consists only of erased words, i.e. this function can not be used to write only one bit of a previously written word. E.g., if 0x00000001 then 0xFFFFFFFE are written to a word, the resulting value in flash may be different from 0x00000000.
A Lock Error is issued if the command is applied to pages belonging to a locked region or to the bootloader protected area.
Note:
The FLASHC error status returned by flashc_is_lock_error and flashc_is_programming_error is updated.
Definition at line 706 of file flashc.c.
References flashc_memset32().
Referenced by flashc_memset8().
{
    return flashc_memset32(dst, src | (uint32_t)src << 16, nbytes, erase);
}
volatile void* flashc_memset32 (volatile void * dst, uint32_t src, size_t nbytes, bool erase)
Copies nbytes bytes to the flash destination pointed to by dst from the repeated src big-endian source word.
All pointer and size alignments are supported.
Parameters:
dst Pointer to flash destination.
src Source word.
nbytes Number of bytes to set.
erase Whether to erase before writing: true or false.
Returns:
The value of dst.
Warning:
This function may be called with erase set to false only if the destination consists only of erased words, i.e. this function can not be used to write only one bit of a previously written word. E.g., if 0x00000001 then 0xFFFFFFFE are written to a word, the resulting value in flash may be different from 0x00000000.
A Lock Error is issued if the command is applied to pages belonging to a locked region or to the bootloader protected area.
Note:
The FLASHC error status returned by flashc_is_lock_error and flashc_is_programming_error is updated.
Definition at line 712 of file flashc.c.
References flashc_memset64().
Referenced by flashc_memset16().
{
    return flashc_memset64(dst, src | (uint64_t)src << 32, nbytes, erase);
}
volatile void* flashc_memset64 (volatile void * dst, uint64_t src, size_t nbytes, bool erase)
Copies nbytes bytes to the flash destination pointed to by dst from the repeated src big-endian source double-word.
All pointer and size alignments are supported.
Parameters:
dst Pointer to flash destination.
src Source double-word.
nbytes Number of bytes to set.
erase Whether to erase before writing: true or false.
Returns:
The value of dst.
Warning:
This function may be called with erase set to false only if the destination consists only of erased words, i.e. this function can not be used to write only one bit of a previously written word. E.g., if 0x00000001 then 0xFFFFFFFE are written to a word, the resulting value in flash may be different from 0x00000000.
A Lock Error is issued if the command is applied to pages belonging to a locked region or to the bootloader protected area.
Note:
The FLASHC error status returned by flashc_is_lock_error and flashc_is_programming_error is updated.
Definition at line 718 of file flashc.c.
References Align_down, flashc_clear_page_buffer(), flashc_erase_page(), flashc_erase_user_page(), flashc_error_status, flashc_get_flash_size(), flashc_write_page(), flashc_write_user_page(), Get_align, min, Test_align, StructCVPtr::u16ptr, StructCVPtr::u32ptr, Union64::u64, UnionVPtr::u64ptr, UnionCVPtr::u64ptr, StructCVPtr::u64ptr, Union64::u8, StructCVPtr::u8ptr, UnionVPtr::u8ptr, and UnionCVPtr::u8ptr.
Referenced by flashc_memset32().
{
    // Use aggregated pointers to have several alignments available for a same address.
    UnionCVPtr flash_array_end;
    UnionVPtr dest;
    Union64 source = {0};
    StructCVPtr dest_end;
    UnionCVPtr flash_page_source_end;
    bool incomplete_flash_page_end;
    Union64 flash_dword;
    UnionVPtr tmp;
    unsigned int error_status = 0;
    unsigned int i;
    // Reformat arguments.
    flash_array_end.u8ptr = AVR32_FLASH + flashc_get_flash_size();
    dest.u8ptr = dst;
    for (i = (Get_align((uint32_t)dest.u8ptr, sizeof(uint64_t)) - 1) & (sizeof(uint64_t) - 1);
            src; i = (i - 1) & (sizeof(uint64_t) - 1)) {
        source.u8[i] = src;
        src >>= 8;
    }
    dest_end.u8ptr = dest.u8ptr + nbytes;
    // If destination is outside flash, go to next flash page if any.
    if (dest.u8ptr < AVR32_FLASH) {
        dest.u8ptr = AVR32_FLASH;
    } else if (flash_array_end.u8ptr <= dest.u8ptr && dest.u8ptr < AVR32_FLASHC_USER_PAGE) {
        dest.u8ptr = AVR32_FLASHC_USER_PAGE;
    }
    // If end of destination is outside flash, move it to the end of the previous flash page if any.
    if (dest_end.u8ptr > AVR32_FLASHC_USER_PAGE + AVR32_FLASHC_USER_PAGE_SIZE) {
        dest_end.u8ptr = AVR32_FLASHC_USER_PAGE + AVR32_FLASHC_USER_PAGE_SIZE;
    } else if (AVR32_FLASHC_USER_PAGE >= dest_end.u8ptr && dest_end.u8ptr > flash_array_end.u8ptr) {
        dest_end.u8ptr = flash_array_end.u8ptr;
    }
    // Align each end of destination pointer with its natural boundary.
    dest_end.u16ptr = (uint16_t *)Align_down((uint32_t)dest_end.u8ptr, sizeof(uint16_t));
    dest_end.u32ptr = (uint32_t *)Align_down((uint32_t)dest_end.u16ptr, sizeof(uint32_t));
    dest_end.u64ptr = (uint64_t *)Align_down((uint32_t)dest_end.u32ptr, sizeof(uint64_t));
    // While end of destination is not reached...
    while (dest.u8ptr < dest_end.u8ptr) {
        // Clear the page buffer in order to prepare data for a flash page write.
        flashc_clear_page_buffer();
        error_status |= flashc_error_status;
        // Determine where the source data will end in the current flash page.
        flash_page_source_end.u64ptr =
                (uint64_t *)min((uint32_t)dest_end.u64ptr,
                Align_down((uint32_t)dest.u8ptr, AVR32_FLASHC_PAGE_SIZE) + AVR32_FLASHC_PAGE_SIZE);
        // Determine if the current destination page has an incomplete end.
        incomplete_flash_page_end = (Align_down((uint32_t)dest.u8ptr, AVR32_FLASHC_PAGE_SIZE) >=
                Align_down((uint32_t)dest_end.u8ptr, AVR32_FLASHC_PAGE_SIZE));
        // Use a flash double-word buffer to manage unaligned accesses.
        flash_dword.u64 = source.u64;
        // If destination does not point to the beginning of the current flash page...
        if (!Test_align((uint32_t)dest.u8ptr, AVR32_FLASHC_PAGE_SIZE)) {
            // Fill the beginning of the page buffer with the current flash page data.
            // This is required by the hardware, even if page erase is not requested,
            // in order to be able to write successfully to erased parts of flash
            // pages that have already been written to.
            for (tmp.u8ptr = (uint8_t *)Align_down((uint32_t)dest.u8ptr, AVR32_FLASHC_PAGE_SIZE);
                    tmp.u64ptr < (uint64_t *)Align_down((uint32_t)dest.u8ptr, sizeof(uint64_t));
                    tmp.u64ptr++) {
                *tmp.u64ptr = *tmp.u64ptr;
            }
            // If destination is not 64-bit aligned...
            if (!Test_align((uint32_t)dest.u8ptr, sizeof(uint64_t))) {
                // Fill the beginning of the flash double-word buffer with the current
                // flash page data.
                // This is required by the hardware, even if page erase is not
                // requested, in order to be able to write successfully to erased parts
                // of flash pages that have already been written to.
                for (i = 0; i < Get_align((uint32_t)dest.u8ptr, sizeof(uint64_t)); i++) {
                    flash_dword.u8[i] = *tmp.u8ptr++;
                }
                // Align the destination pointer with its 64-bit boundary.
                dest.u64ptr = (uint64_t *)Align_down((uint32_t)dest.u8ptr, sizeof(uint64_t));
                // If the current destination double-word is not the last one...
                if (dest.u64ptr < dest_end.u64ptr) {
                    // Write the flash double-word buffer to the page buffer and reinitialize it.
                    *dest.u64ptr++ = flash_dword.u64;
                    flash_dword.u64 = source.u64;
                }
            }
        }
        // Write the source data to the page buffer with 64-bit alignment.
        for (i = flash_page_source_end.u64ptr - dest.u64ptr; i; i--) {
            *dest.u64ptr++ = source.u64;
        }
        // If the current destination page has an incomplete end...
        if (incomplete_flash_page_end) {
            // This is required by the hardware, even if page erase is not requested,
            // in order to be able to write successfully to erased parts of flash
            // pages that have already been written to.
            {
                tmp.u8ptr = (volatile uint8_t *)dest_end.u8ptr;
                // If end of destination is not 64-bit aligned...
                if (!Test_align((uint32_t)dest_end.u8ptr, sizeof(uint64_t))) {
                    // Fill the end of the flash double-word buffer with the current flash page data.
                    for (i = Get_align((uint32_t)dest_end.u8ptr, sizeof(uint64_t)); i < sizeof(uint64_t); i++)
                        flash_dword.u8[i] = *tmp.u8ptr++;
                    // Write the flash double-word buffer to the page buffer.
                    *dest.u64ptr++ = flash_dword.u64;
                }
                // Fill the end of the page buffer with the current flash page data.
                for (; !Test_align((uint32_t)tmp.u64ptr, AVR32_FLASHC_PAGE_SIZE); tmp.u64ptr++) {
                    *tmp.u64ptr = *tmp.u64ptr;
                }
            }
        }
        // If the current flash page is in the flash array...
        if (dest.u8ptr <= AVR32_FLASHC_USER_PAGE) {
            // Erase the current page if requested and write it from the page buffer.
            if (erase) {
                flashc_erase_page(-1, false);
                error_status |= flashc_error_status;
            }
            flashc_write_page(-1);
            error_status |= flashc_error_status;
            // If the end of the flash array is reached, go to the User page.
            if (dest.u8ptr >= flash_array_end.u8ptr) {
                dest.u8ptr = AVR32_FLASHC_USER_PAGE;
            }
        } else {
            // Erase the User page if requested and write it from the page buffer.
            if (erase) {
                flashc_erase_user_page(false);
                error_status |= flashc_error_status;
            }
            flashc_write_user_page();
            error_status |= flashc_error_status;
        }
    }
    // Update the FLASHC error status.
    flashc_error_status = error_status;
    // Return the initial destination pointer as the standard memset function does.
    return dst;
}
volatile void* flashc_memset8 (volatile void * dst, uint8_t src, size_t nbytes, bool erase)
Copies nbytes bytes to the flash destination pointed to by dst from the repeated src source byte.
All pointer and size alignments are supported.
Parameters:
dst Pointer to flash destination.
src Source byte.
nbytes Number of bytes to set.
erase Whether to erase before writing: true or false.
Returns:
The value of dst.
Warning:
This function may be called with erase set to false only if the destination consists only of erased words, i.e. this function can not be used to write only one bit of a previously written word. E.g., if 0x00000001 then 0xFFFFFFFE are written to a word, the resulting value in flash may be different from 0x00000000.
A Lock Error is issued if the command is applied to pages belonging to a locked region or to the bootloader protected area.
Note:
The FLASHC error status returned by flashc_is_lock_error and flashc_is_programming_error is updated.
Definition at line 700 of file flashc.c.
References flashc_memset16().
{
    return flashc_memset16(dst, src | (uint16_t)src << 8, nbytes, erase);
}
void flashc_no_operation (void)
Issues a No Operation command to the FLASHC.
Note:
The FLASHC error status returned by flashc_is_lock_error and flashc_is_programming_error is updated.
Definition at line 312 of file flashc.c.
References flashc_issue_command().
{
    flashc_issue_command(AVR32_FLASHC_FCMD_CMD_NOP, -1);
}
bool flashc_quick_page_read (int page_number)
Applies the Quick Page Read command to a page.
Parameters:
page_number The page number:
0 to (flashc_get_page_count() - 1): a page number within the flash array;
< 0: the current page number.
Returns:
Whether the specified page is erased.
Note:
The FLASHC error status returned by flashc_is_lock_error and flashc_is_programming_error is updated.
Definition at line 638 of file flashc.c.
References flashc_is_page_erased(), and flashc_issue_command().
Referenced by flashc_erase_page().
{
    flashc_issue_command(AVR32_FLASHC_FCMD_CMD_QPR, page_number);
    return flashc_is_page_erased();
}
bool flashc_quick_user_page_read (void)
Issues a Quick Page Read User Page command to the FLASHC.
Returns:
Whether the User page is erased.
Note:
The FLASHC error status returned by flashc_is_lock_error and flashc_is_programming_error is updated.
Definition at line 680 of file flashc.c.
References flashc_is_page_erased(), and flashc_issue_command().
Referenced by flashc_erase_user_page().
{
    flashc_issue_command(AVR32_FLASHC_FCMD_CMD_QPRUP, -1);
    return flashc_is_page_erased();
}
uint64_t flashc_read_all_gp_fuses (void)
Reads all general-purpose fuses.
Returns:
The value of all general-purpose fuses as a word.
Note:
The actual number of general-purpose fuse bits implemented by hardware is given by AVR32_FLASHC_GPF_NUM. The other bits among the 64 are fixed at 1 by hardware.
Definition at line 444 of file flashc.c.
Referenced by flashc_erase_all_gp_fuses(), flashc_erase_gp_fuse_byte(), flashc_read_gp_fuse_bit(), flashc_read_gp_fuse_bitfield(), and flashc_read_gp_fuse_byte().
{
    return AVR32_FLASHC.fgpfrlo | (uint64_t)AVR32_FLASHC.fgpfrhi << 32;
}
bool flashc_read_gp_fuse_bit (unsigned int gp_fuse_bit)
Reads a general-purpose fuse bit.
Parameters:
gp_fuse_bit The general-purpose fuse bit: 0 to 63.
Returns:
The value of the specified general-purpose fuse bit.
Note:
The actual number of general-purpose fuse bits implemented by hardware is given by AVR32_FLASHC_GPF_NUM. The other bits among the 64 are fixed at 1 by hardware.
Definition at line 426 of file flashc.c.
References flashc_read_all_gp_fuses().
Referenced by flashc_erase_gp_fuse_bit(), and flashc_is_external_privileged_fetch_locked().
{
    return ((flashc_read_all_gp_fuses() & 1ULL << (gp_fuse_bit & 0x3F)) != 0);
}
uint64_t flashc_read_gp_fuse_bitfield (unsigned int pos, unsigned int width)
Reads a general-purpose fuse bit-field.
Parameters:
pos The bit-position of the general-purpose fuse bit-field: 0 to 63.
width The bit-width of the general-purpose fuse bit-field: 0 to 64.
Returns:
The value of the specified general-purpose fuse bit-field.
Note:
The actual number of general-purpose fuse bits implemented by hardware is given by AVR32_FLASHC_GPF_NUM. The other bits among the 64 are fixed at 1 by hardware.
Definition at line 432 of file flashc.c.
References flashc_read_all_gp_fuses(), and min.
Referenced by flashc_erase_gp_fuse_bitfield(), and flashc_get_bootloader_protected_size().
{
    return flashc_read_all_gp_fuses() >> (pos & 0x3F) & ((1ULL << min(width, 64)) - 1);
}
uint8_t flashc_read_gp_fuse_byte (unsigned int gp_fuse_byte)
Reads a general-purpose fuse byte.
Parameters:
gp_fuse_byte The general-purpose fuse byte: 0 to 7.
Returns:
The value of the specified general-purpose fuse byte.
Note:
The actual number of general-purpose fuse bits implemented by hardware is given by AVR32_FLASHC_GPF_NUM. The other bits among the 64 are fixed at 1 by hardware.
Definition at line 438 of file flashc.c.
References flashc_read_all_gp_fuses().
Referenced by flashc_erase_gp_fuse_byte().
{
    return flashc_read_all_gp_fuses() >> ((gp_fuse_byte & 0x07) << 3);
}
void flashc_set_all_gp_fuses (uint64_t value)
Sets all general-purpose fuses with the appropriate erase and write operations.
Parameters:
value The value of all general-purpose fuses as a word.
Warning:
A Lock Error is issued if the Security bit is active.
Note:
The FLASHC error status returned by flashc_is_lock_error and flashc_is_programming_error is updated.
The actual number of general-purpose fuse bits implemented by hardware is given by AVR32_FLASHC_GPF_NUM. The other bits among the 64 are fixed at 1 by hardware.
Definition at line 595 of file flashc.c.
References flashc_erase_all_gp_fuses(), flashc_error_status, and flashc_write_all_gp_fuses().
{
    unsigned int error_status;
    switch (value) {
    case 0xFFFFFFFFFFFFFFFFULL:
        flashc_erase_all_gp_fuses(false);
        break;
    case 0x0000000000000000ULL:
        flashc_write_all_gp_fuses(0x0000000000000000ULL);
        break;
    default:
        flashc_erase_all_gp_fuses(false);
        error_status = flashc_error_status;
        flashc_write_all_gp_fuses(value);
        flashc_error_status |= error_status;
        break;
    }
}
unsigned int flashc_set_bootloader_protected_size (unsigned int bootprot_size)
Sets the bootloader protected size.
Parameters:
bootprot_size The wanted bootloader protected size in bytes. If this size is not supported, the actual size will be the nearest greater available size or the maximal possible size if the requested size is too large.
Returns:
The actual bootloader protected size in bytes.
Warning:
A Lock Error is issued if the Security bit is active.
Note:
The FLASHC error status returned by flashc_is_lock_error and flashc_is_programming_error is updated.
Definition at line 353 of file flashc.c.
References clz, flashc_get_bootloader_protected_size(), flashc_set_gp_fuse_bitfield(), max, and min.
{
    flashc_set_gp_fuse_bitfield(AVR32_FLASHC_FGPFRLO_BOOTPROT_OFFSET,
            AVR32_FLASHC_FGPFRLO_BOOTPROT_SIZE,
            (1 << AVR32_FLASHC_FGPFRLO_BOOTPROT_SIZE) - 1 -
            ((bootprot_size) ?
            32 - clz((((min(max(bootprot_size, AVR32_FLASHC_PAGE_SIZE << 1),
            AVR32_FLASHC_PAGE_SIZE <<
            ((1 << AVR32_FLASHC_FGPFRLO_BOOTPROT_SIZE) - 1)) +
            AVR32_FLASHC_PAGE_SIZE - 1) /
            AVR32_FLASHC_PAGE_SIZE) << 1) - 1) - 1 :
            0));
    return flashc_get_bootloader_protected_size();
}
void flashc_set_bus_freq (unsigned int cpu_f_hz)
Depending on the CPU frequency, set the wait states of flash read accesses.
Parameters:
cpu_f_hz The CPU frequency
Definition at line 155 of file flashc.c.
References flashc_set_wait_state().
{
    if (cpu_f_hz >= AVR32_FLASHC_FWS_0_MAX_FREQ) {
        // Set 1 WS.
        flashc_set_wait_state(1);
    } else {
        // Set 0 WS.
        flashc_set_wait_state(0);
    }
}
void flashc_set_flash_waitstate_and_readmode (unsigned long cpu_f_hz)
Depednding to the CPU frequency, set the wait states of flash read accesses and enable or disable the High speed read mode.
Parameters:
cpu_f_hz The CPU frequency
Referenced by pcl_configure_synchronous_clocks(), and pcl_switch_to_osc().
void flashc_set_gp_fuse_bit (unsigned int gp_fuse_bit, bool value)
Sets a general-purpose fuse bit with the appropriate erase and write operations.
Parameters:
gp_fuse_bit The general-purpose fuse bit: 0 to 63.
value The value of the specified general-purpose fuse bit.
Warning:
A Lock Error is issued if the Security bit is active and the command is applied to BOOTPROT or EPFL fuses.
Note:
The FLASHC error status returned by flashc_is_lock_error and flashc_is_programming_error is updated.
The actual number of general-purpose fuse bits implemented by hardware is given by AVR32_FLASHC_GPF_NUM. The other bits among the 64 are fixed at 1 by hardware.
Definition at line 545 of file flashc.c.
References flashc_erase_gp_fuse_bit(), and flashc_write_gp_fuse_bit().
Referenced by flashc_lock_external_privileged_fetch(), and flashc_set_gp_fuse_bitfield().
{
    if (value) {
        flashc_erase_gp_fuse_bit(gp_fuse_bit, false);
    } else {
        flashc_write_gp_fuse_bit(gp_fuse_bit, false);
    }
}
void flashc_set_gp_fuse_bitfield (unsigned int pos, unsigned int width, uint64_t value)
Sets a general-purpose fuse bit-field with the appropriate erase and write operations.
Parameters:
pos The bit-position of the general-purpose fuse bit-field: 0 to 63.
width The bit-width of the general-purpose fuse bit-field: 0 to 64.
value The value of the specified general-purpose fuse bit-field.
Warning:
A Lock Error is issued if the Security bit is active and the command is applied to BOOTPROT or EPFL fuses.
Note:
The FLASHC error status returned by flashc_is_lock_error and flashc_is_programming_error is updated.
The actual number of general-purpose fuse bits implemented by hardware is given by AVR32_FLASHC_GPF_NUM. The other bits among the 64 are fixed at 1 by hardware.
Definition at line 555 of file flashc.c.
References flashc_error_status, flashc_set_gp_fuse_bit(), and min.
Referenced by flashc_set_bootloader_protected_size().
{
    unsigned int error_status = 0;
    unsigned int gp_fuse_bit;
    pos &= 0x3F;
    width = min(width, 64);
    for (gp_fuse_bit = pos; gp_fuse_bit < pos + width; gp_fuse_bit++, value >>= 1) {
        flashc_set_gp_fuse_bit(gp_fuse_bit, value & 0x01);
        error_status |= flashc_error_status;
    }
    flashc_error_status = error_status;
}
void flashc_set_gp_fuse_byte (unsigned int gp_fuse_byte, uint8_t value)
Sets a general-purpose fuse byte with the appropriate erase and write operations.
Parameters:
gp_fuse_byte The general-purpose fuse byte: 0 to 7.
value The value of the specified general-purpose fuse byte.
Warning:
A Lock Error is issued if the Security bit is active.
Note:
The FLASHC error status returned by flashc_is_lock_error and flashc_is_programming_error is updated.
The actual number of general-purpose fuse bits implemented by hardware is given by AVR32_FLASHC_GPF_NUM. The other bits among the 64 are fixed at 1 by hardware.
Definition at line 572 of file flashc.c.
References flashc_erase_gp_fuse_byte(), flashc_error_status, and flashc_write_gp_fuse_byte().
{
    unsigned int error_status;
    switch (value) {
    case 0xFF:
        flashc_erase_gp_fuse_byte(gp_fuse_byte, false);
        break;
    case 0x00:
        flashc_write_gp_fuse_byte(gp_fuse_byte, 0x00);
        break;
    default:
        flashc_erase_gp_fuse_byte(gp_fuse_byte, false);
        error_status = flashc_error_status;
        flashc_write_gp_fuse_byte(gp_fuse_byte, value);
        flashc_error_status |= error_status;
        break;
    }
}
void flashc_set_wait_state (unsigned int wait_state)
Sets the number of wait states of flash read accesses.
Parameters:
wait_state The number of wait states of flash read accesses: 0 to 1.
Definition at line 147 of file flashc.c.
References u_avr32_flashc_fcr_t::FCR, and u_avr32_flashc_fcr_t::fcr.
{
    u_avr32_flashc_fcr_t u_avr32_flashc_fcr = {AVR32_FLASHC.fcr};
    u_avr32_flashc_fcr.FCR.fws = wait_state;
    AVR32_FLASHC.fcr = u_avr32_flashc_fcr.fcr;
}
void flashc_write_all_gp_fuses (uint64_t value)
Writes all general-purpose fuses.
Parameters:
value The value of all general-purpose fuses as a word.
Warning:
A Lock Error is issued if the Security bit is active.
Note:
The FLASHC error status returned by flashc_is_lock_error and flashc_is_programming_error is updated.
A write operation can only clear bits; in other words, an erase operation must first be done if some bits need to be set to 1.
The actual number of general-purpose fuse bits implemented by hardware is given by AVR32_FLASHC_GPF_NUM. The other bits among the 64 are fixed at 1 by hardware.
Definition at line 531 of file flashc.c.
References flashc_error_status, and flashc_write_gp_fuse_byte().
Referenced by flashc_set_all_gp_fuses().
{
    unsigned int error_status = 0;
    unsigned int gp_fuse_byte;
    for (gp_fuse_byte = 0; gp_fuse_byte < 8; gp_fuse_byte++, value >>= 8) {
        flashc_write_gp_fuse_byte(gp_fuse_byte, value);
        error_status |= flashc_error_status;
    }
    flashc_error_status = error_status;
}
void flashc_write_gp_fuse_bit (unsigned int gp_fuse_bit, bool value)
Writes a general-purpose fuse bit.
Parameters:
gp_fuse_bit The general-purpose fuse bit: 0 to 63.
value The value of the specified general-purpose fuse bit.
Warning:
A Lock Error is issued if the Security bit is active and the command is applied to BOOTPROT or EPFL fuses.
Note:
The FLASHC error status returned by flashc_is_lock_error and flashc_is_programming_error is updated.
A write operation can only clear bits; in other words, an erase operation must first be done if some bits need to be set to 1.
The actual number of general-purpose fuse bits implemented by hardware is given by AVR32_FLASHC_GPF_NUM. The other bits among the 64 are fixed at 1 by hardware.
Definition at line 500 of file flashc.c.
References flashc_issue_command().
Referenced by flashc_set_gp_fuse_bit(), and flashc_write_gp_fuse_bitfield().
{
    if (!value) {
        flashc_issue_command(AVR32_FLASHC_FCMD_CMD_WGPB, gp_fuse_bit & 0x3F);
    }
}
void flashc_write_gp_fuse_bitfield (unsigned int pos, unsigned int width, uint64_t value)
Writes a general-purpose fuse bit-field.
Parameters:
pos The bit-position of the general-purpose fuse bit-field: 0 to 63.
width The bit-width of the general-purpose fuse bit-field: 0 to 64.
value The value of the specified general-purpose fuse bit-field.
Warning:
A Lock Error is issued if the Security bit is active and the command is applied to BOOTPROT or EPFL fuses.
Note:
The FLASHC error status returned by flashc_is_lock_error and flashc_is_programming_error is updated.
A write operation can only clear bits; in other words, an erase operation must first be done if some bits need to be set to 1.
The actual number of general-purpose fuse bits implemented by hardware is given by AVR32_FLASHC_GPF_NUM. The other bits among the 64 are fixed at 1 by hardware.
Definition at line 508 of file flashc.c.
References flashc_error_status, flashc_write_gp_fuse_bit(), and min.
{
    unsigned int error_status = 0;
    unsigned int gp_fuse_bit;
    pos &= 0x3F;
    width = min(width, 64);
    for (gp_fuse_bit = pos; gp_fuse_bit < pos + width; gp_fuse_bit++, value >>= 1) {
        flashc_write_gp_fuse_bit(gp_fuse_bit, value & 0x01);
        error_status |= flashc_error_status;
    }
    flashc_error_status = error_status;
}
void flashc_write_gp_fuse_byte (unsigned int gp_fuse_byte, uint8_t value)
Writes a general-purpose fuse byte.
Parameters:
gp_fuse_byte The general-purpose fuse byte: 0 to 7.
value The value of the specified general-purpose fuse byte.
Warning:
A Lock Error is issued if the Security bit is active.
Note:
The FLASHC error status returned by flashc_is_lock_error and flashc_is_programming_error is updated.
A write operation can only clear bits; in other words, an erase operation must first be done if some bits need to be set to 1.
The actual number of general-purpose fuse bits implemented by hardware is given by AVR32_FLASHC_GPF_NUM. The other bits among the 64 are fixed at 1 by hardware.
Definition at line 525 of file flashc.c.
References flashc_issue_command().
Referenced by flashc_erase_gp_fuse_byte(), flashc_set_gp_fuse_byte(), and flashc_write_all_gp_fuses().
{
    flashc_issue_command(AVR32_FLASHC_FCMD_CMD_PGPFB, (gp_fuse_byte & 0x07) | value << 3);
}
void flashc_write_page (int page_number)
Writes a page from the page buffer.
Parameters:
page_number The page number:
0 to (flashc_get_page_count() - 1): a page number within the flash array;
< 0: the current page number.
Warning:
A Lock Error is issued if the command is applied to a page belonging to a locked region or to the bootloader protected area.
The page buffer is not automatically reset after a page write.
Note:
The FLASHC error status returned by flashc_is_lock_error and flashc_is_programming_error is updated.
A write operation can only clear bits; in other words, an erase operation must first be done if some bits need to be set to 1.
Definition at line 674 of file flashc.c.
References flashc_issue_command().
Referenced by flashc_memcpy(), and flashc_memset64().
{
    flashc_issue_command(AVR32_FLASHC_FCMD_CMD_WP, page_number);
}
void flashc_write_user_page (void)
Writes the User page from the page buffer.
Warning:
The page buffer is not automatically reset after a page write.
Note:
The FLASHC error status returned by flashc_is_lock_error and flashc_is_programming_error is updated.
A write operation can only clear bits; in other words, an erase operation must first be done if some bits need to be set to 1.
Definition at line 694 of file flashc.c.
References flashc_issue_command().
Referenced by flashc_memcpy(), and flashc_memset64().
{
    flashc_issue_command(AVR32_FLASHC_FCMD_CMD_WUP, -1);
}
Variable Documentation
unsigned int flashc_error_status = 0 [static]
Sticky error status of the FLASHC.
This variable is updated by functions that issue FLASHC commands. It contains the cumulated FLASHC error status of all the FLASHC commands issued by a function.
Definition at line 252 of file flashc.c.
Referenced by flashc_erase_all_pages(), flashc_erase_gp_fuse_bitfield(), flashc_erase_gp_fuse_byte(), flashc_erase_page(), flashc_is_lock_error(), flashc_is_programming_error(), flashc_issue_command(), flashc_lock_all_regions(), flashc_memcpy(), flashc_memset64(), flashc_set_all_gp_fuses(), flashc_set_gp_fuse_bitfield(), flashc_set_gp_fuse_byte(), flashc_write_all_gp_fuses(), and flashc_write_gp_fuse_bitfield().
void(*volatile flashc_wait_until_ready)(void)
Pointer to the function used by the driver when it needs to wait until the FLASHC is ready to run a new command.
The default function is flashc_default_wait_until_ready. The user may change this pointer to use another implementation.
Definition at line 228 of file flashc.c.
Referenced by flashc_issue_command().