OS: main.c File Reference
main.c File Reference
#include "board.h"
#include "pm.h"
#include "gpio.h"
#include "os_core.h"
Data Structures
struct task_args
Defines
#define CPU_HZ FOSC0
Functions
void led_blink (void *raw_args)
void led_on ()
int main (void)
void task2 (void *args)
Variables
static struct os_event event
static struct os_interrupt int_1
static struct os_mutex mutex
static struct os_semaphore sem
struct os_task task_1 task_2 task_3 task_4
Define Documentation
#define CPU_HZ FOSC0
Definition at line 6 of file main.c.
Referenced by main().
Function Documentation
void led_blink (void * raw_args)
Definition at line 22 of file main.c.
References task_args::delay_ms, event, gpio_tgl_gpio_pin(), mutex, OS_MS_TO_TICK, os_mutex_unlock(), os_task_delay(), os_task_get_current(), os_task_sleep(), and task_args::pin.
Referenced by main().
{
    struct task_args *args = (struct task_args *) raw_args;
    while (1) {
        os_task_sleep(os_task_get_current(), &event);
        gpio_tgl_gpio_pin(args->pin);
        os_task_delay(OS_MS_TO_TICK(args->delay_ms));
        //os_semaphore_release(&sem);
        os_mutex_unlock(&mutex);
    }
}
void led_on ()
Definition at line 47 of file main.c.
References gpio_clr_gpio_pin(), and LED3_GPIO.
{
    gpio_clr_gpio_pin(LED3_GPIO);
}
int main (void)
Definition at line 52 of file main.c.
References CPU_HZ, task_args::delay_ms, event, FOSC0, int_1, LED0_GPIO, LED1_GPIO, LED2_GPIO, LED3_GPIO, led_blink(), mutex, os_interrupt_setup(), os_mutex_create(), os_mutex_create_event(), os_semaphore_create(), os_start(), os_task_create(), OS_TASK_DEFAULT, OSC0_STARTUP, pm_switch_to_osc0(), sem, task2(), and task_4.
{
    struct task_args args_1 = {
        .delay_ms = 100,
        .pin = LED0_GPIO
    };
    struct task_args args_2 = {
        .delay_ms = 100,
        .pin = LED1_GPIO
    };
    struct task_args args_3 = {
        .delay_ms = 100,
        .pin = LED2_GPIO
    };
    struct task_args args_4 = {
        .delay_ms = 100,
        .pin = LED3_GPIO
    };
    pm_switch_to_osc0(&AVR32_PM, FOSC0, OSC0_STARTUP);
    os_semaphore_create(&sem, 2, 2);
    //os_semaphore_create_event(&event, &sem);
    os_mutex_create(&mutex);
    os_mutex_create_event(&event, &mutex);
    os_interrupt_setup(&int_1, task2, NULL);
    os_task_create(&task_1, led_blink, &args_1, 500, OS_TASK_DEFAULT);
    os_task_create(&task_2, led_blink, &args_2, 500, OS_TASK_DEFAULT);
    os_task_create(&task_3, led_blink, &args_3, 500, OS_TASK_DEFAULT);
    os_task_create(&task_4, led_blink, &args_4, 500, OS_TASK_DEFAULT);
    //os_task_create(&task_4, task2, NULL, 500, OS_TASK_DEFAULT);
    //os_task_set_priority(&task_2, OS_PRIORITY_2);
    os_start(CPU_HZ);
}
void task2 (void * args)
Definition at line 35 of file main.c.
References gpio_tgl_gpio_pin(), LED3_GPIO, OS_MS_TO_TICK, os_statistics_get_task_switch_time(), os_statistics_get_task_switch_time_jitter(), and os_task_delay().
Referenced by main().
{
    volatile static uint32_t task_switch;
    volatile static uint32_t jitter;
    while (1) {
        gpio_tgl_gpio_pin(LED3_GPIO);
        os_task_delay(OS_MS_TO_TICK(500));
        task_switch = os_statistics_get_task_switch_time();
        jitter = os_statistics_get_task_switch_time_jitter();
    }
}
Variable Documentation
struct os_event event [static]
Definition at line 13 of file main.c.
Referenced by __os_event_enable(), led_blink(), main(), and os_event_scheduler().
struct os_interrupt int_1 [static]
Definition at line 10 of file main.c.
Referenced by main().
struct os_mutex mutex [static]
Definition at line 12 of file main.c.
Referenced by __os_event_mutex_is_triggered(), led_blink(), and main().
struct os_semaphore sem [static]
Definition at line 11 of file main.c.
Referenced by main(), and os_event_sempahore_is_triggered().
struct os_task task_1 task_2 task_3 task_4
Definition at line 8 of file main.c.
Referenced by main().