eeOS (Embedded Event-driven Operating System): os_statistics.c File Reference
os_statistics.c File Reference
eeOS Statistics
#include "os_core.h"
Functions
void __os_statistics_switch_context_start (os_cy_t offset_cy)
void __os_statistics_switch_context_stop (os_cy_t offset_cy)
void __os_statistics_switch_context_tick_handler_start (os_cy_t offset_cy)
void __os_statistics_switch_context_tick_handler_stop (os_cy_t offset_cy)
static void measure_context_task_switch_time_start (os_cy_t current_cy)
Start monitoring the task switch time.
static void measure_context_task_switch_time_stop (os_cy_t current_cy)
Stop monitoring the task switch time.
os_cy_t os_statistics_get_task_switch_time (void)
Get the average time of the context task switching in number of cycles.
os_cy_t os_statistics_get_task_switch_time_jitter (void)
Get the jitter of the context task switching in number of cycles.
uint8_t os_statistics_task_cpu_allocation (struct os_task *task)
Theoretical estimation of the CPU load of a task. It is based on the number of current active tasks in the list and their priority. The ratio of the CPU ressources is calculated as follow:
static void update_task_cycle_counter_start (os_cy_t current_cy)
Start monitoring the task activity time.
static void update_task_cycle_counter_stop (os_cy_t current_cy)
Stop monitoring the task activity time.
Variables
static os_cy_t task_cy = 0
Temporary variable to compute the task activity time.
static os_cy_t task_switch_cy
Temporary variable holding the number of cycles for the last task switch.
static os_cy_t task_switch_max_cy = 0
static os_cy_t task_switch_min_cy = (os_cy_t) -1
Detailed Description
eeOS Statistics
Author:
Blaise Lengrand (blaise.lengrand@gmail.com)
Version:
0.1
Date:
2011
License
eeOS is provided in source form for FREE evaluation, for educational use or for peaceful research. If you plan on using eeOS in a commercial product you need to contact the author to properly license its use in your product. The fact that the source is provided does NOT mean that you can use it without paying a licensing fee.
Definition in file os_statistics.c.
Function Documentation
void __os_statistics_switch_context_start (os_cy_t offset_cy)
Hook used to get the time information at the entrance of a context task switch (when using os_yield).
Parameters:
offset_cy The number of cycles between the function call and the call of __HOOK_OS_STATISTICS_SWITCH_CONTEXT_START
Definition at line 87 of file os_statistics.c.
References os_read_cycle_counter(), and update_task_cycle_counter_start().
{
    /* Get the current cycle count */
    os_cy_t current_cy = os_read_cycle_counter() - offset_cy;
    /* Start monitoring the task activity time */
    update_task_cycle_counter_start(current_cy);
}
void __os_statistics_switch_context_stop (os_cy_t offset_cy)
Hook used to get the time information at the exit of a context task switch (when using os_yield).
Parameters:
offset_cy The number of cycles between the call of __HOOK_OS_STATISTICS_SWITCH_CONTEXT_STOP and the exit of the function.
Definition at line 94 of file os_statistics.c.
References os_read_cycle_counter(), and update_task_cycle_counter_stop().
{
    /* Get the current cycle count */
    os_cy_t current_cy = os_read_cycle_counter() + offset_cy;
    /* Stop monitoring the task activity time */
    update_task_cycle_counter_stop(current_cy);
}
void __os_statistics_switch_context_tick_handler_start (os_cy_t offset_cy)
Hook used to get the time information at the entrance of a context task switch (tick interrupt handler).
Parameters:
offset_cy The number of cycles between the interrupt call and the call of __HOOK_OS_STATISTICS_SWITCH_CONTEXT_TICK_HANDLER_START
Definition at line 70 of file os_statistics.c.
References measure_context_task_switch_time_start(), os_read_cycle_counter(), and update_task_cycle_counter_start().
{
    /* Get the current cycle count */
    os_cy_t current_cy = os_read_cycle_counter() - offset_cy;
    /* Start monitoring the task switch and task activity time */
    measure_context_task_switch_time_start(current_cy);
    update_task_cycle_counter_start(current_cy);
}
void __os_statistics_switch_context_tick_handler_stop (os_cy_t offset_cy)
Hook used to get the time information at the exit of a context task switch (tick interrupt handler).
Parameters:
offset_cy The number of cycles between the call of __HOOK_OS_STATISTICS_SWITCH_CONTEXT_TICK_HANDLER_STOP and the exit of the interrupt handler.
Definition at line 78 of file os_statistics.c.
References measure_context_task_switch_time_stop(), os_read_cycle_counter(), and update_task_cycle_counter_stop().
{
    /* Get the current cycle count */
    os_cy_t current_cy = os_read_cycle_counter() + offset_cy;
    /* Stop monitoring the task switch and task activity time */
    measure_context_task_switch_time_stop(current_cy);
    update_task_cycle_counter_stop(current_cy);
}
static void measure_context_task_switch_time_start (os_cy_t current_cy) [inline, static]
Start monitoring the task switch time.
Parameters:
current_cy Current number of cycles
Definition at line 36 of file os_statistics.c.
References task_switch_cy.
Referenced by __os_statistics_switch_context_tick_handler_start().
{
    task_switch_cy = current_cy;
}
static void measure_context_task_switch_time_stop (os_cy_t current_cy) [inline, static]
Stop monitoring the task switch time.
Parameters:
current_cy Current number of cycles
Definition at line 43 of file os_statistics.c.
References task_switch_cy, task_switch_max_cy, and task_switch_min_cy.
Referenced by __os_statistics_switch_context_tick_handler_stop().
{
    task_switch_cy = current_cy - task_switch_cy;
    /* Update the minimal switch time */
    if (task_switch_cy < task_switch_min_cy) {
        task_switch_min_cy = task_switch_cy;
    }
    /* Update the maximal switch time */
    if (task_switch_cy > task_switch_max_cy) {
        task_switch_max_cy = task_switch_cy;
    }
}
static void update_task_cycle_counter_start (os_cy_t current_cy) [inline, static]
Start monitoring the task activity time.
Parameters:
current_cy Current number of cycles
Definition at line 58 of file os_statistics.c.
References __os_process_get_current(), os_process::cycle_counter, and task_cy.
Referenced by __os_statistics_switch_context_start(), and __os_statistics_switch_context_tick_handler_start().
{
    struct os_process *current_process = __os_process_get_current();
    current_process->cycle_counter += current_cy - task_cy;
}
static void update_task_cycle_counter_stop (os_cy_t current_cy) [inline, static]
Stop monitoring the task activity time.
Parameters:
current_cy Current number of cycles
Definition at line 66 of file os_statistics.c.
References task_cy.
Referenced by __os_statistics_switch_context_stop(), and __os_statistics_switch_context_tick_handler_stop().
{
    task_cy = current_cy;
}
Variable Documentation
os_cy_t task_cy = 0 [static]
Temporary variable to compute the task activity time.
Definition at line 21 of file os_statistics.c.
Referenced by update_task_cycle_counter_start(), and update_task_cycle_counter_stop().
os_cy_t task_switch_cy [static]
Temporary variable holding the number of cycles for the last task switch.
Definition at line 25 of file os_statistics.c.
Referenced by measure_context_task_switch_time_start(), and measure_context_task_switch_time_stop().
os_cy_t task_switch_max_cy = 0 [static]
Definition at line 31 of file os_statistics.c.
Referenced by measure_context_task_switch_time_stop(), os_statistics_get_task_switch_time(), and os_statistics_get_task_switch_time_jitter().
os_cy_t task_switch_min_cy = (os_cy_t) -1 [static]
Definition at line 28 of file os_statistics.c.
Referenced by measure_context_task_switch_time_stop(), os_statistics_get_task_switch_time(), and os_statistics_get_task_switch_time_jitter().