OS: os_event.c File Reference
os_event.c File Reference
eeOS Events
#include "os_core.h"
Data Structures
struct __os_event_custom_function_args
Functions
enum os_event_status __os_event_custom_function_handler (struct os_process *proc, os_ptr_t args)
void __os_event_register (struct os_event *event, struct os_process *proc)
Associate a process with an event and enable the event.
void os_event_create (struct os_event *event, const struct os_event_descriptor *descriptor, os_ptr_t args)
Create a new event.
void os_event_create_from_function (struct os_event *event, bool(*trigger)(os_ptr_t), os_ptr_t args)
Create a custom event from a function.
bool os_event_scheduler (void)
Event scheduler.
bool os_event_sort_fifo (struct os_process *proc1, struct os_process *proc2)
Helper function used to define the order of a new process added to an event. This function will add them so that the first in will be the first out. This function must be used with os_event_descriptor::sort.
bool os_event_sort_lifo (struct os_process *proc1, struct os_process *proc2)
Helper function used to define the order of a new process added to an event. This function will add them so that the last in will be the first out. This function must be used with os_event_descriptor::sort.
bool os_event_sort_priority (struct os_process *proc1, struct os_process *proc2)
Helper function used to define the order of a new process added to an event. This function will add them so that the highest priority process will be at the head of the list. This function must be used with os_event_descriptor::sort.
static struct os_process * __os_event_pop_process (struct os_event *event)
static void __os_event_pop (struct os_event *event)
static void __os_event_insert_process_after (struct os_process *proc, struct os_process *new_proc)
static void __os_event_insert_process_begining (struct os_event *event, struct os_process *proc)
static void __os_event_enable (struct os_event *event)
static void __os_event_start (struct os_event *event)
static bool __os_event_is_triggered (struct os_event *event)
Variables
static struct os_event * os_current_event = NULL
struct os_process os_event_alternate_proc
void os_interrupt_trigger_on_event (struct os_interrupt *interrupt, struct os_event *event)
Trigger an interrupt on a specific event.
void os_task_sleep (struct os_task *task, struct os_event *event)
Send the task to sleep and wake it up uppon a specific event.
Detailed Description
eeOS Events
Author:
Blaise Lengrand (blaise.lengrand@gmail.com)
Version:
0.1
Date:
2011
License
eeOS is provided in source form for FREE evaluation, for educational use or for peaceful research. If you plan on using eeOS in a commercial product you need to contact the author to properly license its use in your product. The fact that the source is provided does NOT mean that you can use it without paying a licensing fee.
Definition in file os_event.c.
Function Documentation
enum os_event_status __os_event_custom_function_handler (struct os_process * proc, os_ptr_t args)
Definition at line 216 of file os_event.c.
References __os_event_custom_function_args::args, OS_EVENT_NONE, OS_EVENT_OK_CONTINUE, and __os_event_custom_function_args::trigger.
Referenced by os_event_create_from_function().
{
    struct __os_event_custom_function_args *custom_args =
            (struct __os_event_custom_function_args *) args;
    if (custom_args->trigger(custom_args->args))
        return OS_EVENT_OK_CONTINUE;
    return OS_EVENT_NONE;
}
static void __os_event_enable (struct os_event * event) [inline, static]
Definition at line 70 of file os_event.c.
References event, and os_event::next.
Referenced by __os_event_register().
{
    if (os_current_event) {
        event->next = os_current_event->next;
    }
    else {
        event->next = NULL;
    }
    os_current_event = event;
}
static void __os_event_insert_process_after (struct os_process * proc, struct os_process * new_proc) [inline, static]
Definition at line 58 of file os_event.c.
References os_process::next.
Referenced by __os_event_register().
{
    new_proc->next = proc->next;
    proc->next = new_proc;
}
static void __os_event_insert_process_begining (struct os_event * event, struct os_process * proc) [inline, static]
Definition at line 64 of file os_event.c.
References os_process::next, and os_event::proc.
Referenced by __os_event_register().
{
    proc->next = event->proc;
    event->proc = proc;
}
static bool __os_event_is_triggered (struct os_event * event) [inline, static]
Definition at line 86 of file os_event.c.
References os_event::args, os_event::desc, os_event_descriptor::is_triggered, OS_EVENT_NONE, and os_get_current_process().
{
    if (event->desc.is_triggered(os_get_current_process(), event->args)
            == OS_EVENT_NONE)
        return false;
    return true;
}
static void __os_event_pop (struct os_event * event) [inline, static]
Note:
event MUST be in the event list
Definition at line 43 of file os_event.c.
References os_event::next, and os_current_event.
Referenced by os_event_scheduler().
{
    struct os_event *prev_event = os_current_event;
    // If the event is the 1rst one
    if (event == os_current_event) {
        os_current_event = event->next;
    }
    else {
        // Look for the event in the list
        while (prev_event->next != event) {
            prev_event = prev_event->next;
        }
        prev_event->next = event->next;
    }
}
static struct os_process* __os_event_pop_process (struct os_event * event) [static, read]
Private helper functions
Definition at line 35 of file os_event.c.
References os_process::next.
Referenced by os_event_scheduler().
{
    struct os_process *proc = event->proc;
    event->proc = proc->next;
    return proc;
}
static void __os_event_start (struct os_event * event) [inline, static]
Definition at line 80 of file os_event.c.
References os_event::args, os_event::desc, and os_event_descriptor::start.
Referenced by os_interrupt_trigger_on_event(), and os_task_sleep().
{
    if (event->desc.start) {
        event->desc.start(event->args);
    }
}
bool os_event_sort_fifo (struct os_process * proc1, struct os_process * proc2)
Helper function used to define the order of a new process added to an event. This function will add them so that the first in will be the first out. This function must be used with os_event_descriptor::sort.
Definition at line 97 of file os_event.c.
Referenced by __os_event_register().
{
    return true;
}
bool os_event_sort_lifo (struct os_process * proc1, struct os_process * proc2)
Helper function used to define the order of a new process added to an event. This function will add them so that the last in will be the first out. This function must be used with os_event_descriptor::sort.
Definition at line 103 of file os_event.c.
{
    return false;
}
bool os_event_sort_priority (struct os_process * proc1, struct os_process * proc2)
Helper function used to define the order of a new process added to an event. This function will add them so that the highest priority process will be at the head of the list. This function must be used with os_event_descriptor::sort.
Precondition:
CONFIG_OS_USE_PRIORITY must be set
Definition at line 110 of file os_event.c.
References os_process::priority.
Referenced by __os_event_register().
{
    return (proc1->priority <= proc2->priority);
}
Variable Documentation
struct os_event* os_current_event = NULL [static]
Definition at line 19 of file os_event.c.
Referenced by __os_event_pop(), __os_event_register(), and os_event_scheduler().
struct os_process os_event_alternate_proc
Initial value:
 {
    .next = NULL
}
Task API Extension
Definition at line 243 of file os_event.c.