OS: os_core.c File Reference
os_core.c File Reference
eeOS Core
#include "compiler.h"
#include "os_core.h"
Functions
void __os_process_disable (struct os_process *proc)
void __os_process_enable (struct os_process *proc)
struct os_process * os_get_current_process (void)
Get the current process.
void os_process_disable (struct os_process *proc)
Disable the execution of a process.
void os_process_enable (struct os_process *proc)
Enable the execution a process.
bool os_process_is_enabled (struct os_process *proc)
Check wether a process is enabled or not.
struct os_process * os_scheduler (void)
This function will define the rules to change the task.
void os_yield (void)
Call the scheduler to switch to a new task that is ready to run. This function is useful for cooperative task swiching.
Variables
struct os_process os_app
Context of the application task.
struct os_process * os_current_process = &os_app
Current process running.
volatile os_tick_t tick_counter = 0
Tick counter.
Detailed Description
eeOS Core
Author:
Blaise Lengrand (blaise.lengrand@gmail.com)
Version:
0.1
Date:
2011
License
eeOS is provided in source form for FREE evaluation, for educational use or for peaceful research. If you plan on using eeOS in a commercial product you need to contact the author to properly license its use in your product. The fact that the source is provided does NOT mean that you can use it without paying a licensing fee.
Definition in file os_core.c.
Function Documentation
struct os_process* os_get_current_process (void) [read]
Get the current process.
Returns:
A pointer on the current procress
Definition at line 76 of file os_core.c.
References os_current_process.
Referenced by __os_event_is_triggered(), os_mutex_lock(), and os_mutex_unlock().
{
    return os_current_process;
}
struct os_process* os_scheduler (void) [read]
This function will define the rules to change the task.
Returns:
The new task context
Definition at line 51 of file os_core.c.
References os_process::next, os_current_process, OS_SCHEDULER_PRE_INTERRUPT_HOOK, os_process::priority, and os_process::priority_counter.
Referenced by os_switch_context_hook(), and os_switch_context_int_handler_hook().
{
    do {
        // Get the next process
        os_current_process = os_current_process->next;
        // Check wether its priority counter is null
        if (!os_current_process->priority_counter) {
            os_current_process->priority_counter =
                    os_current_process->priority;
            OS_SCHEDULER_PRE_INTERRUPT_HOOK();
            return os_current_process;
        }
        // Decrease the priority counter
        os_current_process->priority_counter--;
    } while (true);
}
Variable Documentation
struct os_process os_app
Initial value:
 {
    .next = &os_app,
    .type = OS_PROCESS_TYPE_APPLICATION,
    .priority = OS_PRIORITY_1,
    .priority_counter = OS_PRIORITY_1,
}
Context of the application task.
Note:
This context is available only after the call of os_start
Definition at line 31 of file os_core.c.
Referenced by __os_process_disable(), and __os_process_get_application().
struct os_process* os_current_process = &os_app
Current process running.
Definition at line 42 of file os_core.c.
Referenced by _os_switch_context(), ISR(), os_get_current_process(), os_scheduler(), os_task_get_current(), and os_task_sleep().
volatile os_tick_t tick_counter = 0
Tick counter.
Definition at line 47 of file os_core.c.
Referenced by os_switch_context_int_handler_hook(), and os_task_delay().