OS: pm.c File Reference
pm.c File Reference
Power Manager driver.
#include "compiler.h"
#include "pm.h"
Data Structures
union u_avr32_pm_bgcr_t
union u_avr32_pm_bod_t
union u_avr32_pm_cksel_t
union u_avr32_pm_gcctrl_t
union u_avr32_pm_icr_t
union u_avr32_pm_idr_t
union u_avr32_pm_ier_t
union u_avr32_pm_mcctrl_t
union u_avr32_pm_oscctrl0_t
union u_avr32_pm_oscctrl1_t
union u_avr32_pm_oscctrl32_t
union u_avr32_pm_pll_t
union u_avr32_pm_rccr_t
union u_avr32_pm_vregcr_t
Functions
void pm_bod_clear_irq (volatile avr32_pm_t *pm)
Clears the Brown-Out Detector interrupt flag.
void pm_bod_disable_irq (volatile avr32_pm_t *pm)
Disables the Brown-Out Detector interrupt.
void pm_bod_enable_irq (volatile avr32_pm_t *pm)
Enables the Brown-Out Detector interrupt.
unsigned long pm_bod_get_irq_enable_bit (volatile avr32_pm_t *pm)
Gets the Brown-Out Detector interrupt enable status.
unsigned long pm_bod_get_irq_status (volatile avr32_pm_t *pm)
Gets the Brown-Out Detector interrupt flag.
unsigned long pm_bod_get_level (volatile avr32_pm_t *pm)
Gets the triggering threshold of the Brown-Out Detector.
void pm_cksel (volatile avr32_pm_t *pm, unsigned int pbadiv, unsigned int pbasel, unsigned int pbbdiv, unsigned int pbbsel, unsigned int hsbdiv, unsigned int hsbsel)
This function will select all the power manager clocks.
void pm_cksel_get (volatile avr32_pm_t *pm, unsigned long *p_cksel)
This function returns the cksel (Clock Select).
void pm_cksel_set (volatile avr32_pm_t *pm, unsigned long cksel)
This function set the cksel (Clock Select).
void pm_disable_clk0 (volatile avr32_pm_t *pm)
This function will disable the oscillator 0.
void pm_disable_clk1 (volatile avr32_pm_t *pm)
This function will disable the oscillator 1.
void pm_disable_clk32 (volatile avr32_pm_t *pm)
This function will disable the oscillator 32.
long pm_disable_module (volatile avr32_pm_t *pm, unsigned long module)
Disable the clock of a module.
void pm_enable_clk0 (volatile avr32_pm_t *pm, unsigned int startup)
This function will enable the oscillator 0 to be used with a startup time.
void pm_enable_clk0_no_wait (volatile avr32_pm_t *pm, unsigned int startup)
This function will enable the oscillator 0 to be used with no startup time.
void pm_enable_clk1 (volatile avr32_pm_t *pm, unsigned int startup)
This function will enable the oscillator 1 to be used with a startup time.
void pm_enable_clk1_no_wait (volatile avr32_pm_t *pm, unsigned int startup)
This function will enable the oscillator 1 to be used with no startup time.
void pm_enable_clk32 (volatile avr32_pm_t *pm, unsigned int startup)
This function will enable the oscillator 32 to be used with a startup time.
void pm_enable_clk32_no_wait (volatile avr32_pm_t *pm, unsigned int startup)
This function will enable the oscillator 32 to be used with no startup time.
long pm_enable_module (volatile avr32_pm_t *pm, unsigned long module)
Enable the clock of a module.
void pm_enable_osc0_crystal (volatile avr32_pm_t *pm, unsigned int fosc0)
This function will enable the crystal mode of the oscillator 0.
void pm_enable_osc0_ext_clock (volatile avr32_pm_t *pm)
This function will enable the external clock mode of the oscillator 0.
void pm_enable_osc1_crystal (volatile avr32_pm_t *pm, unsigned int fosc1)
This function will enable the crystal mode of the oscillator 1.
void pm_enable_osc1_ext_clock (volatile avr32_pm_t *pm)
This function will enable the external clock mode of the oscillator 1.
void pm_enable_osc32_crystal (volatile avr32_pm_t *pm)
This function will enable the crystal mode of the 32-kHz oscillator.
void pm_enable_osc32_ext_clock (volatile avr32_pm_t *pm)
This function will enable the external clock mode of the 32-kHz oscillator.
void pm_gc_disable (volatile avr32_pm_t *pm, unsigned int gc)
This function will disable a generic clock.
void pm_gc_enable (volatile avr32_pm_t *pm, unsigned int gc)
This function will enable a generic clock.
void pm_gc_setup (volatile avr32_pm_t *pm, unsigned int gc, unsigned int osc_or_pll, unsigned int pll_osc, unsigned int diven, unsigned int div)
This function will setup a generic clock.
unsigned long pm_get_clock (volatile avr32_pm_t *pm)
This function returns the power manager main clock.
void pm_pll_disable (volatile avr32_pm_t *pm, unsigned int pll)
This function will disable a PLL.
void pm_pll_enable (volatile avr32_pm_t *pm, unsigned int pll)
This function will enable a PLL.
unsigned int pm_pll_get_option (volatile avr32_pm_t *pm, unsigned int pll)
This function will get a PLL option.
void pm_pll_set_option (volatile avr32_pm_t *pm, unsigned int pll, unsigned int pll_freq, unsigned int pll_div2, unsigned int pll_wbwdisable)
This function will set a PLL option.
void pm_pll_setup (volatile avr32_pm_t *pm, unsigned int pll, unsigned int mul, unsigned int div, unsigned int osc, unsigned int lockcount)
This function will setup a PLL.
unsigned long pm_read_gplp (volatile avr32_pm_t *pm, unsigned long gplp)
Read the content of the PM GPLP registers.
static void pm_set_osc0_mode (volatile avr32_pm_t *pm, unsigned int mode)
Sets the mode of the oscillator 0.
static void pm_set_osc1_mode (volatile avr32_pm_t *pm, unsigned int mode)
Sets the mode of the oscillator 1.
static void pm_set_osc32_mode (volatile avr32_pm_t *pm, unsigned int mode)
Sets the mode of the 32-kHz oscillator.
void pm_switch_to_clock (volatile avr32_pm_t *pm, unsigned long clock)
This function will switch the power manager main clock.
void pm_switch_to_osc0 (volatile avr32_pm_t *pm, unsigned int fosc0, unsigned int startup)
Switch main clock to clock Osc0 (crystal mode)
void pm_wait_for_clk0_ready (volatile avr32_pm_t *pm)
This function will wait until the Osc0 clock is ready.
void pm_wait_for_clk1_ready (volatile avr32_pm_t *pm)
This function will wait until the Osc1 clock is ready.
void pm_wait_for_clk32_ready (volatile avr32_pm_t *pm)
This function will wait until the osc32 clock is ready.
void pm_wait_for_pll0_locked (volatile avr32_pm_t *pm)
This function will wait for PLL0 locked.
void pm_wait_for_pll1_locked (volatile avr32_pm_t *pm)
This function will wait for PLL1 locked.
void pm_write_gplp (volatile avr32_pm_t *pm, unsigned long gplp, unsigned long value)
Write into the PM GPLP registers.
Detailed Description
Power Manager driver.
Compiler: IAR EWAVR32 and GNU GCC for AVR32
Supported devices: All AVR32 devices.
AppNote:
Author:
Atmel Corporation: http://www.atmel.com
Support and FAQ: http://support.atmel.no/
Definition in file pm.c.
Function Documentation
static void pm_set_osc0_mode (volatile avr32_pm_t * pm, unsigned int mode) [static]
Sets the mode of the oscillator 0.
Parameters:
pm Base address of the Power Manager (i.e. &AVR32_PM).
mode Oscillator 0 mode (i.e. AVR32_PM_OSCCTRL0_MODE_x).
Definition at line 147 of file pm.c.
References u_avr32_pm_oscctrl0_t::OSCCTRL0, and u_avr32_pm_oscctrl0_t::oscctrl0.
Referenced by pm_enable_osc0_crystal(), and pm_enable_osc0_ext_clock().
{
  // Read
  u_avr32_pm_oscctrl0_t u_avr32_pm_oscctrl0 = {pm->oscctrl0};
  // Modify
  u_avr32_pm_oscctrl0.OSCCTRL0.mode = mode;
  // Write
  pm->oscctrl0 = u_avr32_pm_oscctrl0.oscctrl0;
}
static void pm_set_osc1_mode (volatile avr32_pm_t * pm, unsigned int mode) [static]
Sets the mode of the oscillator 1.
Parameters:
pm Base address of the Power Manager (i.e. &AVR32_PM).
mode Oscillator 1 mode (i.e. AVR32_PM_OSCCTRL1_MODE_x).
Definition at line 210 of file pm.c.
References u_avr32_pm_oscctrl1_t::OSCCTRL1, and u_avr32_pm_oscctrl1_t::oscctrl1.
Referenced by pm_enable_osc1_crystal(), and pm_enable_osc1_ext_clock().
{
  // Read
  u_avr32_pm_oscctrl1_t u_avr32_pm_oscctrl1 = {pm->oscctrl1};
  // Modify
  u_avr32_pm_oscctrl1.OSCCTRL1.mode = mode;
  // Write
  pm->oscctrl1 = u_avr32_pm_oscctrl1.oscctrl1;
}
static void pm_set_osc32_mode (volatile avr32_pm_t * pm, unsigned int mode) [static]
Sets the mode of the 32-kHz oscillator.
Parameters:
pm Base address of the Power Manager (i.e. &AVR32_PM).
mode 32-kHz oscillator mode (i.e. AVR32_PM_OSCCTRL32_MODE_x).
Definition at line 273 of file pm.c.
References u_avr32_pm_oscctrl32_t::OSCCTRL32, and u_avr32_pm_oscctrl32_t::oscctrl32.
Referenced by pm_enable_osc32_crystal(), and pm_enable_osc32_ext_clock().
{
  // Read
  u_avr32_pm_oscctrl32_t u_avr32_pm_oscctrl32 = {pm->oscctrl32};
  // Modify
  u_avr32_pm_oscctrl32.OSCCTRL32.mode = mode;
  // Write
  pm->oscctrl32 = u_avr32_pm_oscctrl32.oscctrl32;
}