OS: power_clocks_lib.c File Reference
power_clocks_lib.c File Reference
High-level library abstracting features such as oscillators/pll/dfll configuration, clock configuration, System-sensible parameters configuration, buses clocks configuration, sleep mode, reset.
#include "power_clocks_lib.h"
Functions
long int pcl_configure_clocks (pcl_freq_param_t *param)
Device-specific data.
long int pcl_configure_clocks_dfll0 (pcl_freq_param_t *param)
Automatically configure the CPU, PBA, PBB, and HSB clocks using the DFLL0 as main source clock.
long int pcl_configure_clocks_osc0 (pcl_freq_param_t *param)
Automatically configure the CPU, PBA, PBB, and HSB clocks using the OSC0 osc as main source clock.
long int pcl_configure_clocks_rc120m (pcl_freq_param_t *param)
Automatically configure the CPU, PBA, PBB, and HSB clocks using the RC120M osc as main source clock.
long int pcl_configure_clocks_rcsys (pcl_freq_param_t *param)
Automatically configure the CPU, PBA, PBB, and HSB clocks using the RCSYS osc as main source clock.
static long int pcl_configure_clocks_uc3l (pcl_freq_param_t *param)
static long int pcl_configure_synchronous_clocks (pm_clk_src_t main_clk_src, unsigned long main_clock_freq_hz, pcl_freq_param_t *param)
Device-specific implementation.
long int pcl_configure_usb_clock (void)
Configure the USB Clock.
long int pcl_switch_to_osc (pcl_osc_t osc, unsigned int fcrystal, unsigned int startup)
UC3C Device-specific implementation.
Detailed Description
High-level library abstracting features such as oscillators/pll/dfll configuration, clock configuration, System-sensible parameters configuration, buses clocks configuration, sleep mode, reset.
Compiler: IAR EWAVR32 and GNU GCC for AVR32
Supported devices: All AVR32 devices.
AppNote:
Author:
Atmel Corporation: http://www.atmel.com
Support and FAQ: http://support.atmel.no/
Definition in file power_clocks_lib.c.
Function Documentation
static long int pcl_configure_clocks_uc3l (pcl_freq_param_t * param) [static]
Definition at line 218 of file power_clocks_lib.c.
References pcl_configure_clocks_dfll0(), pcl_configure_clocks_osc0(), pcl_configure_clocks_rc120m(), pcl_configure_clocks_rcsys(), PCL_MC_OSC0, PCL_MC_RC120M, and PCL_MC_RCSYS.
Referenced by pcl_configure_clocks().
{
  // Supported main clock sources: PCL_MC_RCSYS, PCL_MC_OSC0, PCL_MC_DFLL0, PCL_MC_RC120M
  // Supported synchronous clocks frequencies if RCSYS is the main clock source:
  // 115200Hz, 57600Hz, 28800Hz, 14400Hz, 7200Hz, 3600Hz, 1800Hz, 900Hz, 450Hz.
  // Supported synchronous clocks frequencies if RC120M is the main clock source:
  // 30MHz, 15MHz, 7.5MHz, 3.75MHz, 1.875MHz, 937.5kHz, 468.75kHz.
  // Supported synchronous clocks frequencies if OSC0 is the main clock source:
  // (these obviously depend on the OSC0 frequency; we'll take 16MHz as an example)
  // 16MHz, 8MHz, 4MHz, 2MHz, 1MHz, 500kHz, 250kHz, 125kHz, 62.5kHz.
  // Supported synchronous clocks frequencies if DFLL is the main clock source:
  // (these obviously depend on the DFLL target frequency; we'll take 100MHz as an example)
  // 50MHz, 25MHz, 12.5MHz, 6.25MHz, 3.125MHz, 1562.5kHz, 781.25kHz, 390.625kHz.
  // NOTE: by default, this implementation doesn't perform thorough checks on the
  // input parameters. To enable the checks, define AVR32SFW_INPUT_CHECK.
#ifdef AVR32SFW_INPUT_CHECK
  // Verify that fCPU >= fPBx
  if((param->cpu_f < param->pba_f) || (param->cpu_f < param->pbb_f))
    return(-1);
#endif
  if(PCL_MC_RCSYS == param->main_clk_src)
  {
    return(pcl_configure_clocks_rcsys(param));
  }
  else if(PCL_MC_RC120M == param->main_clk_src)
  {
    return(pcl_configure_clocks_rc120m(param));
  }
  else if(PCL_MC_OSC0 == param->main_clk_src)
  {
    return(pcl_configure_clocks_osc0(param));
  }
  else // PCL_MC_DFLL0 == param->main_clk_src
  {
    return(pcl_configure_clocks_dfll0(param));
  }
}
static long int pcl_configure_synchronous_clocks (pm_clk_src_t main_clk_src, unsigned long main_clock_freq_hz, pcl_freq_param_t * param) [static]
Device-specific implementation.
Definition at line 264 of file power_clocks_lib.c.
References flashc_set_flash_waitstate_and_readmode(), and PASS.
Referenced by pcl_configure_clocks_dfll0(), pcl_configure_clocks_osc0(), pcl_configure_clocks_rc120m(), and pcl_configure_clocks_rcsys().
{
  //#
  //# Set the Synchronous clock division ratio for each clock domain
  //#
  pm_set_all_cksel(main_clock_freq_hz, param->cpu_f, param->pba_f, param->pbb_f);
  //#
  //# Set the Flash wait state and the speed read mode (depending on the target CPU frequency).
  //#
#if UC3L
    flashcdw_set_flash_waitstate_and_readmode(param->cpu_f);
#elif UC3C
    flashc_set_flash_waitstate_and_readmode(param->cpu_f);
#endif
  //#
  //# Switch the main clock source to the selected clock.
  //#
  pm_set_mclk_source(main_clk_src);
  return PASS;
}