OS: os_event_descriptor Struct Reference
os_event_descriptor Struct Reference
Event descriptor.
#include <os_event.h>
Data Fields
enum os_event_status(* is_triggered)(struct os_process *proc, os_ptr_t args)
Check the status of an event.
bool(* sort)(struct os_process *proc1, struct os_process *proc2)
Sorting function. This function compare 2 processes. The following helper functions are available:
void(* start)(os_ptr_t args)
This function will handle the setup of the event. For example, if the event is a timer, the timer will start to run after the call of this function.
Detailed Description
Event descriptor.
Definition at line 56 of file os_event.h.
Field Documentation
enum os_event_status(* os_event_descriptor::is_triggered)(struct os_process *proc, os_ptr_t args)
Check the status of an event.
Note:
This function is optional.
Parameters:
proc The process of the process which is intented to triggered
args Argument passed to the event during its creation
Returns:
The current event status (os_event_status)
Definition at line 82 of file os_event.h.
Referenced by __os_event_is_triggered(), os_event_create(), and os_event_create_from_function().
bool(* os_event_descriptor::sort)(struct os_process *proc1, struct os_process *proc2)
Sorting function. This function compare 2 processes. The following helper functions are available:
os_event_sort_fifo
os_event_sort_lifo
Note:
This function is optional. By default the new process will added using the os_event_sort_fifo algorithm or the os_event_sort_priority alorithm, depending if priorities are enabled or not.
Parameters:
proc1 The first process used in the comparison
proc2 The second process used in the comparison
Returns:
true if proc1 should be placed before proc2, false otherwise.
Definition at line 69 of file os_event.h.
Referenced by __os_event_register(), and os_event_create().
void(* os_event_descriptor::start)(os_ptr_t args)
This function will handle the setup of the event. For example, if the event is a timer, the timer will start to run after the call of this function.
Parameters:
args Argument passed to the event during its creation
Definition at line 75 of file os_event.h.
Referenced by __os_event_start(), and os_event_create().