OS: uc3_port.c File Reference
uc3_port.c File Reference
eeOS 32-bit AVR UC3 Port
#include "os_core.h"
Defines
#define OS_SCHEDULER_IRQ_GROUP AVR32_CORE_IRQ_GROUP
#define PUSH(proc, value)
Functions
void _os_switch_context (void)
ISR (os_switch_context_int_handler, OS_SCHEDULER_IRQ_GROUP, CONFIG_OS_SCHEDULER_IRQ_PRIORITY)
bool os_process_context_load (struct os_process *proc, os_proc_ptr_t proc_ptr, os_ptr_t args)
Load the context of a task into the stack. this is the inital process which will setup the stack before entering in the task function.
static void os_scheduler_clear_int (void)
void os_setup_scheduler (uint32_t cpu_freq_hz)
Setup the task scheduler interrupt.
static void os_switch_context_int_handler (void)
Context switch for a process.
Interrupt handler which is used to schedule and switch between the processes.
Detailed Description
eeOS 32-bit AVR UC3 Port
Author:
Blaise Lengrand (blaise.lengrand@gmail.com)
Version:
0.1
Date:
2011
License
eeOS is provided in source form for FREE evaluation, for educational use or for peaceful research. If you plan on using eeOS in a commercial product you need to contact the author to properly license its use in your product. The fact that the source is provided does NOT mean that you can use it without paying a licensing fee.
Definition in file uc3_port.c.
Define Documentation
#define OS_SCHEDULER_IRQ_GROUP AVR32_CORE_IRQ_GROUP
Definition at line 52 of file uc3_port.c.
#define PUSH (proc, value)
Value:
{ \
    (proc)->sp = (uint32_t *) (proc)->sp - 1; \
    *((uint32_t *) (proc)->sp) = (uint32_t) (value); \
}
Push a 32-bit value onto the stack of the task
Parameters:
proc The current process holding the stack we want to update
value The 32-bit value to be pushed
Definition at line 21 of file uc3_port.c.
Referenced by os_process_context_load().
Function Documentation
void _os_switch_context (void)
Definition at line 196 of file uc3_port.c.
References CONFIG_OS_USE_SW_INTERRUPTS, os_current_process, and os_switch_context_hook().
{
    extern struct os_process *os_current_process;
    __asm__ __volatile__ (
#if CONFIG_OS_USE_SW_INTERRUPTS == true
        // Test if we need to save the context
        "cp.w r8, 0\n\t"
    #if __ICCAVR32__
        "brne bypass_context_save:C\n\t"
    #else
        "brne bypass_context_save\n\t"
    #endif
#endif
        // Save context
        "pushm r10-r12, lr\n\t" // r10-r12, lr
        "ld.d r10, sp[4*4]\n\t"
        "st.d sp[4*4], r8\n\t" // r8-r9
        "st.d --sp, r10\n\t" // pc, sr
            "pushm r0-r7\n\t" // r0-r7
        // Save the stack pointer
        "mov r0, os_current_process\n\t"
        "ld.w r1, r0[0]\n\t"
        "st.w r1[0], sp\n"
        // Bypass the context saving
        "bypass_context_save:"
    );
    os_switch_context_hook();
    __asm__ __volatile__ (
        // Update the stack pointer
        "ld.w sp, r12\n\t"
        // Restore context
        "popm r0-r7\n\t" // r0-r7
        "ld.d r6, sp++\n\t" // r6 = sr; r7 = pc
        "popm lr, r8-r12\n\t" // lr, r8-r12
        "st.d --sp, r6\n\t" // stack sr and pc
        "ld.d r6, sp[-14*4]\n\t" // restore r6-r7
        // Restore context
        "rets\n\t"
    );
#if __ICCAVR32__
    #pragma diag_suppress=Pe174
#endif
    os_current_process = os_current_process;
#if __ICCAVR32__
    #pragma diag_default=Pe174
#endif
}
ISR (os_switch_context_int_handler , OS_SCHEDULER_IRQ_GROUP , CONFIG_OS_SCHEDULER_IRQ_PRIORITY)
Definition at line 150 of file uc3_port.c.
References HOOK_OS_STATISTICS_SWITCH_CONTEXT_START, HOOK_OS_STATISTICS_SWITCH_CONTEXT_STOP, os_current_process, os_scheduler_clear_int(), and os_switch_context_int_handler_hook().
{
    extern struct os_process *os_current_process;
    __asm__ __volatile__ (
        // Save context
            "pushm r0-r7\n\t"
        // Save the stack pointer
        "mov r0, os_current_process\n\t"
        "ld.w r1, r0[0]\n\t"
        "st.w r1[0], sp\n\t"
    );
    HOOK_OS_STATISTICS_SWITCH_CONTEXT_START(42);
    // Clear the interrupt flag
    os_scheduler_clear_int();
    os_switch_context_int_handler_hook();
    __asm__ __volatile__ (
        // Update the stack pointer
        "ld.w sp, r12\n\t"
        // Restore context
        "popm r0-r7\n\t"
    );
    HOOK_OS_STATISTICS_SWITCH_CONTEXT_STOP();
    __asm__ __volatile__ (
        "rete\n\t"
    );
#if __ICCAVR32__
    #pragma diag_suppress=Pe174
#endif
    os_current_process = os_current_process;
#if __ICCAVR32__
    #pragma diag_default=Pe174
#endif
}
static void os_scheduler_clear_int (void) [inline, static]
Definition at line 48 of file uc3_port.c.
References Get_system_register, and Set_system_register.
Referenced by ISR().
{
        Set_system_register(AVR32_COMPARE, Get_system_register(AVR32_COMPARE));
    }