eeOS (Embedded Event-driven Operating System): Queues
Queues
[Public API]
This page contains technical information related to a queue.
Data Structures
struct os_queue
Queue type. A queue is a singly linked list.
struct os_queue_doubly
Doubly queue type. A queue is a doubly linked list.
struct os_queue_doubly_process
Type definition for the structure os_queue_doubly_process.
struct os_queue_process
Type definition for the structure os_queue_process.
Defines
#define OS_QUEUE_DEFINE(NAME,...)
Macro used to define a new singly queue type.
#define OS_QUEUE_DOUBLY_DEFINE(NAME,...)
Macro used to define a new doubly queue type.
Typedefs
typedef bool(* os_queue_doubly_sort_t)(struct os_queue_doubly *a, struct os_queue_doubly *b)
Sorting function prototype for doubly linked lists.
typedef bool(* os_queue_sort_t)(struct os_queue *a, struct os_queue *b)
Sorting function prototype for singly linked lists.
Singly Queues
Singly queues are singly linked list. Singly linked lists contain nodes which have a data field as well as a next field, which points to the next node in the linked list.
bool os_queue_sort_fifo (struct os_queue *a, struct os_queue *b)
Helper function used to define the order of a new element added to a queue (os_queue). This function will add them so that the first in will be the first out. This function must be used with the type os_queue_sort_t.
bool os_queue_sort_lifo (struct os_queue *a, struct os_queue *b)
Helper function used to define the order of a new element added to a queue (os_queue). This function will add them so that the last in will be the first out. This function must be used with the type os_queue_sort_t.
bool os_queue_process_sort_priority (struct os_queue *a, struct os_queue *b)
Helper function used to define the order of a new element added to a queue (os_queue). This function will add them so that the highest priority process will be at the head of the list. This function must be used with the type os_queue_sort_t.
static struct os_queue * os_queue_pop (struct os_queue **first_elt)
Returns and remove the first element from the queue.
static struct os_queue * os_queue_head (struct os_queue *first_elt)
Returns the first element from the queue.
static void os_queue_insert_after (struct os_queue *prev_elt, struct os_queue *elt)
Insert an element in the queue. The element cannot be inserted at the begining of the queue but after another element only.
static void os_queue_insert_first (struct os_queue **first_elt, struct os_queue *elt)
Insert an element at the begining of the queue.
void os_queue_add_sort (struct os_queue **first_elt, struct os_queue *elt, os_queue_sort_t sort_fct)
Add a new element to the queue and sort it.
static void os_queue_add (struct os_queue **first_elt, struct os_queue *new_elt)
Add a new element to the queue. The new element will be added to the end of the queue.
bool os_queue_remove (struct os_queue **first_elt, struct os_queue *elt)
Remove an element from the queue.
Doubly Queues
Doubly queues are doubly linked lists. In a doubly linked list, each node contains, besides the next-node link, a second link field pointing to the previous node in the sequence.
bool os_queue_doubly_process_sort_priority (struct os_queue_doubly *a, struct os_queue_doubly *b)
Helper function used to define the order of a new elements added to a doubly process queue (os_queue_doubly). This function will add them so that the highest priority process will be at the head of the list. This function must be used with the type os_queue_doubly_sort_t.
static struct os_queue_doubly * os_queue_doubly_pop (struct os_queue_doubly **first_elt)
Returns and remove the first element from the queue.
static struct os_queue_doubly * os_queue_doubly_head (struct os_queue_doubly *first_elt)
Returns the first element from the queue.
static void os_queue_doubly_insert_after (struct os_queue_doubly *prev_elt, struct os_queue_doubly *elt)
Insert an element in the queue.
static void os_queue_doubly_insert_first (struct os_queue_doubly **first_elt, struct os_queue_doubly *elt)
Insert an element at the begining of the queue.
void os_queue_doubly_add_sort (struct os_queue_doubly **first_elt, struct os_queue_doubly *elt, os_queue_doubly_sort_t sort_fct)
Add a new element to the queue and sort it.
static void os_queue_doubly_add (struct os_queue_doubly **first_elt, struct os_queue_doubly *new_elt)
Add a new element to the queue. The new element will be added to the end of the queue.
void os_queue_doubly_remove (struct os_queue_doubly *elt)
Remove an element from the queue. The element must not be the first one in the queue.
void os_queue_doubly_remove_ex (struct os_queue_doubly **first_elt, struct os_queue_doubly *elt)
Remove an element from the queue.
Singly Process Queues
Singly process queues are children of singly queues (os_queue). The difference is that they hold a process information.
static struct os_queue * os_queue_process_get_queue (struct os_queue_process *elt)
Get the os_queue element from the os_process_queue type \ * \.
static struct os_queue_process * os_queue_process_from_queue (struct os_queue *elt)
Get the os_process_queue element from the os_queue type \ * \.
static struct os_queue_process * os_queue_process_pop (struct os_queue_process **first_elt)
Alias of os_queue_pop \ * \.
static struct os_queue_process * os_queue_process_head (struct os_queue_process *first_elt)
Alias of os_queue_head \ * \.
static void os_queue_process_insert_after (struct os_queue_process *prev_elt, struct os_queue_process *elt)
Alias of os_queue_insert_after \ * \.
static void os_queue_process_insert_first (struct os_queue_process **first_elt, struct os_queue_process *elt)
Alias of os_queue_insert_first \ * \.
static void os_queue_process_add_sort (struct os_queue_process **first_elt, struct os_queue_process *elt, os_queue_sort_t sort_fct)
Alias of os_queue_add_sort \ * \.
static bool os_queue_process_remove (struct os_queue_process **first_elt, struct os_queue_process *elt)
Alias of os_queue_remove \ * \.
static struct os_process * os_queue_process_get (struct os_queue_process *elt)
Returns the process information held by a os_queue_process element.
static void os_queue_process_add (struct os_queue_process **first_elt, struct os_queue_process *new_elt)
Add a new element to the queue. The new element will be added to the end of the queue. If CONFIG_OS_USE_PRIORITY is set, the element will be added according to the priority of the process associated with the queue element. The highest priority goes first.
Doubly Process Queues
Doubly process queues are children of doubly queues (os_queue_doubly). The difference is that they hold a process information.
static struct os_queue_doubly * os_queue_doubly_process_get_queue_doubly (struct os_queue_doubly_process *elt)
Get the os_queue_doubly element from the os_doubly_process_queue type \ * \.
static struct
os_queue_doubly_process * os_queue_doubly_process_from_queue_doubly (struct os_queue_doubly *elt)
Get the os_doubly_process_queue element from the os_queue_doubly type \ * \.
static struct
os_queue_doubly_process * os_queue_doubly_process_pop (struct os_queue_doubly_process **first_elt)
Alias of os_queue_doubly_pop \ * \.
static struct
os_queue_doubly_process * os_queue_doubly_process_head (struct os_queue_doubly_process *first_elt)
Alias of os_queue_doubly_head \ * \.
static void os_queue_doubly_process_insert_after (struct os_queue_doubly_process *prev_elt, struct os_queue_doubly_process *elt)
Alias of os_queue_doubly_insert_after \ * \.
static void os_queue_doubly_process_insert_first (struct os_queue_doubly_process **first_elt, struct os_queue_doubly_process *elt)
Alias of os_queue_doubly_insert_first \ * \.
static void os_queue_doubly_process_add_sort (struct os_queue_doubly_process **first_elt, struct os_queue_doubly_process *elt, os_queue_doubly_sort_t sort_fct)
Alias of os_queue_doubly_add_sort \ * \.
static void os_queue_doubly_process_remove (struct os_queue_doubly_process *elt)
Alias of os_queue_doubly_remove \ * \.
static void os_queue_doubly_process_remove_ex (struct os_queue_doubly_process **first_elt, struct os_queue_doubly_process *elt)
Alias of os_queue_doubly_remove_ex \ * \.
static struct os_process * os_queue_doubly_process_get (struct os_queue_doubly_process *elt)
Returns the process information held by a os_queue_doubly_process element.
static void os_queue_doubly_process_add (struct os_queue_doubly_process **first_elt, struct os_queue_doubly_process *new_elt)
Add a new element to the queue. The new element will be added to the end of the queue. If CONFIG_OS_USE_PRIORITY is set, the element will be added according to the priority of the process associated with the queue element. The highest priority goes first.
Detailed Description
This page contains technical information related to a queue.
Define Documentation
#define OS_QUEUE_DEFINE (NAME, ...)
Macro used to define a new singly queue type.
The queue type defined by this macro will inherit from all the following functions (from the os_queue):
os_queue_<NAME>_pop alias of os_queue_pop
os_queue_<NAME>_head alias of os_queue_head
os_queue_<NAME>_insert_after alias of os_queue_insert_after
os_queue_<NAME>_insert_first alias of os_queue_insert_first
os_queue_<NAME>_add_sort alias of os_queue_add_sort
os_queue_<NAME>_remove alias of os_queue_remove
But also from 2 other functions to cast the defined type:
os_queue_<NAME>_get_queue (get the os_queue element from the os_<NAME>_queue type)
os_queue_<NAME>_from_queue (get the os_<NAME>_queue element from the os_queue type)
Parameters:
NAME Prefix for the name of the queue. The queue type defined will be a structure with the following symbol: os_queue_<NAME>
... Parameters that will be included in the queue type.
Definition at line 47 of file os_queue.h.
#define OS_QUEUE_DOUBLY_DEFINE (NAME, ...)
Macro used to define a new doubly queue type.
The queue type defined by this macro will inherit from all the following functions (from the os_queue_doubly):
os_queue_<NAME>_pop alias of os_queue_doubly_pop
os_queue_<NAME>_head alias of os_queue_doubly_head
os_queue_<NAME>_insert_after alias of os_queue_doubly_insert_after
os_queue_<NAME>_insert_first alias of os_queue_doubly_insert_first
os_queue_<NAME>_add_sort alias of os_queue_doubly_add_sort
os_queue_<NAME>_remove alias of os_queue_doubly_remove
But also from 2 other functions to cast the defined type:
os_queue_<NAME>_get_queue (get the os_queue_doubly element from the os_<NAME>_queue type)
os_queue_<NAME>_from_queue (get the os_<NAME>_queue element from the os_queue_doubly type)
Parameters:
NAME Prefix for the name of the queue. The queue type defined will be a structure with the following symbol: os_queue_<NAME>
... Parameters that will be included in the queue type.
Definition at line 110 of file os_queue.h.
Typedef Documentation
typedef bool(* os_queue_doubly_sort_t)(struct os_queue_doubly *a, struct os_queue_doubly *b)
Sorting function prototype for doubly linked lists.
Parameters:
a The first queue element
b The secont queue element
Returns:
true if the first element is supposed to be placed before the second element. Returns false otherwise.
Definition at line 196 of file os_queue.h.
typedef bool(* os_queue_sort_t)(struct os_queue *a, struct os_queue *b)
Sorting function prototype for singly linked lists.
Parameters:
a The first queue element
b The secont queue element
Returns:
true if the first element is supposed to be placed before the second element. Returns false otherwise.
See also:
The following functions are predefined and can be used:
os_queue_sort_fifo
os_queue_sort_lifo
Definition at line 177 of file os_queue.h.
Function Documentation
static void os_queue_add (struct os_queue ** first_elt, struct os_queue * new_elt) [inline, static]
Add a new element to the queue. The new element will be added to the end of the queue.
Parameters:
first_elt A pointer on the variable holding the first element in the queue.
new_elt The new element to be added.
Definition at line 300 of file os_queue.h.
References os_queue::next.
{
    elt->next = prev_elt->next;
    prev_elt->next = elt;
}
void os_queue_add_sort (struct os_queue ** first_elt, struct os_queue * elt, os_queue_sort_t sort_fct)
Add a new element to the queue and sort it.
Parameters:
first_elt A pointer on the variable holding the first element in the queue.
elt The new element to be added.
sort_fct The sorting function.
static void os_queue_doubly_add (struct os_queue_doubly ** first_elt, struct os_queue_doubly * new_elt) [inline, static]
Add a new element to the queue. The new element will be added to the end of the queue.
Parameters:
first_elt A pointer on the variable holding the first element in the queue.
new_elt The new element to be added.
Definition at line 417 of file os_queue.h.
References os_queue_doubly::next, and os_queue_doubly::prev.
{
void os_queue_doubly_add_sort (struct os_queue_doubly ** first_elt, struct os_queue_doubly * elt, os_queue_doubly_sort_t sort_fct)
Add a new element to the queue and sort it.
Parameters:
first_elt A pointer on the variable holding the first element in the queue.
elt The new element to be added.
sort_fct The sorting function.
static struct os_queue_doubly* os_queue_doubly_head (struct os_queue_doubly * first_elt) [static, read]
Returns the first element from the queue.
Parameters:
first_elt A pointer on the first element in the queue.
Returns:
The first element from the queue.
Definition at line 361 of file os_queue.h.
{
static void os_queue_doubly_insert_after (struct os_queue_doubly * prev_elt, struct os_queue_doubly * elt) [inline, static]
Insert an element in the queue.
Parameters:
prev_elt The element after which the new element should be placed.
elt The new element to be inserted.
Definition at line 371 of file os_queue.h.
{
static void os_queue_doubly_insert_first (struct os_queue_doubly ** first_elt, struct os_queue_doubly * elt) [inline, static]
Insert an element at the begining of the queue.
Parameters:
first_elt A pointer on the variable holding the first element in the queue.
elt The new element to be inserted.
Definition at line 390 of file os_queue.h.
{
    return first_elt;
static struct os_queue_doubly* os_queue_doubly_pop (struct os_queue_doubly ** first_elt) [static, read]
Returns and remove the first element from the queue.
Parameters:
first_elt A pointer on the variable holding the first element in the queue.
Returns:
The first element from the queue.
Note:
The queue must not be empty
Definition at line 348 of file os_queue.h.
    {
static void os_queue_doubly_process_add (struct os_queue_doubly_process ** first_elt, struct os_queue_doubly_process * new_elt) [inline, static]
Add a new element to the queue. The new element will be added to the end of the queue. If CONFIG_OS_USE_PRIORITY is set, the element will be added according to the priority of the process associated with the queue element. The highest priority goes first.
Parameters:
first_elt A pointer on the variable holding the first element in the queue.
new_elt The new element to be added.
Definition at line 548 of file os_queue.h.
{
static void os_queue_doubly_process_add_sort (struct os_queue_doubly_process ** first_elt, struct os_queue_doubly_process * elt, os_queue_doubly_sort_t sort_fct) [inline, static]
Alias of os_queue_doubly_add_sort \ * \.
Definition at line 525 of file os_queue.h.
{
static struct os_queue_doubly_process* os_queue_doubly_process_from_queue_doubly (struct os_queue_doubly * elt) [static, read]
Get the os_doubly_process_queue element from the os_queue_doubly type \ * \.
Definition at line 525 of file os_queue.h.
{
static struct os_process* os_queue_doubly_process_get (struct os_queue_doubly_process * elt) [static, read]
Returns the process information held by a os_queue_doubly_process element.
Parameters:
elt The os_queue_doubly_process element
Returns:
The os_process associated with this element.
Definition at line 533 of file os_queue.h.
    {
static struct os_queue_doubly* os_queue_doubly_process_get_queue_doubly (struct os_queue_doubly_process * elt) [static, read]
Get the os_queue_doubly element from the os_doubly_process_queue type \ * \.
Definition at line 525 of file os_queue.h.
{
static struct os_queue_doubly_process* os_queue_doubly_process_head (struct os_queue_doubly_process * first_elt) [static, read]
Alias of os_queue_doubly_head \ * \.
Definition at line 525 of file os_queue.h.
{
static void os_queue_doubly_process_insert_after (struct os_queue_doubly_process * prev_elt, struct os_queue_doubly_process * elt) [inline, static]
Alias of os_queue_doubly_insert_after \ * \.
Definition at line 525 of file os_queue.h.
{
static void os_queue_doubly_process_insert_first (struct os_queue_doubly_process ** first_elt, struct os_queue_doubly_process * elt) [inline, static]
Alias of os_queue_doubly_insert_first \ * \.
Definition at line 525 of file os_queue.h.
{
static struct os_queue_doubly_process* os_queue_doubly_process_pop (struct os_queue_doubly_process ** first_elt) [static, read]
Alias of os_queue_doubly_pop \ * \.
Definition at line 525 of file os_queue.h.
{
static void os_queue_doubly_process_remove (struct os_queue_doubly_process * elt) [inline, static]
Alias of os_queue_doubly_remove \ * \.
Definition at line 525 of file os_queue.h.
{
static void os_queue_doubly_process_remove_ex (struct os_queue_doubly_process ** first_elt, struct os_queue_doubly_process * elt) [inline, static]
Alias of os_queue_doubly_remove_ex \ * \.
Definition at line 525 of file os_queue.h.
{
bool os_queue_doubly_process_sort_priority (struct os_queue_doubly * a, struct os_queue_doubly * b)
Helper function used to define the order of a new elements added to a doubly process queue (os_queue_doubly). This function will add them so that the highest priority process will be at the head of the list. This function must be used with the type os_queue_doubly_sort_t.
Precondition:
CONFIG_OS_USE_PRIORITY must be set
void os_queue_doubly_remove (struct os_queue_doubly * elt)
Remove an element from the queue. The element must not be the first one in the queue.
Parameters:
elt The element to be removed.
void os_queue_doubly_remove_ex (struct os_queue_doubly ** first_elt, struct os_queue_doubly * elt)
Remove an element from the queue.
Parameters:
first_elt A pointer on the variable holding the first element in the queue.
elt The element to be removed.
static struct os_queue* os_queue_head (struct os_queue * first_elt) [static, read]
Returns the first element from the queue.
Parameters:
first_elt A pointer on the first element in the queue.
Returns:
The first element from the queue.
Definition at line 255 of file os_queue.h.
{
static void os_queue_insert_after (struct os_queue * prev_elt, struct os_queue * elt) [inline, static]
Insert an element in the queue. The element cannot be inserted at the begining of the queue but after another element only.
Parameters:
prev_elt The element after which the new element should be placed.
elt The new element to be inserted.
Definition at line 265 of file os_queue.h.
{
static void os_queue_insert_first (struct os_queue ** first_elt, struct os_queue * elt) [inline, static]
Insert an element at the begining of the queue.
Parameters:
first_elt A pointer on the variable holding the first element in the queue.
elt The new element to be inserted.
Definition at line 277 of file os_queue.h.
{
    struct os_queue *elt = *first_elt;
    *first_elt = elt->next;
    return elt;
static struct os_queue* os_queue_pop (struct os_queue ** first_elt) [static, read]
Returns and remove the first element from the queue.
Parameters:
first_elt A pointer on the variable holding the first element in the queue.
Returns:
The first element from the queue.
Note:
The queue must not be empty
Definition at line 244 of file os_queue.h.
{
static void os_queue_process_add (struct os_queue_process ** first_elt, struct os_queue_process * new_elt) [inline, static]
Add a new element to the queue. The new element will be added to the end of the queue. If CONFIG_OS_USE_PRIORITY is set, the element will be added according to the priority of the process associated with the queue element. The highest priority goes first.
Parameters:
first_elt A pointer on the variable holding the first element in the queue.
new_elt The new element to be added.
Definition at line 488 of file os_queue.h.
Referenced by os_mutex_lock(), and os_semaphore_take().
{
static void os_queue_process_add_sort (struct os_queue_process ** first_elt, struct os_queue_process * elt, os_queue_sort_t sort_fct) [inline, static]
Alias of os_queue_add_sort \ * \.
Definition at line 466 of file os_queue.h.
{
static struct os_queue_process* os_queue_process_from_queue (struct os_queue * elt) [static, read]
Get the os_process_queue element from the os_queue type \ * \.
Definition at line 466 of file os_queue.h.
{
static struct os_process* os_queue_process_get (struct os_queue_process * elt) [static, read]
Returns the process information held by a os_queue_process element.
Parameters:
elt The os_queue_process element
Returns:
The os_process associated with this element.
Definition at line 474 of file os_queue.h.
References os_queue_process::proc.
    {
static struct os_queue* os_queue_process_get_queue (struct os_queue_process * elt) [static, read]
Get the os_queue element from the os_process_queue type \ * \.
Definition at line 466 of file os_queue.h.
{
static struct os_queue_process* os_queue_process_head (struct os_queue_process * first_elt) [static, read]
Alias of os_queue_head \ * \.
Definition at line 466 of file os_queue.h.
{
static void os_queue_process_insert_after (struct os_queue_process * prev_elt, struct os_queue_process * elt) [inline, static]
Alias of os_queue_insert_after \ * \.
Definition at line 466 of file os_queue.h.
{
static void os_queue_process_insert_first (struct os_queue_process ** first_elt, struct os_queue_process * elt) [inline, static]
Alias of os_queue_insert_first \ * \.
Definition at line 466 of file os_queue.h.
{
static struct os_queue_process* os_queue_process_pop (struct os_queue_process ** first_elt) [static, read]
Alias of os_queue_pop \ * \.
Definition at line 466 of file os_queue.h.
Referenced by os_mutex_unlock(), and os_semaphore_release().
{
static bool os_queue_process_remove (struct os_queue_process ** first_elt, struct os_queue_process * elt) [inline, static]
Alias of os_queue_remove \ * \.
Definition at line 466 of file os_queue.h.
{
bool os_queue_process_sort_priority (struct os_queue * a, struct os_queue * b)
Helper function used to define the order of a new element added to a queue (os_queue). This function will add them so that the highest priority process will be at the head of the list. This function must be used with the type os_queue_sort_t.
Precondition:
CONFIG_OS_USE_PRIORITY must be set
bool os_queue_remove (struct os_queue ** first_elt, struct os_queue * elt)
Remove an element from the queue.
Parameters:
first_elt A pointer on the variable holding the first element in the queue.
elt The element to be removed.
Returns:
true if the element has be successfully removed from the queue. Returns false if the element has not been found.
bool os_queue_sort_fifo (struct os_queue * a, struct os_queue * b)
Helper function used to define the order of a new element added to a queue (os_queue). This function will add them so that the first in will be the first out. This function must be used with the type os_queue_sort_t.
Referenced by __os_event_register().
bool os_queue_sort_lifo (struct os_queue * a, struct os_queue * b)
Helper function used to define the order of a new element added to a queue (os_queue). This function will add them so that the last in will be the first out. This function must be used with the type os_queue_sort_t.