eeOS (Embedded Event-driven Operating System): os_semaphore.c File Reference
os_semaphore.c File Reference
eeOS Semaphores
#include "os_core.h"
Functions
enum os_event_status __os_event_sempahore_is_triggered (struct os_process *proc, os_ptr_t args)
Event trigger function. Take the semphore, use by the event.
void os_semaphore_release (struct os_semaphore *sem)
Releases a semaphore.
void os_semaphore_take (struct os_semaphore *sem)
Take a semaphore. If no semaphore is available, wait until it gets free.
Detailed Description
eeOS Semaphores
Author:
Blaise Lengrand (blaise.lengrand@gmail.com)
Version:
0.1
Date:
2011
License
eeOS is provided in source form for FREE evaluation, for educational use or for peaceful research. If you plan on using eeOS in a commercial product you need to contact the author to properly license its use in your product. The fact that the source is provided does NOT mean that you can use it without paying a licensing fee.
Definition in file os_semaphore.c.
Function Documentation
enum os_event_status __os_event_sempahore_is_triggered (struct os_process * proc, os_ptr_t args)
Event trigger function. Take the semphore, use by the event.
Parameters:
proc The process waiting for the event.
args Extra arguments send with this event.
Returns:
OS_EVENT_NONE if no ressource is available. OS_EVENT_OK_STOP if only 1 is available, OS_EVENT_OK_CONTINUE if more than one.
Definition at line 17 of file os_semaphore.c.
References os_semaphore::counter, os_enter_critical(), os_is_critical(), os_leave_critical(), and os_process::status.
Referenced by os_semaphore_create_event().
{
    /* Initial status set to "no event" */
    enum os_event_status status = OS_EVENT_NONE;
    /* Cast the arguments into a os_semaphore structure */
    struct os_semaphore *sem = (struct os_semaphore *) args;
    /* Save the critical region status */
    bool is_critical = os_is_critical();
    /* Enter in a critical region if not already in */
    if (!is_critical) {
        os_enter_critical();
    }
    /* If there is only 1 semaphore left */
    if (sem->counter == 1) {
        /* Take it */
        sem->counter = 0;
        /* It is the last semaphore so no further check is necessary */
        status = OS_EVENT_OK_STOP;
    }
    /* If there is more than 1 semaphore available */
    else if (sem->counter > 1) {
        /* Take it */
        sem->counter--;
        /* Another process can be triggered with this sempahore, so
         * set the status as "continue"
         */
        status = OS_EVENT_OK_CONTINUE;
    }
    /* Leave the critical region */
    if (!is_critical) {
        os_leave_critical();
    }
    return status;
}