eeOS (Embedded Event-driven Operating System): os_statistics.h File Reference
os_statistics.h File Reference
eeOS Statistics
Defines
#define __HOOK_OS_STATISTICS_SWITCH_CONTEXT_START(offset_cy)
Hook used to get the time information at the entrance of a context task switch (when using os_yield).
#define __HOOK_OS_STATISTICS_SWITCH_CONTEXT_STOP(offset_cy)
Hook used to get the time information at the exit of a context task switch (when using os_yield).
#define __HOOK_OS_STATISTICS_SWITCH_CONTEXT_TICK_HANDLER_START(offset_cy)
Hook used to get the time information at the entrance of a context task switch (tick interrupt handler).
#define __HOOK_OS_STATISTICS_SWITCH_CONTEXT_TICK_HANDLER_STOP(offset_cy)
Hook used to get the time information at the exit of a context task switch (tick interrupt handler).
#define CONFIG_OS_STATISTICS_MONITOR_TASK_SWITCH false
Give statistics about the task switching. This enables the following functions:
os_statistics_get_task_switch_time
os_statistics_get_task_switch_time_jitter.
Functions
void __os_statistics_switch_context_start (os_cy_t offset_cy)
void __os_statistics_switch_context_stop (os_cy_t offset_cy)
void __os_statistics_switch_context_tick_handler_start (os_cy_t offset_cy)
void __os_statistics_switch_context_tick_handler_stop (os_cy_t offset_cy)
void os_statistics_monitor_ram (void)
Statistics
This set of function gives real-time statistics on the current operating system setup.
os_cy_t os_statistics_get_task_switch_time (void)
Get the average time of the context task switching in number of cycles.
os_cy_t os_statistics_get_task_switch_time_jitter (void)
Get the jitter of the context task switching in number of cycles.
uint8_t os_statistics_task_cpu_allocation (struct os_task *task)
Theoretical estimation of the CPU load of a task. It is based on the number of current active tasks in the list and their priority. The ratio of the CPU ressources is calculated as follow:
Detailed Description
eeOS Statistics
Author:
Blaise Lengrand (blaise.lengrand@gmail.com)
Version:
0.1
Date:
2011
License
eeOS is provided in source form for FREE evaluation, for educational use or for peaceful research. If you plan on using eeOS in a commercial product you need to contact the author to properly license its use in your product. The fact that the source is provided does NOT mean that you can use it without paying a licensing fee.
Definition in file os_statistics.h.
Define Documentation
#define __HOOK_OS_STATISTICS_SWITCH_CONTEXT_START (offset_cy)
Value:
do { \
            __os_statistics_switch_context_start(offset_cy); \
        } while (false)
Hook used to get the time information at the entrance of a context task switch (when using os_yield).
Parameters:
offset_cy The number of cycles between the function call and the call of __HOOK_OS_STATISTICS_SWITCH_CONTEXT_START
Definition at line 59 of file os_statistics.h.
#define __HOOK_OS_STATISTICS_SWITCH_CONTEXT_STOP (offset_cy)
Value:
do { \
            __os_statistics_switch_context_stop(offset_cy); \
        } while (false)
Hook used to get the time information at the exit of a context task switch (when using os_yield).
Parameters:
offset_cy The number of cycles between the call of __HOOK_OS_STATISTICS_SWITCH_CONTEXT_STOP and the exit of the function.
Definition at line 69 of file os_statistics.h.
#define __HOOK_OS_STATISTICS_SWITCH_CONTEXT_TICK_HANDLER_START (offset_cy)
Value:
do { \
            __os_statistics_switch_context_tick_handler_start(offset_cy); \
        } while (false)
Hook used to get the time information at the entrance of a context task switch (tick interrupt handler).
Parameters:
offset_cy The number of cycles between the interrupt call and the call of __HOOK_OS_STATISTICS_SWITCH_CONTEXT_TICK_HANDLER_START
Definition at line 40 of file os_statistics.h.
#define __HOOK_OS_STATISTICS_SWITCH_CONTEXT_TICK_HANDLER_STOP (offset_cy)
Value:
do { \
            __os_statistics_switch_context_tick_handler_stop(offset_cy); \
        } while (false)
Hook used to get the time information at the exit of a context task switch (tick interrupt handler).
Parameters:
offset_cy The number of cycles between the call of __HOOK_OS_STATISTICS_SWITCH_CONTEXT_TICK_HANDLER_STOP and the exit of the interrupt handler.
Definition at line 50 of file os_statistics.h.
Function Documentation
void __os_statistics_switch_context_start (os_cy_t offset_cy)
Hook used to get the time information at the entrance of a context task switch (when using os_yield).
Parameters:
offset_cy The number of cycles between the function call and the call of __HOOK_OS_STATISTICS_SWITCH_CONTEXT_START
Definition at line 87 of file os_statistics.c.
References os_read_cycle_counter(), and update_task_cycle_counter_start().
{
    /* Get the current cycle count */
    os_cy_t current_cy = os_read_cycle_counter() - offset_cy;
    /* Start monitoring the task activity time */
    update_task_cycle_counter_start(current_cy);
}
void __os_statistics_switch_context_stop (os_cy_t offset_cy)
Hook used to get the time information at the exit of a context task switch (when using os_yield).
Parameters:
offset_cy The number of cycles between the call of __HOOK_OS_STATISTICS_SWITCH_CONTEXT_STOP and the exit of the function.
Definition at line 94 of file os_statistics.c.
References os_read_cycle_counter(), and update_task_cycle_counter_stop().
{
    /* Get the current cycle count */
    os_cy_t current_cy = os_read_cycle_counter() + offset_cy;
    /* Stop monitoring the task activity time */
    update_task_cycle_counter_stop(current_cy);
}
void __os_statistics_switch_context_tick_handler_start (os_cy_t offset_cy)
Hook used to get the time information at the entrance of a context task switch (tick interrupt handler).
Parameters:
offset_cy The number of cycles between the interrupt call and the call of __HOOK_OS_STATISTICS_SWITCH_CONTEXT_TICK_HANDLER_START
Definition at line 70 of file os_statistics.c.
References measure_context_task_switch_time_start(), os_read_cycle_counter(), and update_task_cycle_counter_start().
{
    /* Get the current cycle count */
    os_cy_t current_cy = os_read_cycle_counter() - offset_cy;
    /* Start monitoring the task switch and task activity time */
    measure_context_task_switch_time_start(current_cy);
    update_task_cycle_counter_start(current_cy);
}
void __os_statistics_switch_context_tick_handler_stop (os_cy_t offset_cy)
Hook used to get the time information at the exit of a context task switch (tick interrupt handler).
Parameters:
offset_cy The number of cycles between the call of __HOOK_OS_STATISTICS_SWITCH_CONTEXT_TICK_HANDLER_STOP and the exit of the interrupt handler.
Definition at line 78 of file os_statistics.c.
References measure_context_task_switch_time_stop(), os_read_cycle_counter(), and update_task_cycle_counter_stop().
{
    /* Get the current cycle count */
    os_cy_t current_cy = os_read_cycle_counter() + offset_cy;
    /* Stop monitoring the task switch and task activity time */
    measure_context_task_switch_time_stop(current_cy);
    update_task_cycle_counter_stop(current_cy);
}
void os_statistics_monitor_ram (void)